package octopusdeploy

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_accounts",
			Category:         "Accounts",
			ShortDescription: `Provides information about existing accounts.`,
			Description:      ``,
			Keywords: []string{
				"accounts",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_cloud_service_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing Azure cloud service deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_service_fabric_cluster_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing Azure service fabric cluster deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_web_app_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing Azure web app deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_certificates",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing certificates.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_channels",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing channels.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_cloud_region_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing cloud region deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_environments",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing environments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_feeds",
			Category:         "Feeds",
			ShortDescription: `Provides information about existing feeds.`,
			Description:      ``,
			Keywords: []string{
				"feeds",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_kubernetes_cluster_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing Kubernetes cluster deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_library_variable_sets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing library variable sets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_lifecycles",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing lifecycles.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_listening_tentacle_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing listening tentacle deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_machine",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_machine_policies",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing machine policies.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_offline_package_drop_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing offline package drop deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_polling_tentacle_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing polling tentacle deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_project_groups",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing project groups.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_projects",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing projects.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_spaces",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing spaces.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_ssh_connection_deployment_targets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing SSH connection deployment targets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_tag_sets",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing tag sets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_teams",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing users.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_tenants",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing tenants.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_user_roles",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing user roles.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_users",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing users.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_variables",
			Category:         "Data Sources",
			ShortDescription: `Provides information about existing variables.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"octopusdeploy_accounts":                                        0,
		"octopusdeploy_azure_cloud_service_deployment_targets":          1,
		"octopusdeploy_azure_service_fabric_cluster_deployment_targets": 2,
		"octopusdeploy_azure_web_app_deployment_targets":                3,
		"octopusdeploy_certificates":                                    4,
		"octopusdeploy_channels":                                        5,
		"octopusdeploy_cloud_region_deployment_targets":                 6,
		"octopusdeploy_deployment_targets":                              7,
		"octopusdeploy_environments":                                    8,
		"octopusdeploy_feeds":                                           9,
		"octopusdeploy_kubernetes_cluster_deployment_targets":           10,
		"octopusdeploy_library_variable_sets":                           11,
		"octopusdeploy_lifecycles":                                      12,
		"octopusdeploy_listening_tentacle_deployment_targets":           13,
		"octopusdeploy_machine":                                         14,
		"octopusdeploy_machine_policies":                                15,
		"octopusdeploy_offline_package_drop_deployment_targets":         16,
		"octopusdeploy_polling_tentacle_deployment_targets":             17,
		"octopusdeploy_project_groups":                                  18,
		"octopusdeploy_projects":                                        19,
		"octopusdeploy_spaces":                                          20,
		"octopusdeploy_ssh_connection_deployment_targets":               21,
		"octopusdeploy_tag_sets":                                        22,
		"octopusdeploy_teams":                                           23,
		"octopusdeploy_tenants":                                         24,
		"octopusdeploy_user_roles":                                      25,
		"octopusdeploy_users":                                           26,
		"octopusdeploy_variables":                                       27,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
