package octopusdeploy

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_account",
			Category:         "Resources",
			ShortDescription: `This resource manages accounts in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_aws_account",
			Category:         "Resources",
			ShortDescription: `This resource manages AWS accounts in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_cloud_service_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages Azure cloud service deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_service_fabric_cluster_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages Azure service fabric cluster deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_service_principal",
			Category:         "Resources",
			ShortDescription: `This resource manages Azure service principal accounts in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_subscription_account",
			Category:         "Resources",
			ShortDescription: `This resource manages Azure subscription accounts in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_azure_web_app_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages Azure web app deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_certificate",
			Category:         "Resources",
			ShortDescription: `This resource manages certificates in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_channel",
			Category:         "Resources",
			ShortDescription: `This resource manages channels in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_cloud_region_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages cloud region deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_deployment_process",
			Category:         "Resources",
			ShortDescription: `This resource manages deployment processes in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_deployment_target",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_environment",
			Category:         "Resources",
			ShortDescription: `This resource manages environments in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_feed",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_kubernetes_cluster_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages Kubernets cluster deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_library_variable_set",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_lifecycle",
			Category:         "Resources",
			ShortDescription: `This resource manages lifecycles in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_listening_tentacle_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages listening tentacle deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_machine_policy",
			Category:         "Resources",
			ShortDescription: `This resource manages machine policies in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_nuget_feed",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_offline_package_drop_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages offline package drop deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_polling_tentacle_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages polling tentacle deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_project",
			Category:         "Resources",
			ShortDescription: `This resource manages projects in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_project_deployment_target_trigger",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_project_group",
			Category:         "Resources",
			ShortDescription: `This resource manages project groups in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_space",
			Category:         "Resources",
			ShortDescription: `This resource manages spaces in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_ssh_connection_deployment_target",
			Category:         "Resources",
			ShortDescription: `This resource manages SSH connection deployment targets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_ssh_key_account",
			Category:         "Resources",
			ShortDescription: `This resource manages SSH key accounts in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_tag_set",
			Category:         "Resources",
			ShortDescription: `This resource manages tag sets in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_team",
			Category:         "Resources",
			ShortDescription: `This resource manages teams in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_tenant",
			Category:         "Resources",
			ShortDescription: `This resource manages tenants in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_token_account",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_user",
			Category:         "Resources",
			ShortDescription: `This resource manages users in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_user_role",
			Category:         "Resources",
			ShortDescription: `This resource manages user roles in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_username_password_account",
			Category:         "Resources",
			ShortDescription: `This resource manages username-password accounts in Octopus Deploy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "octopusdeploy_variable",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"octopusdeploy_account":                                        0,
		"octopusdeploy_aws_account":                                    1,
		"octopusdeploy_azure_cloud_service_deployment_target":          2,
		"octopusdeploy_azure_service_fabric_cluster_deployment_target": 3,
		"octopusdeploy_azure_service_principal":                        4,
		"octopusdeploy_azure_subscription_account":                     5,
		"octopusdeploy_azure_web_app_deployment_target":                6,
		"octopusdeploy_certificate":                                    7,
		"octopusdeploy_channel":                                        8,
		"octopusdeploy_cloud_region_deployment_target":                 9,
		"octopusdeploy_deployment_process":                             10,
		"octopusdeploy_deployment_target":                              11,
		"octopusdeploy_environment":                                    12,
		"octopusdeploy_feed":                                           13,
		"octopusdeploy_kubernetes_cluster_deployment_target":           14,
		"octopusdeploy_library_variable_set":                           15,
		"octopusdeploy_lifecycle":                                      16,
		"octopusdeploy_listening_tentacle_deployment_target":           17,
		"octopusdeploy_machine_policy":                                 18,
		"octopusdeploy_nuget_feed":                                     19,
		"octopusdeploy_offline_package_drop_deployment_target":         20,
		"octopusdeploy_polling_tentacle_deployment_target":             21,
		"octopusdeploy_project":                                        22,
		"octopusdeploy_project_deployment_target_trigger":              23,
		"octopusdeploy_project_group":                                  24,
		"octopusdeploy_space":                                          25,
		"octopusdeploy_ssh_connection_deployment_target":               26,
		"octopusdeploy_ssh_key_account":                                27,
		"octopusdeploy_tag_set":                                        28,
		"octopusdeploy_team":                                           29,
		"octopusdeploy_tenant":                                         30,
		"octopusdeploy_token_account":                                  31,
		"octopusdeploy_user":                                           32,
		"octopusdeploy_user_role":                                      33,
		"octopusdeploy_username_password_account":                      34,
		"octopusdeploy_variable":                                       35,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
