package okta

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "okta_app",
			Category:         "Data Sources",
			ShortDescription: `Get an application of any kind from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_app_group_assignments",
			Category:         "Data Sources",
			ShortDescription: `Get a set of groups assigned to an Okta application.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_app_metadata_saml",
			Category:         "Data Sources",
			ShortDescription: `Get a SAML application's metadata from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_app_oauth",
			Category:         "Data Sources",
			ShortDescription: `Get a OIDC application from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_app_saml",
			Category:         "Data Sources",
			ShortDescription: `Get a SAML application from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_auth_server",
			Category:         "Data Sources",
			ShortDescription: `Get an auth server from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_auth_server_policy",
			Category:         "Data Sources",
			ShortDescription: `Get an authorization server policy from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_auth_server_scopes",
			Category:         "Data Sources",
			ShortDescription: `Get a list of authorization server scopes from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_behavior",
			Category:         "Data Sources",
			ShortDescription: `Get a behavior by name or ID.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_behaviors",
			Category:         "Data Sources",
			ShortDescription: `Get a behaviors by search criteria.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_brand",
			Category:         "Data Sources",
			ShortDescription: `Get a single Brand from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_brands",
			Category:         "Data Sources",
			ShortDescription: `Get the brands belonging to an Okta organization.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_default_policy",
			Category:         "Data Sources",
			ShortDescription: `Get a Default policy from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_email_customization",
			Category:         "Data Sources",
			ShortDescription: `Get the email customization of an email template belonging to a brand in an Okta organization.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_email_customizations",
			Category:         "Data Sources",
			ShortDescription: `Get the email customizations of an email template belonging to a brand in an Okta organization.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_email_template",
			Category:         "Data Sources",
			ShortDescription: `Get a single Email Template for a Brand belonging to an Okta organization.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_email_templates",
			Category:         "Data Sources",
			ShortDescription: `Get the email templates belonging to a brand in an Okta organization.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_everyone_group",
			Category:         "Data Sources",
			ShortDescription: `Get the ` + "`" + `Everyone` + "`" + ` group from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_group",
			Category:         "Data Sources",
			ShortDescription: `Get a group from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_groups",
			Category:         "Data Sources",
			ShortDescription: `Get a list of groups from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_metadata_saml",
			Category:         "Data Sources",
			ShortDescription: `Get SAML IdP metadata from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_oidc",
			Category:         "Data Sources",
			ShortDescription: `Get a OIDC IdP from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_saml",
			Category:         "Data Sources",
			ShortDescription: `Get a SAML IdP from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_social",
			Category:         "Data Sources",
			ShortDescription: `Get a social IdP from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_policy",
			Category:         "Data Sources",
			ShortDescription: `Get a policy from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_user",
			Category:         "Data Sources",
			ShortDescription: `Get a single users from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_user_profile_mapping_source",
			Category:         "Data Sources",
			ShortDescription: `Get the base user Profile Mapping source or target from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_user_security_questions",
			Category:         "Data Sources",
			ShortDescription: `Get a list of user's security questions.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_user_type",
			Category:         "Data Sources",
			ShortDescription: `Get a user type from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_users",
			Category:         "Data Sources",
			ShortDescription: `Get a list of users from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"okta_app":                         0,
		"okta_app_group_assignments":       1,
		"okta_app_metadata_saml":           2,
		"okta_app_oauth":                   3,
		"okta_app_saml":                    4,
		"okta_auth_server":                 5,
		"okta_auth_server_policy":          6,
		"okta_auth_server_scopes":          7,
		"okta_behavior":                    8,
		"okta_behaviors":                   9,
		"okta_brand":                       10,
		"okta_brands":                      11,
		"okta_default_policy":              12,
		"okta_email_customization":         13,
		"okta_email_customizations":        14,
		"okta_email_template":              15,
		"okta_email_templates":             16,
		"okta_everyone_group":              17,
		"okta_group":                       18,
		"okta_groups":                      19,
		"okta_idp_metadata_saml":           20,
		"okta_idp_oidc":                    21,
		"okta_idp_saml":                    22,
		"okta_idp_social":                  23,
		"okta_policy":                      24,
		"okta_user":                        25,
		"okta_user_profile_mapping_source": 26,
		"okta_user_security_questions":     27,
		"okta_user_type":                   28,
		"okta_users":                       29,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
