package okta

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "okta_app",
			Category:         "Data Sources",
			ShortDescription: `Get an application of any kind from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_app_metadata_saml",
			Category:         "Data Sources",
			ShortDescription: `Get a SAML application's metadata from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_app_oauth",
			Category:         "Data Sources",
			ShortDescription: `Get a OIDC application from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_app_saml",
			Category:         "Data Sources",
			ShortDescription: `Get a SAML application from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_auth_server",
			Category:         "Data Sources",
			ShortDescription: `Get an auth server from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_auth_server_policy",
			Category:         "Data Sources",
			ShortDescription: `Get an authorization server policy from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_auth_server_scopes",
			Category:         "Data Sources",
			ShortDescription: `Get a list of authorization server scopes from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_default_policy",
			Category:         "Data Sources",
			ShortDescription: `Get a Default policy from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_everyone_group",
			Category:         "Data Sources",
			ShortDescription: `Get the ` + "`" + `Everyone` + "`" + ` group from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_group",
			Category:         "Data Sources",
			ShortDescription: `Get a group from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_groups",
			Category:         "Data Sources",
			ShortDescription: `Get a list of groups from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_metadata_saml",
			Category:         "Data Sources",
			ShortDescription: `Get SAML IdP metadata from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_oidc",
			Category:         "Data Sources",
			ShortDescription: `Get a OIDC IdP from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_saml",
			Category:         "Data Sources",
			ShortDescription: `Get a SAML IdP from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_idp_social",
			Category:         "Data Sources",
			ShortDescription: `Get a social IdP from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_policy",
			Category:         "Data Sources",
			ShortDescription: `Get a policy from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_user",
			Category:         "Data Sources",
			ShortDescription: `Get a single users from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_user_profile_mapping_source",
			Category:         "Data Sources",
			ShortDescription: `Get the base user Profile Mapping source or target from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_user_type",
			Category:         "Data Sources",
			ShortDescription: `Get a user type from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "okta_users",
			Category:         "Data Sources",
			ShortDescription: `Get a list of users from Okta.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"okta_app":                         0,
		"okta_app_metadata_saml":           1,
		"okta_app_oauth":                   2,
		"okta_app_saml":                    3,
		"okta_auth_server":                 4,
		"okta_auth_server_policy":          5,
		"okta_auth_server_scopes":          6,
		"okta_default_policy":              7,
		"okta_everyone_group":              8,
		"okta_group":                       9,
		"okta_groups":                      10,
		"okta_idp_metadata_saml":           11,
		"okta_idp_oidc":                    12,
		"okta_idp_saml":                    13,
		"okta_idp_social":                  14,
		"okta_policy":                      15,
		"okta_user":                        16,
		"okta_user_profile_mapping_source": 17,
		"okta_user_type":                   18,
		"okta_users":                       19,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
