package gcorelabs

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_baremetal",
			Category:         "Resources",
			ShortDescription: `Represent baremetal instance`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_cdn_origingroup",
			Category:         "Resources",
			ShortDescription: `Represent origin group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_cdn_resource",
			Category:         "Resources",
			ShortDescription: `Represent CDN resource`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_cdn_rule",
			Category:         "Resources",
			ShortDescription: `Represent cdn resource rule`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_cdn_sslcert",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_dns_zone",
			Category:         "Resources",
			ShortDescription: `Represent DNS zone resource. https://dns.gcorelabs.com/zones`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_dns_zone_record",
			Category:         "Resources",
			ShortDescription: `Represent DNS Zone Record resource. https://dns.gcorelabs.com/zones`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_floatingip",
			Category:         "Resources",
			ShortDescription: `A floating IP is a static IP address that points to one of your Instances. It allows you to redirect network traffic to any of your Instances in the same datacenter.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_instance",
			Category:         "Resources",
			ShortDescription: `Represent instance`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_k8s",
			Category:         "Resources",
			ShortDescription: `Represent k8s cluster with one default pool.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_k8s_pool",
			Category:         "Resources",
			ShortDescription: `Represent k8s cluster's pool.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_keypair",
			Category:         "Resources",
			ShortDescription: `Represent a ssh key, do not depends on region`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_lblistener",
			Category:         "Resources",
			ShortDescription: `Represent load balancer listener. Can not be created without load balancer. A listener is a process that checks for connection requests, using the protocol and port that you configure`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_lbmember",
			Category:         "Resources",
			ShortDescription: `Represent load balancer member`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_lbpool",
			Category:         "Resources",
			ShortDescription: `Represent load balancer listener pool. A pool is a list of virtual machines to which the listener will redirect incoming traffic`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_lifecyclepolicy",
			Category:         "Resources",
			ShortDescription: `Represent lifecycle policy. Use to periodically take snapshots`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_loadbalancer",
			Category:         "Resources",
			ShortDescription: `Represent load balancer`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_loadbalancerv2",
			Category:         "Resources",
			ShortDescription: `Represent load balancer without nested listener`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_network",
			Category:         "Resources",
			ShortDescription: `Represent network. A network is a software-defined network in a cloud computing infrastructure`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_reservedfixedip",
			Category:         "Resources",
			ShortDescription: `Represent reserved ips`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_router",
			Category:         "Resources",
			ShortDescription: `Represent router. Router enables you to dynamically exchange routes between networks`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_secret",
			Category:         "Resources",
			ShortDescription: `Represent secret`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_securitygroup",
			Category:         "Resources",
			ShortDescription: `Represent SecurityGroups(Firewall)`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_servergroup",
			Category:         "Resources",
			ShortDescription: `Represent server group resource`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_snapshot",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_storage_s3",
			Category:         "Resources",
			ShortDescription: `Represent s3 storage resource. https://storage.gcorelabs.com/storage/list`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_storage_s3_bucket",
			Category:         "Resources",
			ShortDescription: `Represent s3 storage bucket resource. https://storage.gcorelabs.com/storage/list`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_storage_sftp",
			Category:         "Resources",
			ShortDescription: `Represent sftp storage resource. https://storage.gcorelabs.com/storage/list`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_storage_sftp_key",
			Category:         "Resources",
			ShortDescription: `Represent storage key resource. https://storage.gcorelabs.com/ssh-key/list`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_subnet",
			Category:         "Resources",
			ShortDescription: `Represent subnets. Subnetwork is a range of IP addresses in a cloud network. Addresses from this range will be assigned to machines in the cloud`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gcorelabs_gcore_volume",
			Category:         "Resources",
			ShortDescription: `Represent volume. A volume is a file storage which is similar to SSD and HDD hard disks but located in the cloud`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"gcorelabs_gcore_baremetal":         0,
		"gcorelabs_gcore_cdn_origingroup":   1,
		"gcorelabs_gcore_cdn_resource":      2,
		"gcorelabs_gcore_cdn_rule":          3,
		"gcorelabs_gcore_cdn_sslcert":       4,
		"gcorelabs_gcore_dns_zone":          5,
		"gcorelabs_gcore_dns_zone_record":   6,
		"gcorelabs_gcore_floatingip":        7,
		"gcorelabs_gcore_instance":          8,
		"gcorelabs_gcore_k8s":               9,
		"gcorelabs_gcore_k8s_pool":          10,
		"gcorelabs_gcore_keypair":           11,
		"gcorelabs_gcore_lblistener":        12,
		"gcorelabs_gcore_lbmember":          13,
		"gcorelabs_gcore_lbpool":            14,
		"gcorelabs_gcore_lifecyclepolicy":   15,
		"gcorelabs_gcore_loadbalancer":      16,
		"gcorelabs_gcore_loadbalancerv2":    17,
		"gcorelabs_gcore_network":           18,
		"gcorelabs_gcore_reservedfixedip":   19,
		"gcorelabs_gcore_router":            20,
		"gcorelabs_gcore_secret":            21,
		"gcorelabs_gcore_securitygroup":     22,
		"gcorelabs_gcore_servergroup":       23,
		"gcorelabs_gcore_snapshot":          24,
		"gcorelabs_gcore_storage_s3":        25,
		"gcorelabs_gcore_storage_s3_bucket": 26,
		"gcorelabs_gcore_storage_sftp":      27,
		"gcorelabs_gcore_storage_sftp_key":  28,
		"gcorelabs_gcore_subnet":            29,
		"gcorelabs_gcore_volume":            30,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
