package grafana

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_ips",
			Category:         "Cloud",
			ShortDescription: `Data source for retrieving sets of cloud IPs. See https://grafana.com/docs/grafana-cloud/reference/allow-list/ for more info`,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"ips",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_organization",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"organization",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_stack",
			Category:         "Cloud",
			ShortDescription: `Data source for Grafana Stack`,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"stack",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_dashboard",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/dashboards/Folder/Dashboard Search HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/folder_dashboard_search/Dashboard HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"dashboard",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_dashboards",
			Category:         "Grafana OSS",
			ShortDescription: `Datasource for retrieving all dashboards. Specify list of folder IDs to search in for dashboards. Official documentation https://grafana.com/docs/grafana/latest/dashboards/Folder/Dashboard Search HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/folder_dashboard_search/Dashboard HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"dashboards",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_data_source",
			Category:         "Grafana OSS",
			ShortDescription: `Get details about a Grafana Datasource querying by either name, uid or ID`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"data",
				"source",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_folder",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/folder/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"folder",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_folders",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/folder/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"folders",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_library_panel",
			Category:         "Grafana OSS",
			ShortDescription: `Data source for retrieving a single library panel by name or uid.`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"library",
				"panel",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_action",
			Category:         "OnCall",
			ShortDescription: `Note: This data source is going to be deprecated, please use outgoing webhook data source instead. * HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/outgoing_webhooks/ !> Deprecated: Use the grafana_oncall_outgoing_webhook data source instead.`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"action",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_escalation_chain",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/escalation_chains/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"escalation",
				"chain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_outgoing_webhook",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/outgoing_webhooks/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"outgoing",
				"webhook",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_schedule",
			Category:         "OnCall",
			ShortDescription: `Official documentation https://grafana.com/docs/oncall/latest/calendar-schedules/HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/schedules/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"schedule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_slack_channel",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/slack_channels/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"slack",
				"channel",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_team",
			Category:         "OnCall",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"team",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_user",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/users/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_user_group",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/user_groups/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"user",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_organization",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/organization-management/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/org/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"organization",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_organization_preferences",
			Category:         "Grafana OSS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"oss",
				"organization",
				"preferences",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_slos",
			Category:         "SLO",
			ShortDescription: `Datasource for retrieving all SLOs. Official documentation https://grafana.com/docs/grafana-cloud/slo/API documentation https://grafana.com/docs/grafana-cloud/slo/api/`,
			Description:      ``,
			Keywords: []string{
				"slo",
				"slos",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_synthetic_monitoring_probe",
			Category:         "Synthetic Monitoring",
			ShortDescription: `Data source for retrieving a single probe by name.`,
			Description:      ``,
			Keywords: []string{
				"synthetic",
				"monitoring",
				"probe",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_synthetic_monitoring_probes",
			Category:         "Synthetic Monitoring",
			ShortDescription: `Data source for retrieving all probes.`,
			Description:      ``,
			Keywords: []string{
				"synthetic",
				"monitoring",
				"probes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_team",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/team-management/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/team/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"team",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_user",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/user-management/server-user-management/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/user/ This data source uses Grafana's admin APIs for reading users which does not currently work with API Tokens. You must use basic auth.`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_users",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/user-management/server-user-management/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/user/ This data source uses Grafana's admin APIs for reading users which does not currently work with API Tokens. You must use basic auth.`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"users",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"grafana_cloud_ips":                   0,
		"grafana_cloud_organization":          1,
		"grafana_cloud_stack":                 2,
		"grafana_dashboard":                   3,
		"grafana_dashboards":                  4,
		"grafana_data_source":                 5,
		"grafana_folder":                      6,
		"grafana_folders":                     7,
		"grafana_library_panel":               8,
		"grafana_oncall_action":               9,
		"grafana_oncall_escalation_chain":     10,
		"grafana_oncall_outgoing_webhook":     11,
		"grafana_oncall_schedule":             12,
		"grafana_oncall_slack_channel":        13,
		"grafana_oncall_team":                 14,
		"grafana_oncall_user":                 15,
		"grafana_oncall_user_group":           16,
		"grafana_organization":                17,
		"grafana_organization_preferences":    18,
		"grafana_slos":                        19,
		"grafana_synthetic_monitoring_probe":  20,
		"grafana_synthetic_monitoring_probes": 21,
		"grafana_team":                        22,
		"grafana_user":                        23,
		"grafana_users":                       24,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
