package grafana

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "grafana_alert_notification",
			Category:         "Deprecated",
			ShortDescription: `This resource is used to configure the legacy alerting system which has been replaced by the unified alerting system https://grafana.com/docs/grafana/latest/alerting/ in Grafana 9+. See resources in the Alerting section https://registry.terraform.io/providers/grafana/grafana/latest/docs for info on how to configure alerting with Terraform. * HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/alerting_notification_channels/ !> Deprecated: This resource is used to configure the legacy alerting system which has been replaced by the unified alerting system https://grafana.com/docs/grafana/latest/alerting/ in Grafana 9+. See resources in the Alerting section https://registry.terraform.io/providers/grafana/grafana/latest/docs for info on how to configure alerting with Terraform.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"alert",
				"notification",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_annotation",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/annotate-visualizations/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/annotations/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"annotation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_api_key",
			Category:         "Grafana OSS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"oss",
				"api",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_builtin_role_assignment",
			Category:         "Grafana Enterprise",
			ShortDescription: `Note: This resource is going to be deprecated with Grafana 9.+, please use grafana_role https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/role instead. Note: This resource is available only with Grafana Enterprise 8.+. Official documentation https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/access_control/`,
			Description:      ``,
			Keywords: []string{
				"enterprise",
				"builtin",
				"role",
				"assignment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_access_policy",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"access",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_access_policy_token",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"access",
				"policy",
				"token",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_api_key",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"api",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_plugin_installation",
			Category:         "Cloud",
			ShortDescription: `Manages Grafana Cloud Plugin Installations. Plugin Catalog https://grafana.com/grafana/plugins/`,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"plugin",
				"installation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_stack",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"stack",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_stack_api_key",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"stack",
				"api",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_stack_service_account",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"stack",
				"service",
				"account",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_cloud_stack_service_account_token",
			Category:         "Cloud",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"stack",
				"service",
				"account",
				"token",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_contact_point",
			Category:         "Alerting",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"alerting",
				"contact",
				"point",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_dashboard",
			Category:         "Grafana OSS",
			ShortDescription: `Manages Grafana dashboards. Official documentation https://grafana.com/docs/grafana/latest/dashboards/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"dashboard",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_dashboard_permission",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/dashboard_permissions/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"dashboard",
				"permission",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_data_source",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/datasources/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/data_source/ The required arguments for this resource vary depending on the type of data source selected (via the 'type' argument).`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"data",
				"source",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_data_source_permission",
			Category:         "Grafana Enterprise",
			ShortDescription: `HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/datasource_permissions/`,
			Description:      ``,
			Keywords: []string{
				"enterprise",
				"data",
				"source",
				"permission",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_folder",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/dashboards/manage-dashboards/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/folder/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"folder",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_folder_permission",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/folder_permissions/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"folder",
				"permission",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_library_panel",
			Category:         "Grafana OSS",
			ShortDescription: `Manages Grafana library panels. Official documentation https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/manage-library-panels/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/library_element/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"library",
				"panel",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_machine_learning_holiday",
			Category:         "Cloud",
			ShortDescription: `A holiday describes time periods where a time series is expected to behave differently to normal. To use a holiday in a job, use its id in the holidays attribute of a grafana_machine_learning_job: terraform resource "grafana_machine_learning_job" "test_job" { ... holidays = [ grafana_machine_learning_holiday.my_holiday.id ] }`,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"machine",
				"learning",
				"holiday",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_machine_learning_job",
			Category:         "Cloud",
			ShortDescription: `A job defines the queries and model parameters for a machine learning task.`,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"machine",
				"learning",
				"job",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_machine_learning_outlier_detector",
			Category:         "Cloud",
			ShortDescription: `An outlier detector monitors the results of a query and reports when its values are outside normal bands. The normal band is configured by choice of algorithm, its sensitivity and other configuration. Visit https://grafana.com/docs/grafana-cloud/machine-learning/outlier-detection/ for more details.`,
			Description:      ``,
			Keywords: []string{
				"cloud",
				"machine",
				"learning",
				"outlier",
				"detector",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_message_template",
			Category:         "Alerting",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"alerting",
				"message",
				"template",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_mute_timing",
			Category:         "Alerting",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"alerting",
				"mute",
				"timing",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_notification_policy",
			Category:         "Alerting",
			ShortDescription: `Sets the global notification policy for Grafana. !> This resource manages the entire notification policy tree, and will overwrite any existing policies. Official documentation https://grafana.com/docs/grafana/latest/alerting/manage-notifications/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/ This resource requires Grafana 9.1.0 or later.`,
			Description:      ``,
			Keywords: []string{
				"alerting",
				"notification",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_escalation",
			Category:         "OnCall",
			ShortDescription: `Official documentation https://grafana.com/docs/oncall/latest/escalation-policies/HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/escalation_policies/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"escalation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_escalation_chain",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/escalation_chains/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"escalation",
				"chain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_integration",
			Category:         "OnCall",
			ShortDescription: `Official documentation https://grafana.com/docs/oncall/latest/integrations/HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"integration",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_on_call_shift",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/on_call_shifts/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"on",
				"call",
				"shift",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_outgoing_webhook",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/outgoing_webhooks/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"outgoing",
				"webhook",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_route",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/routes/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"route",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_oncall_schedule",
			Category:         "OnCall",
			ShortDescription: `HTTP API https://grafana.com/docs/oncall/latest/oncall-api-reference/schedules/`,
			Description:      ``,
			Keywords: []string{
				"oncall",
				"schedule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_organization",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/organization-management/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/org/ This resource represents an instance-scoped resource and uses Grafana's admin APIs. It does not work with API tokens or service accounts which are org-scoped. You must use basic auth.`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"organization",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_organization_preferences",
			Category:         "Grafana OSS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"oss",
				"organization",
				"preferences",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_playlist",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/dashboards/create-manage-playlists/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/playlist/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"playlist",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_report",
			Category:         "Grafana Enterprise",
			ShortDescription: `Note: This resource is available only with Grafana Enterprise 7.+. Official documentation https://grafana.com/docs/grafana/latest/dashboards/create-reports/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/reporting/`,
			Description:      ``,
			Keywords: []string{
				"enterprise",
				"report",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_role",
			Category:         "Grafana Enterprise",
			ShortDescription: `Note: This resource is available only with Grafana Enterprise 8.+. Official documentation https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/access_control/`,
			Description:      ``,
			Keywords: []string{
				"enterprise",
				"role",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_role_assignment",
			Category:         "Grafana Enterprise",
			ShortDescription: `Note: This resource is available only with Grafana Enterprise 9.2+. * Official documentation https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/ * HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/access_control/`,
			Description:      ``,
			Keywords: []string{
				"enterprise",
				"role",
				"assignment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_rule_group",
			Category:         "Alerting",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"alerting",
				"rule",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_service_account",
			Category:         "Grafana OSS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"oss",
				"service",
				"account",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_service_account_permission",
			Category:         "Grafana OSS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"oss",
				"service",
				"account",
				"permission",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_service_account_token",
			Category:         "Grafana OSS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"oss",
				"service",
				"account",
				"token",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_slo",
			Category:         "SLO",
			ShortDescription: `Resource manages Grafana SLOs. Official documentation https://grafana.com/docs/grafana-cloud/slo/API documentation https://grafana.com/docs/grafana-cloud/slo/api/`,
			Description:      ``,
			Keywords: []string{
				"slo",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_synthetic_monitoring_check",
			Category:         "Synthetic Monitoring",
			ShortDescription: `Synthetic Monitoring checks are tests that run on selected probes at defined intervals and report metrics and logs back to your Grafana Cloud account. The target for checks can be a domain name, a server, or a website, depending on what information you would like to gather about your endpoint. You can define multiple checks for a single endpoint to check different capabilities. Official documentation https://grafana.com/docs/grafana-cloud/synthetic-monitoring/checks/`,
			Description:      ``,
			Keywords: []string{
				"synthetic",
				"monitoring",
				"check",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_synthetic_monitoring_installation",
			Category:         "Synthetic Monitoring",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"synthetic",
				"monitoring",
				"installation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_synthetic_monitoring_probe",
			Category:         "Synthetic Monitoring",
			ShortDescription: `Besides the public probes run by Grafana Labs, you can also install your own private probes. These are only accessible to you and only write data to your Grafana Cloud account. Private probes are instances of the open source Grafana Synthetic Monitoring Agent. Official documentation https://grafana.com/docs/grafana-cloud/synthetic-monitoring/private-probes/`,
			Description:      ``,
			Keywords: []string{
				"synthetic",
				"monitoring",
				"probe",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_team",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/team-management/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/team/`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"team",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_team_external_group",
			Category:         "Grafana Enterprise",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-team-sync/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/external_group_sync/`,
			Description:      ``,
			Keywords: []string{
				"enterprise",
				"team",
				"external",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_team_preferences",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/organization-preferences/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/team/ !> Deprecated: Use the preferences attribute of the grafana_team resource instead.`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"team",
				"preferences",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "grafana_user",
			Category:         "Grafana OSS",
			ShortDescription: `Official documentation https://grafana.com/docs/grafana/latest/administration/user-management/server-user-management/HTTP API https://grafana.com/docs/grafana/latest/developers/http_api/user/ This resource represents an instance-scoped resource and uses Grafana's admin APIs. It does not work with API tokens or service accounts which are org-scoped. You must use basic auth.`,
			Description:      ``,
			Keywords: []string{
				"oss",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"grafana_alert_notification":                0,
		"grafana_annotation":                        1,
		"grafana_api_key":                           2,
		"grafana_builtin_role_assignment":           3,
		"grafana_cloud_access_policy":               4,
		"grafana_cloud_access_policy_token":         5,
		"grafana_cloud_api_key":                     6,
		"grafana_cloud_plugin_installation":         7,
		"grafana_cloud_stack":                       8,
		"grafana_cloud_stack_api_key":               9,
		"grafana_cloud_stack_service_account":       10,
		"grafana_cloud_stack_service_account_token": 11,
		"grafana_contact_point":                     12,
		"grafana_dashboard":                         13,
		"grafana_dashboard_permission":              14,
		"grafana_data_source":                       15,
		"grafana_data_source_permission":            16,
		"grafana_folder":                            17,
		"grafana_folder_permission":                 18,
		"grafana_library_panel":                     19,
		"grafana_machine_learning_holiday":          20,
		"grafana_machine_learning_job":              21,
		"grafana_machine_learning_outlier_detector": 22,
		"grafana_message_template":                  23,
		"grafana_mute_timing":                       24,
		"grafana_notification_policy":               25,
		"grafana_oncall_escalation":                 26,
		"grafana_oncall_escalation_chain":           27,
		"grafana_oncall_integration":                28,
		"grafana_oncall_on_call_shift":              29,
		"grafana_oncall_outgoing_webhook":           30,
		"grafana_oncall_route":                      31,
		"grafana_oncall_schedule":                   32,
		"grafana_organization":                      33,
		"grafana_organization_preferences":          34,
		"grafana_playlist":                          35,
		"grafana_report":                            36,
		"grafana_role":                              37,
		"grafana_role_assignment":                   38,
		"grafana_rule_group":                        39,
		"grafana_service_account":                   40,
		"grafana_service_account_permission":        41,
		"grafana_service_account_token":             42,
		"grafana_slo":                               43,
		"grafana_synthetic_monitoring_check":        44,
		"grafana_synthetic_monitoring_installation": 45,
		"grafana_synthetic_monitoring_probe":        46,
		"grafana_team":                              47,
		"grafana_team_external_group":               48,
		"grafana_team_preferences":                  49,
		"grafana_user":                              50,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
