package akamai

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_evasive_path_match",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsEvasivePathMatch`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"evasive",
				"path",
				"match",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "config_id",
					Description: `(Required) The configuration ID.`,
				},
				resource.Attribute{
					Name:        "security_policy_id",
					Description: `(Optional) The ID of the security policy to use. ## Attributes Reference In addition to the arguments above, the following attributes are exported:`,
				},
				resource.Attribute{
					Name:        "json",
					Description: `A JSON-formatted list of information about the evasive path match settings.`,
				},
				resource.Attribute{
					Name:        "output_text",
					Description: `A tabular display showing the evasive path match settings.`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "json",
					Description: `A JSON-formatted list of information about the evasive path match settings.`,
				},
				resource.Attribute{
					Name:        "output_text",
					Description: `A tabular display showing the evasive path match settings.`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_logging",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsLogging`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"logging",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_pragma_header",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsPragmaHeader`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"pragma",
				"header",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_prefetch",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsPrefetch`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"prefetch",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_api_endpoints",
			Category:         "Application Security",
			ShortDescription: `ApiEndpoints`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"api",
				"endpoints",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_api_request_constraints",
			Category:         "Application Security",
			ShortDescription: `ApiRequestConstraints`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"api",
				"request",
				"constraints",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_attack_groups",
			Category:         "Application Security",
			ShortDescription: `KRS Attack Groups`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"attack",
				"groups",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_bypass_network_lists",
			Category:         "Application Security",
			ShortDescription: `BypassNetworkLists`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"bypass",
				"network",
				"lists",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_configuration",
			Category:         "Application Security",
			ShortDescription: `Configuration`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"configuration",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_configuration_version",
			Category:         "Application Security",
			ShortDescription: `ConfigurationVersion`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"configuration",
				"version",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_contracts_groups",
			Category:         "Application Security",
			ShortDescription: `ContractsGroups`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"contracts",
				"groups",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_custom_deny",
			Category:         "Application Security",
			ShortDescription: `CustomDeny`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"custom",
				"deny",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_custom_rule_actions",
			Category:         "Application Security",
			ShortDescription: `Custom Rule Actions`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"custom",
				"rule",
				"actions",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_custom_rules",
			Category:         "Application Security",
			ShortDescription: `CustomRules`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"custom",
				"rules",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_eval_groups",
			Category:         "Application Security",
			ShortDescription: `Evaluation Attack Groups`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"eval",
				"groups",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_eval_rules",
			Category:         "Application Security",
			ShortDescription: `Evaluation Rules`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"eval",
				"rules",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_export_configuration",
			Category:         "Application Security",
			ShortDescription: `ExportConfiguration`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"export",
				"configuration",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_failover_hostnames",
			Category:         "Application Security",
			ShortDescription: `FailoverHostnames`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"failover",
				"hostnames",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_hostname_coverage",
			Category:         "Application Security",
			ShortDescription: `HostnameCoverage`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"hostname",
				"coverage",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_hostname_coverage_match_targets",
			Category:         "Application Security",
			ShortDescription: `ApiHostnameCoverageMatchTargets`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"hostname",
				"coverage",
				"match",
				"targets",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_hostname_coverage_overlapping",
			Category:         "Application Security",
			ShortDescription: `ApiHostnameCoverageOverlapping`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"hostname",
				"coverage",
				"overlapping",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_ip_geo",
			Category:         "Application Security",
			ShortDescription: `IP/Geo`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"ip",
				"geo",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_match_targets",
			Category:         "Application Security",
			ShortDescription: `MatchTargets`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"match",
				"targets",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_penalty_box",
			Category:         "Application Security",
			ShortDescription: `Penalty Box`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"penalty",
				"box",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rate_policies",
			Category:         "Application Security",
			ShortDescription: `Rate Policies`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rate",
				"policies",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rate_policy_actions",
			Category:         "Application Security",
			ShortDescription: `Rate Policy Actions`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rate",
				"policy",
				"actions",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_reputation_profile_actions",
			Category:         "Application Security",
			ShortDescription: `Reputation Profile Actions`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"reputation",
				"profile",
				"actions",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_reputation_profile_analysis",
			Category:         "Application Security",
			ShortDescription: `Reputation Profile Analysis`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"reputation",
				"profile",
				"analysis",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_reputation_profiles",
			Category:         "Application Security",
			ShortDescription: `Reputation Profiles`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"reputation",
				"profiles",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rule_upgrade_details",
			Category:         "Application Security",
			ShortDescription: `Rule Upgrade Details`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rule",
				"upgrade",
				"details",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rules",
			Category:         "Application Security",
			ShortDescription: `KRS Rules`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rules",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_security_policy",
			Category:         "Application Security",
			ShortDescription: `SecurityPolicy`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_security_policy_protections",
			Category:         "Application Security",
			ShortDescription: `Security Policy Protections`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"policy",
				"protections",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_selectable_hostnames",
			Category:         "Application Security",
			ShortDescription: `SelectableHostnames`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"selectable",
				"hostnames",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_selected_hostnames",
			Category:         "Application Security",
			ShortDescription: `SelectedHostnames`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"selected",
				"hostnames",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_siem_definitions",
			Category:         "Application Security",
			ShortDescription: `SiemDefinitions`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"siem",
				"definitions",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_siem_settings",
			Category:         "Application Security",
			ShortDescription: `SiemSettings`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"siem",
				"settings",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_slow_post",
			Category:         "Application Security",
			ShortDescription: `Slow Post`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"slow",
				"post",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_threat_intel",
			Category:         "Application Security",
			ShortDescription: `Threat Intelligence`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"threat",
				"intel",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_tuning_recommendations",
			Category:         "Application Security",
			ShortDescription: `TuningRecommendations`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"tuning",
				"recommendations",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "config_id",
					Description: `(Required). Unique identifier of the security configuration you want tuning recommendations for.`,
				},
				resource.Attribute{
					Name:        "security_policy_id",
					Description: `(Required). Unique identifier of the security policy you want tuning recommendations for.`,
				},
				resource.Attribute{
					Name:        "ruleset_type",
					Description: `(Optional). Type of ruleset used by the security configuration you want tuning recommendations for. Supported values are ` + "`" + `active` + "`" + ` and ` + "`" + `evaluation` + "`" + `. Defaults to ` + "`" + `active` + "`" + `.`,
				},
				resource.Attribute{
					Name:        "attack_group",
					Description: `(Optional). Unique name of the attack group you want tuning recommendations for. If not included, recommendations are returned for all attack groups. ## Attributes Reference In addition to the arguments above, the following attribute is exported:`,
				},
				resource.Attribute{
					Name:        "json",
					Description: `JSON-formatted list of the tuning recommendations for the security policy or the attack group. The exception block format in a recommendation conforms to the exception block format used in ` + "`" + `condition_exception` + "`" + ` element of ` + "`" + `attack_group` + "`" + ` resource.`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "json",
					Description: `JSON-formatted list of the tuning recommendations for the security policy or the attack group. The exception block format in a recommendation conforms to the exception block format used in ` + "`" + `condition_exception` + "`" + ` element of ` + "`" + `attack_group` + "`" + ` resource.`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_version_notes",
			Category:         "Application Security",
			ShortDescription: `VersionNotes`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"version",
				"notes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_waf_mode",
			Category:         "Application Security",
			ShortDescription: `WAF Mode`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"waf",
				"mode",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_wap_selected_hostnames",
			Category:         "Application Security",
			ShortDescription: `WAPSelectedHostnames`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"wap",
				"selected",
				"hostnames",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_authorities_set",
			Category:         "DNS",
			ShortDescription: `DNS Authorities Set`,
			Description:      ``,
			Keywords: []string{
				"dns",
				"authorities",
				"set",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_api_prioritization_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `API Prioritization match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"api",
				"prioritization",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_application_load_balancer",
			Category:         "Cloudlets",
			ShortDescription: `Application Load Balancer`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"application",
				"load",
				"balancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_application_load_balancer_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `Application Load Balancer match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"application",
				"load",
				"balancer",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_audience_segmentation_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `Audience Segmentation match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"audience",
				"segmentation",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_edge_redirector_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `Edge Redirector match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"edge",
				"redirector",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_forward_rewrite_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `Forward Rewrite match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"forward",
				"rewrite",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_phased_release_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `Phased Release match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"phased",
				"release",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_policy",
			Category:         "Cloudlets",
			ShortDescription: `Cloudlets policy`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_request_control_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `Request Control match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"request",
				"control",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_visitor_prioritization_match_rule",
			Category:         "Cloudlets",
			ShortDescription: `Visitor Prioritization match rule`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"visitor",
				"prioritization",
				"match",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_contract",
			Category:         "Common",
			ShortDescription: `Contract`,
			Description:      ``,
			Keywords: []string{
				"common",
				"contract",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_contracts",
			Category:         "Common",
			ShortDescription: `Property contracts`,
			Description:      ``,
			Keywords: []string{
				"common",
				"contracts",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cp_code",
			Category:         "Property Provisioning",
			ShortDescription: `CP Code`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"cp",
				"code",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_datastream_activation_history",
			Category:         "DataStream",
			ShortDescription: `Activation History`,
			Description:      ``,
			Keywords: []string{
				"datastream",
				"activation",
				"history",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_datastream_dataset_fields",
			Category:         "DataStream",
			ShortDescription: `Data Set Fields`,
			Description:      ``,
			Keywords: []string{
				"datastream",
				"dataset",
				"fields",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_edgeworkers_property_rules",
			Category:         "EdgeWorkers",
			ShortDescription: `EdgeWorkers Property Rules`,
			Description:      ``,
			Keywords: []string{
				"edgeworkers",
				"property",
				"rules",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_edgeworkers_resource_tier",
			Category:         "EdgeWorkers",
			ShortDescription: `EdgeWorkers resource tier`,
			Description:      ``,
			Keywords: []string{
				"edgeworkers",
				"resource",
				"tier",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_group",
			Category:         "Common",
			ShortDescription: `Group`,
			Description:      ``,
			Keywords: []string{
				"common",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_groups",
			Category:         "Common",
			ShortDescription: `Property groups`,
			Description:      ``,
			Keywords: []string{
				"common",
				"groups",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_default_datacenter",
			Category:         "Global Traffic Management",
			ShortDescription: `Default data center`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"default",
				"datacenter",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_contact_types",
			Category:         "IAM",
			ShortDescription: `IAM Contact Types`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"contact",
				"types",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_countries",
			Category:         "IAM",
			ShortDescription: `IAM Countries`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"countries",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_groups",
			Category:         "IAM",
			ShortDescription: `IAM Groups`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"groups",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_roles",
			Category:         "IAM",
			ShortDescription: `IAM Roles`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"roles",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_states",
			Category:         "IAM",
			ShortDescription: `IAM States`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"states",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_supported_langs",
			Category:         "IAM",
			ShortDescription: `IAM Supported Languages`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"supported",
				"langs",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_timeout_policies",
			Category:         "IAM",
			ShortDescription: `IAM Timeout Policies`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"timeout",
				"policies",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_timezones",
			Category:         "IAM",
			ShortDescription: `IAM Timeout Policies`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"timezones",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_networklist_network_lists",
			Category:         "Network Lists",
			ShortDescription: `NetworkLists`,
			Description:      ``,
			Keywords: []string{
				"network",
				"lists",
				"networklist",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Optional) The name of a specific network list to retrieve. If not supplied, information about all network lists will be returned.`,
				},
				resource.Attribute{
					Name:        "type",
					Description: `(Optional) The type of network lists to be retrieved; must be either "IP" or "GEO". If not supplied, information about both types will be returned.`,
				},
				resource.Attribute{
					Name:        "network_list_id",
					Description: `(Optional) The ID of a specific network list to retrieve. If not supplied, information about all network`,
				},
				resource.Attribute{
					Name:        "network_list_id",
					Description: `(Optional) The ID of a specific network list to retrieve. If not supplied, information about all network lists will be returned. The following arguments are supported: ## Attributes Reference In addition to the arguments above, the following attributes are exported:`,
				},
				resource.Attribute{
					Name:        "json",
					Description: `A JSON-formatted list of information about the specified network list(s).`,
				},
				resource.Attribute{
					Name:        "output_text",
					Description: `A tabular display showing the network list information.`,
				},
				resource.Attribute{
					Name:        "list",
					Description: `A list containing the IDs of the specified network lists(s).`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "json",
					Description: `A JSON-formatted list of information about the specified network list(s).`,
				},
				resource.Attribute{
					Name:        "output_text",
					Description: `A tabular display showing the network list information.`,
				},
				resource.Attribute{
					Name:        "list",
					Description: `A list containing the IDs of the specified network lists(s).`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_properties",
			Category:         "Property Provisioning",
			ShortDescription: `Properties`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"properties",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_properties_search",
			Category:         "Property Provisioning",
			ShortDescription: `Search`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"properties",
				"search",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property",
			Category:         "Property Provisioning",
			ShortDescription: `Property`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property_hostnames",
			Category:         "Property Provisioning",
			ShortDescription: `Property hostnames`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"hostnames",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property_products",
			Category:         "Property Provisioning",
			ShortDescription: `Property products`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"products",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property_rule_formats",
			Category:         "Property Provisioning",
			ShortDescription: `Properties rule formats`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"rule",
				"formats",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property_rules",
			Category:         "Property Provisioning",
			ShortDescription: `Property rule tree`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"rules",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property_rules_template",
			Category:         "Property Provisioning",
			ShortDescription: `Property Rules Template`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"rules",
				"template",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"akamai_appsec_advanced_settings_evasive_path_match":    0,
		"akamai_appsec_advanced_settings_logging":               1,
		"akamai_appsec_advanced_settings_pragma_header":         2,
		"akamai_appsec_advanced_settings_prefetch":              3,
		"akamai_appsec_api_endpoints":                           4,
		"akamai_appsec_api_request_constraints":                 5,
		"akamai_appsec_attack_groups":                           6,
		"akamai_appsec_bypass_network_lists":                    7,
		"akamai_appsec_configuration":                           8,
		"akamai_appsec_configuration_version":                   9,
		"akamai_appsec_contracts_groups":                        10,
		"akamai_appsec_custom_deny":                             11,
		"akamai_appsec_custom_rule_actions":                     12,
		"akamai_appsec_custom_rules":                            13,
		"akamai_appsec_eval_groups":                             14,
		"akamai_appsec_eval_rules":                              15,
		"akamai_appsec_export_configuration":                    16,
		"akamai_appsec_failover_hostnames":                      17,
		"akamai_appsec_hostname_coverage":                       18,
		"akamai_appsec_hostname_coverage_match_targets":         19,
		"akamai_appsec_hostname_coverage_overlapping":           20,
		"akamai_appsec_ip_geo":                                  21,
		"akamai_appsec_match_targets":                           22,
		"akamai_appsec_penalty_box":                             23,
		"akamai_appsec_rate_policies":                           24,
		"akamai_appsec_rate_policy_actions":                     25,
		"akamai_appsec_reputation_profile_actions":              26,
		"akamai_appsec_reputation_profile_analysis":             27,
		"akamai_appsec_reputation_profiles":                     28,
		"akamai_appsec_rule_upgrade_details":                    29,
		"akamai_appsec_rules":                                   30,
		"akamai_appsec_security_policy":                         31,
		"akamai_appsec_security_policy_protections":             32,
		"akamai_appsec_selectable_hostnames":                    33,
		"akamai_appsec_selected_hostnames":                      34,
		"akamai_appsec_siem_definitions":                        35,
		"akamai_appsec_siem_settings":                           36,
		"akamai_appsec_slow_post":                               37,
		"akamai_appsec_threat_intel":                            38,
		"akamai_appsec_tuning_recommendations":                  39,
		"akamai_appsec_version_notes":                           40,
		"akamai_appsec_waf_mode":                                41,
		"akamai_appsec_wap_selected_hostnames":                  42,
		"akamai_authorities_set":                                43,
		"akamai_cloudlets_api_prioritization_match_rule":        44,
		"akamai_cloudlets_application_load_balancer":            45,
		"akamai_cloudlets_application_load_balancer_match_rule": 46,
		"akamai_cloudlets_audience_segmentation_match_rule":     47,
		"akamai_cloudlets_edge_redirector_match_rule":           48,
		"akamai_cloudlets_forward_rewrite_match_rule":           49,
		"akamai_cloudlets_phased_release_match_rule":            50,
		"akamai_cloudlets_policy":                               51,
		"akamai_cloudlets_request_control_match_rule":           52,
		"akamai_cloudlets_visitor_prioritization_match_rule":    53,
		"akamai_contract":                                       54,
		"akamai_contracts":                                      55,
		"akamai_cp_code":                                        56,
		"akamai_datastream_activation_history":                  57,
		"akamai_datastream_dataset_fields":                      58,
		"akamai_edgeworkers_property_rules":                     59,
		"akamai_edgeworkers_resource_tier":                      60,
		"akamai_group":                                          61,
		"akamai_groups":                                         62,
		"akamai_gtm_default_datacenter":                         63,
		"akamai_iam_contact_types":                              64,
		"akamai_iam_countries":                                  65,
		"akamai_iam_groups":                                     66,
		"akamai_iam_roles":                                      67,
		"akamai_iam_states":                                     68,
		"akamai_iam_supported_langs":                            69,
		"akamai_iam_timeout_policies":                           70,
		"akamai_iam_timezones":                                  71,
		"akamai_networklist_network_lists":                      72,
		"akamai_properties":                                     73,
		"akamai_properties_search":                              74,
		"akamai_property":                                       75,
		"akamai_property_hostnames":                             76,
		"akamai_property_products":                              77,
		"akamai_property_rule_formats":                          78,
		"akamai_property_rules":                                 79,
		"akamai_property_rules_template":                        80,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
