package akamai

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_activations",
			Category:         "Application Security",
			ShortDescription: `Activations`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"activations",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_evasive_path_match",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsEvasivePathMatch`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"evasive",
				"path",
				"match",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "config_id",
					Description: `(Required) The ID of the security configuration to use.`,
				},
				resource.Attribute{
					Name:        "security_policy_id",
					Description: `(Optional) The ID of a specific security policy to which the evasive path match setting should be applied. If not supplied, the indicated setting will be applied to all policies within the configuration.`,
				},
				resource.Attribute{
					Name:        "enable_path_match",
					Description: `(Required) Whether to enable path match. ## Attributes Reference In addition to the arguments above, the following attributes are exported:`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_logging",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsLogging`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"logging",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_pragma",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsPragmaHeader`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"pragma",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_advanced_settings_prefetch",
			Category:         "Application Security",
			ShortDescription: `AdvancedSettingsPrefetch`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"advanced",
				"settings",
				"prefetch",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_api_constraints_protection",
			Category:         "Application Security",
			ShortDescription: `API Constraints Protection`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"api",
				"constraints",
				"protection",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_api_request_constraints",
			Category:         "Application Security",
			ShortDescription: `ApiRequestConstraints`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"api",
				"request",
				"constraints",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_attack_group",
			Category:         "Application Security",
			ShortDescription: `Attack Group`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"attack",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_bypass_network_lists",
			Category:         "Application Security",
			ShortDescription: `BypassNetworkLists`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"bypass",
				"network",
				"lists",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_configuration",
			Category:         "Application Security",
			ShortDescription: `Configuration`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"configuration",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_configuration_rename",
			Category:         "Application Security",
			ShortDescription: `ConfigurationRename`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"configuration",
				"rename",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_custom_deny",
			Category:         "Application Security",
			ShortDescription: `CustomDeny`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"custom",
				"deny",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_custom_rule",
			Category:         "Application Security",
			ShortDescription: `Custom Rule`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"custom",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_custom_rule_action",
			Category:         "Application Security",
			ShortDescription: `Custom Rule Action`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"custom",
				"rule",
				"action",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_eval",
			Category:         "Application Security",
			ShortDescription: `Evaluation`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"eval",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_eval_group",
			Category:         "Application Security",
			ShortDescription: `Eval Group`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"eval",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_eval_rule",
			Category:         "Application Security",
			ShortDescription: `Eval Rule`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"eval",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_ip_geo",
			Category:         "Application Security",
			ShortDescription: `IP/Geo Firewall`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"ip",
				"geo",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_ip_geo_protection",
			Category:         "Application Security",
			ShortDescription: `IP GEO Protection`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"ip",
				"geo",
				"protection",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_match_target",
			Category:         "Application Security",
			ShortDescription: `MatchTarget`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"match",
				"target",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_match_target_sequence",
			Category:         "Application Security",
			ShortDescription: `MatchTargetSequence`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"match",
				"target",
				"sequence",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_penalty_box",
			Category:         "Application Security",
			ShortDescription: `Penalty Box`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"penalty",
				"box",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rate_policy",
			Category:         "Application Security",
			ShortDescription: `Rate Policy`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rate",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rate_policy_action",
			Category:         "Application Security",
			ShortDescription: `Rate Policy Action`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rate",
				"policy",
				"action",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rate_protection",
			Category:         "Application Security",
			ShortDescription: `Rate Protection`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rate",
				"protection",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_reputation_profile",
			Category:         "Application Security",
			ShortDescription: `Reputation Profile`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"reputation",
				"profile",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_reputation_profile_action",
			Category:         "Application Security",
			ShortDescription: `Reputation Profile Action`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"reputation",
				"profile",
				"action",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_reputation_profile_analysis",
			Category:         "Application Security",
			ShortDescription: `Reputation Profile Analysis`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"reputation",
				"profile",
				"analysis",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_reputation_protection",
			Category:         "Application Security",
			ShortDescription: `Reputation Protection`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"reputation",
				"protection",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rule",
			Category:         "Application Security",
			ShortDescription: `Rule`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_rule_upgrade",
			Category:         "Application Security",
			ShortDescription: `Rule Upgrade`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"rule",
				"upgrade",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_security_policy",
			Category:         "Application Security",
			ShortDescription: `SecurityPolicy`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_security_policy_rename",
			Category:         "Application Security",
			ShortDescription: `SecurityPolicyRename`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"policy",
				"rename",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_selected_hostnames",
			Category:         "Application Security",
			ShortDescription: `SelectedHostnames`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"selected",
				"hostnames",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_siem_settings",
			Category:         "Application Security",
			ShortDescription: `SIEMSettings`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"siem",
				"settings",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_slow_post",
			Category:         "Application Security",
			ShortDescription: `Slow Post`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"slow",
				"post",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_slowpost_protection",
			Category:         "Application Security",
			ShortDescription: `Slowpost Protection`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"slowpost",
				"protection",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_threat_intel",
			Category:         "Application Security",
			ShortDescription: `Threat Intelligence`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"threat",
				"intel",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_version_notes",
			Category:         "Application Security",
			ShortDescription: `VersionNotes`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"version",
				"notes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_waf_mode",
			Category:         "Application Security",
			ShortDescription: `WAF Mode`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"waf",
				"mode",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_waf_protection",
			Category:         "Application Security",
			ShortDescription: `WAF Protection`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"waf",
				"protection",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_appsec_wap_selected_hostnames",
			Category:         "Application Security",
			ShortDescription: `WAPSelectedHostnames`,
			Description:      ``,
			Keywords: []string{
				"application",
				"security",
				"appsec",
				"wap",
				"selected",
				"hostnames",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_application_load_balancer",
			Category:         "Cloudlets",
			ShortDescription: `Application Load Balancer`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"application",
				"load",
				"balancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_application_load_balancer_activation",
			Category:         "Cloudlets",
			ShortDescription: `Application Load Balancer activation`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"application",
				"load",
				"balancer",
				"activation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_policy",
			Category:         "Cloudlets",
			ShortDescription: `Cloudlets Policy`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cloudlets_policy_activation",
			Category:         "Cloudlets",
			ShortDescription: `Cloudlets Policy activation`,
			Description:      ``,
			Keywords: []string{
				"cloudlets",
				"policy",
				"activation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cp_code",
			Category:         "Property Provisioning",
			ShortDescription: `CP Code`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"cp",
				"code",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cps_dv_enrollment",
			Category:         "CPS",
			ShortDescription: `DV Enrollment`,
			Description:      ``,
			Keywords: []string{
				"cps",
				"dv",
				"enrollment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_cps_dv_validation",
			Category:         "CPS",
			ShortDescription: `Domain Validation`,
			Description:      ``,
			Keywords: []string{
				"cps",
				"dv",
				"validation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_datastream",
			Category:         "DataStream",
			ShortDescription: `DataStream`,
			Description:      ``,
			Keywords: []string{
				"datastream",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_dns_record",
			Category:         "DNS",
			ShortDescription: `DNS record`,
			Description:      ``,
			Keywords: []string{
				"dns",
				"record",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_dns_zone",
			Category:         "DNS",
			ShortDescription: `DNS Zone`,
			Description:      ``,
			Keywords: []string{
				"dns",
				"zone",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_edge_hostname",
			Category:         "Property Provisioning",
			ShortDescription: `Edge Hostname`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"edge",
				"hostname",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_edgekv",
			Category:         "EdgeWorkers",
			ShortDescription: `EdgeKV`,
			Description:      ``,
			Keywords: []string{
				"edgeworkers",
				"edgekv",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_edgeworker",
			Category:         "EdgeWorkers",
			ShortDescription: `EdgeWorkers`,
			Description:      ``,
			Keywords: []string{
				"edgeworkers",
				"edgeworker",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_edgeworkers_activation",
			Category:         "EdgeWorkers",
			ShortDescription: `EdgeWorkers activation`,
			Description:      ``,
			Keywords: []string{
				"edgeworkers",
				"activation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_asmap",
			Category:         "Global Traffic Management",
			ShortDescription: `GTM AS Map`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"asmap",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_cidrmap",
			Category:         "Global Traffic Management",
			ShortDescription: `GTM Cidr Map`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"cidrmap",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_datacenter",
			Category:         "Global Traffic Management",
			ShortDescription: `GTM Datacenter`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"datacenter",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_domain",
			Category:         "Global Traffic Management",
			ShortDescription: `GTM Domain`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_geomap",
			Category:         "Global Traffic Management",
			ShortDescription: `GTM Geographic Map`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"geomap",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_property",
			Category:         "Global Traffic Management",
			ShortDescription: `GTM Property`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"property",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_gtm_resource",
			Category:         "Global Traffic Management",
			ShortDescription: `GTM Resource`,
			Description:      ``,
			Keywords: []string{
				"global",
				"traffic",
				"management",
				"gtm",
				"resource",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_iam_user",
			Category:         "IAM",
			ShortDescription: `Create user resources.`,
			Description:      ``,
			Keywords: []string{
				"iam",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_imaging_policy_image",
			Category:         "Image and Video Manager",
			ShortDescription: `Image and Video Manager image policy`,
			Description:      ``,
			Keywords: []string{
				"image",
				"and",
				"video",
				"manager",
				"imaging",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_imaging_policy_set",
			Category:         "Image and Video Manager",
			ShortDescription: `Image and Video Manager policy set`,
			Description:      ``,
			Keywords: []string{
				"image",
				"and",
				"video",
				"manager",
				"imaging",
				"policy",
				"set",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_imaging_policy_video",
			Category:         "Image and Video Manager",
			ShortDescription: `Image and Video Manager video policy`,
			Description:      ``,
			Keywords: []string{
				"image",
				"and",
				"video",
				"manager",
				"imaging",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_networklist_activations",
			Category:         "Network Lists",
			ShortDescription: `NetworkList Activations`,
			Description:      ``,
			Keywords: []string{
				"network",
				"lists",
				"networklist",
				"activations",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "network_list_id",
					Description: `(Required) The ID of the network list to be activated`,
				},
				resource.Attribute{
					Name:        "network",
					Description: `(Optional) The network to be used, either ` + "`" + `STAGING` + "`" + ` or ` + "`" + `PRODUCTION` + "`" + `. If not supplied, defaults to ` + "`" + `STAGING` + "`" + `.`,
				},
				resource.Attribute{
					Name:        "notes",
					Description: `(Optional) A comment describing the activation.`,
				},
				resource.Attribute{
					Name:        "notification_emails",
					Description: `(Required) A bracketed, comma-separated list of email addresses that will be notified when the operation is complete. ## Attributes Reference In addition to the arguments above, the following attribute is exported:`,
				},
				resource.Attribute{
					Name:        "status",
					Description: `The string ` + "`" + `ACTIVATED` + "`" + ` if the activation was successful, or a string identifying the reason why the network list was not activated.`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "status",
					Description: `The string ` + "`" + `ACTIVATED` + "`" + ` if the activation was successful, or a string identifying the reason why the network list was not activated.`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_networklist_description",
			Category:         "Network Lists",
			ShortDescription: `NetworkList Description`,
			Description:      ``,
			Keywords: []string{
				"network",
				"lists",
				"networklist",
				"description",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "network_list_id",
					Description: `(Required) The unique ID of the network list to use.`,
				},
				resource.Attribute{
					Name:        "name",
					Description: `(Required) The name to be assigned to the network list.`,
				},
				resource.Attribute{
					Name:        "description",
					Description: `(Required) The description to be assigned to the network list. ## Attributes Reference In addition to the arguments above, the following attributes are exported:`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_networklist_network_list",
			Category:         "Network Lists",
			ShortDescription: `NetworkList Network List`,
			Description:      ``,
			Keywords: []string{
				"network",
				"lists",
				"networklist",
				"list",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Required) The name to be assigned to the network list.`,
				},
				resource.Attribute{
					Name:        "type",
					Description: `(Required) The type of the network list; must be either "IP" or "GEO".`,
				},
				resource.Attribute{
					Name:        "description",
					Description: `(Required) The description to be assigned to the network list.`,
				},
				resource.Attribute{
					Name:        "mode",
					Description: `(Required) A string specifying the interpretation of the ` + "`" + `list` + "`" + ` parameter. Must be one of the following:`,
				},
				resource.Attribute{
					Name:        "contract_id",
					Description: `(Optional) The contract ID of the network list. If supplied, group_id must also be supplied. The contract_id value of an existing network list may not be modified.`,
				},
				resource.Attribute{
					Name:        "group_id",
					Description: `(Optional) The group ID of the network list. If supplied, contract_id must also be supplied. The group_id value of an existing network list may not be modified. ## Attributes Reference In addition to the arguments above, the following attributes are exported:`,
				},
				resource.Attribute{
					Name:        "network_list_id",
					Description: `The ID of the network list.`,
				},
				resource.Attribute{
					Name:        "sync_point",
					Description: `An integer that identifies the current version of the network list; this value is incremented each time the list is modified.`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "network_list_id",
					Description: `The ID of the network list.`,
				},
				resource.Attribute{
					Name:        "sync_point",
					Description: `An integer that identifies the current version of the network list; this value is incremented each time the list is modified.`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_networklist_subscription",
			Category:         "Network Lists",
			ShortDescription: `NetworkList Subscription`,
			Description:      ``,
			Keywords: []string{
				"network",
				"lists",
				"networklist",
				"subscription",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "network_list",
					Description: `(Required) A list containing one or more IDs of the network lists to which the indicated email addresses should be subscribed.`,
				},
				resource.Attribute{
					Name:        "recipients",
					Description: `(Required) A bracketed, comma-separated list of email addresses that will be notified of changes to any of the specified network lists. ## Attributes Reference In addition to the arguments above, the following attributes are exported:`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property",
			Category:         "Property Provisioning",
			ShortDescription: `Create and update Akamai properties.`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "akamai_property_activation",
			Category:         "Property Provisioning",
			ShortDescription: `Property Activation`,
			Description:      ``,
			Keywords: []string{
				"property",
				"provisioning",
				"activation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"akamai_appsec_activations":                             0,
		"akamai_appsec_advanced_settings_evasive_path_match":    1,
		"akamai_appsec_advanced_settings_logging":               2,
		"akamai_appsec_advanced_settings_pragma":                3,
		"akamai_appsec_advanced_settings_prefetch":              4,
		"akamai_appsec_api_constraints_protection":              5,
		"akamai_appsec_api_request_constraints":                 6,
		"akamai_appsec_attack_group":                            7,
		"akamai_appsec_bypass_network_lists":                    8,
		"akamai_appsec_configuration":                           9,
		"akamai_appsec_configuration_rename":                    10,
		"akamai_appsec_custom_deny":                             11,
		"akamai_appsec_custom_rule":                             12,
		"akamai_appsec_custom_rule_action":                      13,
		"akamai_appsec_eval":                                    14,
		"akamai_appsec_eval_group":                              15,
		"akamai_appsec_eval_rule":                               16,
		"akamai_appsec_ip_geo":                                  17,
		"akamai_appsec_ip_geo_protection":                       18,
		"akamai_appsec_match_target":                            19,
		"akamai_appsec_match_target_sequence":                   20,
		"akamai_appsec_penalty_box":                             21,
		"akamai_appsec_rate_policy":                             22,
		"akamai_appsec_rate_policy_action":                      23,
		"akamai_appsec_rate_protection":                         24,
		"akamai_appsec_reputation_profile":                      25,
		"akamai_appsec_reputation_profile_action":               26,
		"akamai_appsec_reputation_profile_analysis":             27,
		"akamai_appsec_reputation_protection":                   28,
		"akamai_appsec_rule":                                    29,
		"akamai_appsec_rule_upgrade":                            30,
		"akamai_appsec_security_policy":                         31,
		"akamai_appsec_security_policy_rename":                  32,
		"akamai_appsec_selected_hostnames":                      33,
		"akamai_appsec_siem_settings":                           34,
		"akamai_appsec_slow_post":                               35,
		"akamai_appsec_slowpost_protection":                     36,
		"akamai_appsec_threat_intel":                            37,
		"akamai_appsec_version_notes":                           38,
		"akamai_appsec_waf_mode":                                39,
		"akamai_appsec_waf_protection":                          40,
		"akamai_appsec_wap_selected_hostnames":                  41,
		"akamai_cloudlets_application_load_balancer":            42,
		"akamai_cloudlets_application_load_balancer_activation": 43,
		"akamai_cloudlets_policy":                               44,
		"akamai_cloudlets_policy_activation":                    45,
		"akamai_cp_code":                                        46,
		"akamai_cps_dv_enrollment":                              47,
		"akamai_cps_dv_validation":                              48,
		"akamai_datastream":                                     49,
		"akamai_dns_record":                                     50,
		"akamai_dns_zone":                                       51,
		"akamai_edge_hostname":                                  52,
		"akamai_edgekv":                                         53,
		"akamai_edgeworker":                                     54,
		"akamai_edgeworkers_activation":                         55,
		"akamai_gtm_asmap":                                      56,
		"akamai_gtm_cidrmap":                                    57,
		"akamai_gtm_datacenter":                                 58,
		"akamai_gtm_domain":                                     59,
		"akamai_gtm_geomap":                                     60,
		"akamai_gtm_property":                                   61,
		"akamai_gtm_resource":                                   62,
		"akamai_iam_user":                                       63,
		"akamai_imaging_policy_image":                           64,
		"akamai_imaging_policy_set":                             65,
		"akamai_imaging_policy_video":                           66,
		"akamai_networklist_activations":                        67,
		"akamai_networklist_description":                        68,
		"akamai_networklist_network_list":                       69,
		"akamai_networklist_subscription":                       70,
		"akamai_property":                                       71,
		"akamai_property_activation":                            72,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
