package spectrocloud

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_addon_deployment",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_alert",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_appliance",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_application",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_application_profile",
			Category:         "Resources",
			ShortDescription: `Provisions an Application Profile. App Profiles are templates created with preconfigured services. You can create as many profiles as required, with multiple tiers serving different functionalities per use case.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_backup_storage_location",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cloudaccount_aws",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cloudaccount_azure",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cloudaccount_gcp",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cloudaccount_maas",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cloudaccount_openstack",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cloudaccount_tencent",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cloudaccount_vsphere",
			Category:         "Resources",
			ShortDescription: `A resource to manage a vSphere cloud account in Pallette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_aks",
			Category:         "Resources",
			ShortDescription: `Resource for managing AKS clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_aws",
			Category:         "Resources",
			ShortDescription: `Resource for managing AWS clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_azure",
			Category:         "Resources",
			ShortDescription: `Resource for managing Azure clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_edge_native",
			Category:         "Resources",
			ShortDescription: `Resource for managing Edge Native clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_edge_vsphere",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_eks",
			Category:         "Resources",
			ShortDescription: `Resource for managing EKS clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_gcp",
			Category:         "Resources",
			ShortDescription: `Resource for managing GCP clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_group",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_import",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_libvirt",
			Category:         "Resources",
			ShortDescription: `Resource for managing Libvirt clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_maas",
			Category:         "Resources",
			ShortDescription: `Resource for managing MAAS clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_openstack",
			Category:         "Resources",
			ShortDescription: `Resource for managing Openstack clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_profile",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_profile_import",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_tke",
			Category:         "Resources",
			ShortDescription: `Resource for managing TKE clusters in Spectro Cloud through Palette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_cluster_vsphere",
			Category:         "Resources",
			ShortDescription: `A resource to manage a vSphere cluster in Pallette.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_datavolume",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_macro",
			Category:         "Resources",
			ShortDescription: `A resource for creating and managing service output variables and macros.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_privatecloudgateway_ippool",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_project",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_registry_helm",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_registry_oci",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_team",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_virtual_cluster",
			Category:         "Resources",
			ShortDescription: `A resource to manage a Palette Virtual Cluster.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_virtual_machine",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "spectrocloud_workspace",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"spectrocloud_addon_deployment":           0,
		"spectrocloud_alert":                      1,
		"spectrocloud_appliance":                  2,
		"spectrocloud_application":                3,
		"spectrocloud_application_profile":        4,
		"spectrocloud_backup_storage_location":    5,
		"spectrocloud_cloudaccount_aws":           6,
		"spectrocloud_cloudaccount_azure":         7,
		"spectrocloud_cloudaccount_gcp":           8,
		"spectrocloud_cloudaccount_maas":          9,
		"spectrocloud_cloudaccount_openstack":     10,
		"spectrocloud_cloudaccount_tencent":       11,
		"spectrocloud_cloudaccount_vsphere":       12,
		"spectrocloud_cluster_aks":                13,
		"spectrocloud_cluster_aws":                14,
		"spectrocloud_cluster_azure":              15,
		"spectrocloud_cluster_edge_native":        16,
		"spectrocloud_cluster_edge_vsphere":       17,
		"spectrocloud_cluster_eks":                18,
		"spectrocloud_cluster_gcp":                19,
		"spectrocloud_cluster_group":              20,
		"spectrocloud_cluster_import":             21,
		"spectrocloud_cluster_libvirt":            22,
		"spectrocloud_cluster_maas":               23,
		"spectrocloud_cluster_openstack":          24,
		"spectrocloud_cluster_profile":            25,
		"spectrocloud_cluster_profile_import":     26,
		"spectrocloud_cluster_tke":                27,
		"spectrocloud_cluster_vsphere":            28,
		"spectrocloud_datavolume":                 29,
		"spectrocloud_macro":                      30,
		"spectrocloud_privatecloudgateway_ippool": 31,
		"spectrocloud_project":                    32,
		"spectrocloud_registry_helm":              33,
		"spectrocloud_registry_oci":               34,
		"spectrocloud_team":                       35,
		"spectrocloud_virtual_cluster":            36,
		"spectrocloud_virtual_machine":            37,
		"spectrocloud_workspace":                  38,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
