package gitlab

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "gitlab_branch",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_membership",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_variable",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_group_variable data source allows to retrieve details about a group-level CI/CD variable. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/group_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_variables",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_group_variables data source allows to retrieve all group-level CI/CD variables. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/group_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_instance_deploy_keys",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_instance_variable",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_instance_variable data source allows to retrieve details about an instance-level CI/CD variable. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/instance_level_ci_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_instance_variables",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_instance_variables data source allows to retrieve all instance-level CI/CD variables. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/instance_level_ci_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_issue",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_issue data source allows to retrieve details about an issue in a project. Upstream API: GitLab API docs https://docs.gitlab.com/ee/api/issues.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_issues",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_issues data source allows to retrieve details about issues in a project. Upstream API: GitLab API docs https://docs.gitlab.com/ee/api/issues.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_protected_branch",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_protected_branches",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_tag",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_tag data source allows details of a project tag to be retrieved by its name. Upstream API: GitLab API docs https://docs.gitlab.com/ee/api/tags.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_tags",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_variable",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_variable data source allows to retrieve details about a project-level CI/CD variable. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/project_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_variables",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_variables data source allows to retrieve all project-level CI/CD variables. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/project_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_projects",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_repository_file",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_repository_file data source allows details of a file in a repository to be retrieved. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/repository_files.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_user",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_users",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"gitlab_branch":                     0,
		"gitlab_group":                      1,
		"gitlab_group_membership":           2,
		"gitlab_group_variable":             3,
		"gitlab_group_variables":            4,
		"gitlab_instance_deploy_keys":       5,
		"gitlab_instance_variable":          6,
		"gitlab_instance_variables":         7,
		"gitlab_project":                    8,
		"gitlab_project_issue":              9,
		"gitlab_project_issues":             10,
		"gitlab_project_protected_branch":   11,
		"gitlab_project_protected_branches": 12,
		"gitlab_project_tag":                13,
		"gitlab_project_tags":               14,
		"gitlab_project_variable":           15,
		"gitlab_project_variables":          16,
		"gitlab_projects":                   17,
		"gitlab_repository_file":            18,
		"gitlab_user":                       19,
		"gitlab_users":                      20,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
