package gitlab

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "gitlab_application",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_application data source retrieves information about a gitlab application. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/applications.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_branch",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_cluster_agent",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_cluster_agent data source allows to retrieve details about a GitLab Agent for Kubernetes. -> Requires at least GitLab 14.10 Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/cluster_agents.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_cluster_agents",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_cluster_agents data source allows details of GitLab Agents for Kubernetes in a project. -> Requires at least GitLab 14.10 Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/cluster_agents.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_current_user",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_hook",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_hooks",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_membership",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_subgroups",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_variable",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_group_variable data source allows to retrieve details about a group-level CI/CD variable. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/group_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_group_variables",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_group_variables data source allows to retrieve all group-level CI/CD variables. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/group_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_groups",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_instance_deploy_keys",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_instance_variable",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_instance_variable data source allows to retrieve details about an instance-level CI/CD variable. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/instance_level_ci_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_instance_variables",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_instance_variables data source allows to retrieve all instance-level CI/CD variables. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/instance_level_ci_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_metadata",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_metadata data source retrieves the metadata of the GitLab instance. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/metadata.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_branches",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_hook",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_hooks",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_issue",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_issue data source allows to retrieve details about an issue in a project. Upstream API: GitLab API docs https://docs.gitlab.com/ee/api/issues.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_issues",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_issues data source allows to retrieve details about issues in a project. Upstream API: GitLab API docs https://docs.gitlab.com/ee/api/issues.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_membership",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_milestone",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_milestone data source allows get details of a project milestone. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/milestones.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_milestones",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_milestones data source allows get details of a project milestones. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/milestones.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_protected_branch",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_protected_branches",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_tag",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_tag data source allows details of a project tag to be retrieved by its name. Upstream API: GitLab API docs https://docs.gitlab.com/ee/api/tags.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_tags",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_variable",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_variable data source allows to retrieve details about a project-level CI/CD variable. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/project_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_project_variables",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_project_variables data source allows to retrieve all project-level CI/CD variables. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/project_level_variables.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_projects",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_release_link",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_release_link data source allows get details of a release link. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/releases/links.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_release_links",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_release_links data source allows get details of release links. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/releases/links.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_repository_file",
			Category:         "Data Sources",
			ShortDescription: `The gitlab_repository_file data source allows details of a file in a repository to be retrieved. Upstream API: GitLab REST API docs https://docs.gitlab.com/ee/api/repository_files.html`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_repository_tree",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_user",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_user_sshkeys",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "gitlab_users",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"gitlab_application":                0,
		"gitlab_branch":                     1,
		"gitlab_cluster_agent":              2,
		"gitlab_cluster_agents":             3,
		"gitlab_current_user":               4,
		"gitlab_group":                      5,
		"gitlab_group_hook":                 6,
		"gitlab_group_hooks":                7,
		"gitlab_group_membership":           8,
		"gitlab_group_subgroups":            9,
		"gitlab_group_variable":             10,
		"gitlab_group_variables":            11,
		"gitlab_groups":                     12,
		"gitlab_instance_deploy_keys":       13,
		"gitlab_instance_variable":          14,
		"gitlab_instance_variables":         15,
		"gitlab_metadata":                   16,
		"gitlab_project":                    17,
		"gitlab_project_branches":           18,
		"gitlab_project_hook":               19,
		"gitlab_project_hooks":              20,
		"gitlab_project_issue":              21,
		"gitlab_project_issues":             22,
		"gitlab_project_membership":         23,
		"gitlab_project_milestone":          24,
		"gitlab_project_milestones":         25,
		"gitlab_project_protected_branch":   26,
		"gitlab_project_protected_branches": 27,
		"gitlab_project_tag":                28,
		"gitlab_project_tags":               29,
		"gitlab_project_variable":           30,
		"gitlab_project_variables":          31,
		"gitlab_projects":                   32,
		"gitlab_release_link":               33,
		"gitlab_release_links":              34,
		"gitlab_repository_file":            35,
		"gitlab_repository_tree":            36,
		"gitlab_user":                       37,
		"gitlab_user_sshkeys":               38,
		"gitlab_users":                      39,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
