package scaleway

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "scaleway_account_ssh_key",
			Category:         "Data Sources",
			ShortDescription: `Get information on a Scaleway SSH key.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_offer",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a baremetal offer.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_os",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a baremetal operating system.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_server",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a baremetal server.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a container.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container_namespace",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a container namespace.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_record",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a domain record.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_zone",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a domain zone.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function_namespace",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a function namespace.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_image",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an Instance Image.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an instance IP.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a Security Group.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_server",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an Instance Server.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_volume",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an instance volume.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_device",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an IOT Device.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_hub",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an IOT Hub.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_cluster",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a Kubernetes Cluster.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_pool",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a Kubernetes Cluster's Pool.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a Load Balancer.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_certificate",
			Category:         "Data Sources",
			ShortDescription: `Manages Scaleway Load-Balancer Certificates.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_ip",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a Load Balancer IP.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_marketplace_image",
			Category:         "Data Sources",
			ShortDescription: `Gets local image ID of an image from its label name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket",
			Category:         "Data Sources",
			ShortDescription: `Gets information about Scaleway object storage buckets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The unique name of the bucket.`,
				},
				resource.Attribute{
					Name:        "endpoint",
					Description: `The endpoint URL of the bucket`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The unique name of the bucket.`,
				},
				resource.Attribute{
					Name:        "endpoint",
					Description: `The endpoint URL of the bucket`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_acl",
			Category:         "Data Sources",
			ShortDescription: `Gets information about the RDB instance network Access Control List.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_database",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an RDB database.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_instance",
			Category:         "Data Sources",
			ShortDescription: `Gets information about an RDB instance.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_privilege",
			Category:         "Data Sources",
			ShortDescription: `Gets information about the privilege on a RDB database.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_redis_cluster",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a Redis cluster.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_registry_image",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a registry image.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_registry_namespace",
			Category:         "Data Sources",
			ShortDescription: `Gets information about a registry namespace.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_private_network",
			Category:         "Data Sources",
			ShortDescription: `Get information about Scaleway VPC Private Networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Required) Exact name of the private network. ## Attributes Reference ` + "`" + `id` + "`" + ` is set to the ID of the found private network. Addition attributes are exported.`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway",
			Category:         "Data Sources",
			ShortDescription: `Get information about Scaleway VPC Public Gateways.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Required) Exact name of the public gateway. ## Attributes Reference ` + "`" + `id` + "`" + ` is set to the ID of the found public gateway. Addition attributes are exported.`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_dhcp",
			Category:         "Data Sources",
			ShortDescription: `Get information about Scaleway VPC Public Gateway DHCP.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_ip",
			Category:         "Data Sources",
			ShortDescription: `Get information about Scaleway VPC Public Gateway IPs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_pat_rule",
			Category:         "Data Sources",
			ShortDescription: `Get information about Scaleway VPC Public Gateway PAT rule.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"scaleway_account_ssh_key":             0,
		"scaleway_baremetal_offer":             1,
		"scaleway_baremetal_os":                2,
		"scaleway_baremetal_server":            3,
		"scaleway_container":                   4,
		"scaleway_container_namespace":         5,
		"scaleway_domain_record":               6,
		"scaleway_domain_zone":                 7,
		"scaleway_function_namespace":          8,
		"scaleway_instance_image":              9,
		"scaleway_instance_ip":                 10,
		"scaleway_instance_security_group":     11,
		"scaleway_instance_server":             12,
		"scaleway_instance_volume":             13,
		"scaleway_iot_device":                  14,
		"scaleway_iot_hub":                     15,
		"scaleway_k8s_cluster":                 16,
		"scaleway_k8s_pool":                    17,
		"scaleway_lb":                          18,
		"scaleway_lb_certificate":              19,
		"scaleway_lb_ip":                       20,
		"scaleway_marketplace_image":           21,
		"scaleway_object_bucket":               22,
		"scaleway_rdb_acl":                     23,
		"scaleway_rdb_database":                24,
		"scaleway_rdb_instance":                25,
		"scaleway_rdb_privilege":               26,
		"scaleway_redis_cluster":               27,
		"scaleway_registry_image":              28,
		"scaleway_registry_namespace":          29,
		"scaleway_vpc_private_network":         30,
		"scaleway_vpc_public_gateway":          31,
		"scaleway_vpc_public_gateway_dhcp":     32,
		"scaleway_vpc_public_gateway_ip":       33,
		"scaleway_vpc_public_gateway_pat_rule": 34,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
