package scaleway

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "scaleway_account_project",
			Category:         "Account",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"account",
				"project",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_account_ssh_key",
			Category:         "Account",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"account",
				"ssh",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_availability_zones",
			Category:         "Account",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"account",
				"availability",
				"zones",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_offer",
			Category:         "Elastic Metal",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"elastic",
				"metal",
				"baremetal",
				"offer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_option",
			Category:         "Elastic Metal",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"elastic",
				"metal",
				"baremetal",
				"option",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_os",
			Category:         "Elastic Metal",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"elastic",
				"metal",
				"baremetal",
				"os",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_server",
			Category:         "Elastic Metal",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"elastic",
				"metal",
				"baremetal",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_cockpit",
			Category:         "Cockpit",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cockpit",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container",
			Category:         "Containers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"containers",
				"container",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container_namespace",
			Category:         "Containers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"containers",
				"container",
				"namespace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_record",
			Category:         "Domains and DNS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"domains",
				"and",
				"dns",
				"domain",
				"record",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_zone",
			Category:         "Domains and DNS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"domains",
				"and",
				"dns",
				"domain",
				"zone",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_flexible_ip",
			Category:         "Elastic Metal",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"elastic",
				"metal",
				"flexible",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function_namespace",
			Category:         "Functions",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"functions",
				"function",
				"namespace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_application",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"application",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_group",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_ssh_key",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"ssh",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_user",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_image",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"image",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_private_nic",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"private",
				"nic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"security",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_server",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_servers",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"servers",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_snapshot",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"snapshot",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_volume",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"volume",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_device",
			Category:         "IoT Hub",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iot",
				"hub",
				"device",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_hub",
			Category:         "IoT Hub",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iot",
				"hub",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_cluster",
			Category:         "Kubernetes",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"kubernetes",
				"k8s",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_pool",
			Category:         "Kubernetes",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"kubernetes",
				"k8s",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_version",
			Category:         "Kubernetes",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"kubernetes",
				"k8s",
				"version",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_acls",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"acls",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_backend",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"backend",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_backends",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"backends",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_certificate",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"certificate",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_frontend",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"frontend",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_frontends",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"frontends",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_ip",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_ips",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"ips",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_route",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"route",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_routes",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"routes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lbs",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lbs",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_marketplace_image",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"marketplace",
				"image",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
				"bucket",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The unique name of the bucket. ~>`,
				},
				resource.Attribute{
					Name:        "endpoint",
					Description: `The endpoint URL of the bucket`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The unique name of the bucket. ~>`,
				},
				resource.Attribute{
					Name:        "endpoint",
					Description: `The endpoint URL of the bucket`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket_policy",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
				"bucket",
				"policy",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "policy",
					Description: `The bucket's policy in JSON format.`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "policy",
					Description: `The bucket's policy in JSON format.`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_acl",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"acl",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_database",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"database",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_database_backup",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"database",
				"backup",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_instance",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"instance",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_privilege",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"privilege",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_redis_cluster",
			Category:         "Redis",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"redis",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_registry_image",
			Category:         "Container Registry",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"container",
				"registry",
				"image",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_registry_namespace",
			Category:         "Container Registry",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"container",
				"registry",
				"namespace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_secret",
			Category:         "Secrets",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"secrets",
				"secret",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_secret_version",
			Category:         "Secrets",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"secrets",
				"secret",
				"version",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_tem_domain",
			Category:         "Transactional Email",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"transactional",
				"email",
				"tem",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_gateway_network",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"gateway",
				"network",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "gateway_network_id",
					Description: `(Optional) ID of the gateway network. ~> Only one of ` + "`" + `gateway_network_id` + "`" + ` or filters should be specified. You can use all the filters you want.`,
				},
				resource.Attribute{
					Name:        "gateway_id",
					Description: `(Optional) ID of the public gateway the gateway network is linked to`,
				},
				resource.Attribute{
					Name:        "private_network_id",
					Description: `(Optional) ID of the private network the gateway network is linked to`,
				},
				resource.Attribute{
					Name:        "enable_masquerade",
					Description: `(Optional) If masquerade is enabled on requested network`,
				},
				resource.Attribute{
					Name:        "dhcp_id",
					Description: `(Optional) ID of the public gateway DHCP config ## Attributes Reference Exported attributes are the attributes of the [resource](../resources/vpc_gateway_network.md)`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_private_network",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"private",
				"network",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Required) Exact name of the private network. ## Attributes Reference In addition to all above arguments, the following attributes are exported: - ` + "`" + `id` + "`" + ` - The ID of the private network. ~>`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_dhcp",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"dhcp",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_dhcp_reservation",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"dhcp",
				"reservation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_ip",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_pat_rule",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"pat",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_webhosting_offer",
			Category:         "Web Hosting",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"web",
				"hosting",
				"webhosting",
				"offer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"scaleway_account_project":                     0,
		"scaleway_account_ssh_key":                     1,
		"scaleway_availability_zones":                  2,
		"scaleway_baremetal_offer":                     3,
		"scaleway_baremetal_option":                    4,
		"scaleway_baremetal_os":                        5,
		"scaleway_baremetal_server":                    6,
		"scaleway_cockpit":                             7,
		"scaleway_container":                           8,
		"scaleway_container_namespace":                 9,
		"scaleway_domain_record":                       10,
		"scaleway_domain_zone":                         11,
		"scaleway_flexible_ip":                         12,
		"scaleway_function_namespace":                  13,
		"scaleway_iam_application":                     14,
		"scaleway_iam_group":                           15,
		"scaleway_iam_ssh_key":                         16,
		"scaleway_iam_user":                            17,
		"scaleway_instance_image":                      18,
		"scaleway_instance_ip":                         19,
		"scaleway_instance_private_nic":                20,
		"scaleway_instance_security_group":             21,
		"scaleway_instance_server":                     22,
		"scaleway_instance_servers":                    23,
		"scaleway_instance_snapshot":                   24,
		"scaleway_instance_volume":                     25,
		"scaleway_iot_device":                          26,
		"scaleway_iot_hub":                             27,
		"scaleway_k8s_cluster":                         28,
		"scaleway_k8s_pool":                            29,
		"scaleway_k8s_version":                         30,
		"scaleway_lb":                                  31,
		"scaleway_lb_acls":                             32,
		"scaleway_lb_backend":                          33,
		"scaleway_lb_backends":                         34,
		"scaleway_lb_certificate":                      35,
		"scaleway_lb_frontend":                         36,
		"scaleway_lb_frontends":                        37,
		"scaleway_lb_ip":                               38,
		"scaleway_lb_ips":                              39,
		"scaleway_lb_route":                            40,
		"scaleway_lb_routes":                           41,
		"scaleway_lbs":                                 42,
		"scaleway_marketplace_image":                   43,
		"scaleway_object_bucket":                       44,
		"scaleway_object_bucket_policy":                45,
		"scaleway_rdb_acl":                             46,
		"scaleway_rdb_database":                        47,
		"scaleway_rdb_database_backup":                 48,
		"scaleway_rdb_instance":                        49,
		"scaleway_rdb_privilege":                       50,
		"scaleway_redis_cluster":                       51,
		"scaleway_registry_image":                      52,
		"scaleway_registry_namespace":                  53,
		"scaleway_secret":                              54,
		"scaleway_secret_version":                      55,
		"scaleway_tem_domain":                          56,
		"scaleway_vpc_gateway_network":                 57,
		"scaleway_vpc_private_network":                 58,
		"scaleway_vpc_public_gateway":                  59,
		"scaleway_vpc_public_gateway_dhcp":             60,
		"scaleway_vpc_public_gateway_dhcp_reservation": 61,
		"scaleway_vpc_public_gateway_ip":               62,
		"scaleway_vpc_public_gateway_pat_rule":         63,
		"scaleway_webhosting_offer":                    64,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
