package scaleway

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "scaleway_account_ssh_key",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway user SSH keys.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_server",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Baremetal servers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance IPs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip_reverse_dns",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance IPs' reverse DNS.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_placement_group",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance Placement Groups.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_private_nic",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance Private NICs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance security groups.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group_rules",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance security group rules.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_server",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance servers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_volume",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance Volumes.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_device",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Hub device.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_hub",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Hub instances.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_network",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_routes",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Routes.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_cluster",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Kubernetes clusters.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_pool",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Kubernetes cluster pools.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_backend",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancer Backends.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_certificate",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancer Certificates.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_frontend",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancer Frontends.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_ip",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancers IPs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway object storage buckets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The unique name of the bucket.`,
				},
				resource.Attribute{
					Name:        "endpoint",
					Description: `The endpoint URL of the bucket ## Import Buckets can be imported using the ` + "`" + `{region}/{bucketName}` + "`" + ` identifier, e.g. ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object_bucket.some_bucket fr-par/some-bucket ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_instance",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Database Instances.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_user",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Database Users.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_registry_namespace",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Container Registries.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_private_network",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Private Networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"scaleway_account_ssh_key":               0,
		"scaleway_baremetal_server":              1,
		"scaleway_instance_ip":                   2,
		"scaleway_instance_ip_reverse_dns":       3,
		"scaleway_instance_placement_group":      4,
		"scaleway_instance_private_nic":          5,
		"scaleway_instance_security_group":       6,
		"scaleway_instance_security_group_rules": 7,
		"scaleway_instance_server":               8,
		"scaleway_instance_volume":               9,
		"scaleway_iot_device":                    10,
		"scaleway_iot_hub":                       11,
		"scaleway_iot_network":                   12,
		"scaleway_iot_routes":                    13,
		"scaleway_k8s_cluster":                   14,
		"scaleway_k8s_pool":                      15,
		"scaleway_lb":                            16,
		"scaleway_lb_backend":                    17,
		"scaleway_lb_certificate":                18,
		"scaleway_lb_frontend":                   19,
		"scaleway_lb_ip":                         20,
		"scaleway_object_bucket":                 21,
		"scaleway_rdb_instance":                  22,
		"scaleway_rdb_user":                      23,
		"scaleway_registry_namespace":            24,
		"scaleway_vpc_private_network":           25,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
