package scaleway

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "scaleway_account_project",
			Category:         "Account",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"account",
				"project",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_account_ssh_key",
			Category:         "Account",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"account",
				"ssh",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_apple_silicon",
			Category:         "Apple Silicon",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"apple",
				"silicon",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_server",
			Category:         "Elastic Metal",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"elastic",
				"metal",
				"baremetal",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_cockpit",
			Category:         "Cockpit",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cockpit",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_cockpit_grafana_user",
			Category:         "Cockpit",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cockpit",
				"grafana",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_cockpit_token",
			Category:         "Cockpit",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"cockpit",
				"token",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container",
			Category:         "Containers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"containers",
				"container",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container_cron",
			Category:         "Containers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"containers",
				"container",
				"cron",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container_domain",
			Category:         "Containers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"containers",
				"container",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container_namespace",
			Category:         "Containers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"containers",
				"container",
				"namespace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container_token",
			Category:         "Containers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"containers",
				"container",
				"token",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_record",
			Category:         "Domains and DNS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"domains",
				"and",
				"dns",
				"domain",
				"record",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_zone",
			Category:         "Domains and DNS",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"domains",
				"and",
				"dns",
				"domain",
				"zone",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_flexible_ip",
			Category:         "Elastic Metal",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"elastic",
				"metal",
				"flexible",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function",
			Category:         "Functions",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"functions",
				"function",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function_cron",
			Category:         "Functions",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"functions",
				"function",
				"cron",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function_domain",
			Category:         "Functions",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"functions",
				"function",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function_namespace",
			Category:         "Functions",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"functions",
				"function",
				"namespace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function_token",
			Category:         "Functions",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"functions",
				"function",
				"token",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_api_key",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"api",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_application",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"application",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_group",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_policy",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iam_ssh_key",
			Category:         "IAM",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iam",
				"ssh",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_image",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"image",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip_reverse_dns",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"ip",
				"reverse",
				"dns",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_placement_group",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"placement",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_private_nic",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"private",
				"nic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"security",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group_rules",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"security",
				"group",
				"rules",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_server",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_snapshot",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"snapshot",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_user_data",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"user",
				"data",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_volume",
			Category:         "Instances",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"instances",
				"instance",
				"volume",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_device",
			Category:         "IoT Hub",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iot",
				"hub",
				"device",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_hub",
			Category:         "IoT Hub",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iot",
				"hub",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_network",
			Category:         "IoT Hub",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iot",
				"hub",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_routes",
			Category:         "IoT Hub",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"iot",
				"hub",
				"routes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_cluster",
			Category:         "Kubernetes",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"kubernetes",
				"k8s",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_pool",
			Category:         "Kubernetes",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"kubernetes",
				"k8s",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_backend",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"backend",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_certificate",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"certificate",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_frontend",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"frontend",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_ip",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_route",
			Category:         "Load Balancers",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"load",
				"balancers",
				"lb",
				"route",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_mnq_credential",
			Category:         "Messaging and Queuing",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"messaging",
				"and",
				"queuing",
				"mnq",
				"credential",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_mnq_namespace",
			Category:         "Messaging and Queuing",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"messaging",
				"and",
				"queuing",
				"mnq",
				"namespace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_mnq_queue",
			Category:         "Messaging and Queuing",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"messaging",
				"and",
				"queuing",
				"mnq",
				"queue",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "namespace_id",
					Description: `(Required) The ID of the Namespace associated to.`,
				},
				resource.Attribute{
					Name:        "name",
					Description: `(Optional) The name of the queue. Either ` + "`" + `name` + "`" + ` or ` + "`" + `name_prefix` + "`" + ` is required. Conflicts with ` + "`" + `name_prefix` + "`" + `.`,
				},
				resource.Attribute{
					Name:        "name_prefix",
					Description: `(Optional) Creates a unique name beginning with the specified prefix. Conflicts with ` + "`" + `name` + "`" + `.`,
				},
				resource.Attribute{
					Name:        "message_max_age",
					Description: `(Optional) The number of seconds the queue retains a message. Must be between 60 and 1_209_600. Defaults to 345_600.`,
				},
				resource.Attribute{
					Name:        "message_max_size",
					Description: `(Optional) The maximum size of a message. Should be in bytes. Must be between 1024 and 262_144. Defaults to 262_144.`,
				},
				resource.Attribute{
					Name:        "sqs",
					Description: `(Optional) The SQS attributes of the queue. Conflicts with ` + "`" + `nats` + "`" + `. - ` + "`" + `endpoint` + "`" + ` - (Optional) The endpoint of the SQS queue. Can contain a {region} placeholder. Defaults to ` + "`" + `http://sqs-sns.mnq.{region}.scw.cloud` + "`" + `. - ` + "`" + `access_key` + "`" + ` - (Required) The access key of the SQS queue. - ` + "`" + `secret_key` + "`" + ` - (Required) The secret key of the SQS queue. - ` + "`" + `fifo_queue` + "`" + ` - (Optional) Whether the queue is a FIFO queue. If true, the queue name must end with .fifo. Defaults to ` + "`" + `false` + "`" + `. - ` + "`" + `content_based_deduplication` + "`" + ` - (Optional) Specifies whether to enable content-based deduplication. Defaults to ` + "`" + `false` + "`" + `. - ` + "`" + `receive_wait_time_seconds` + "`" + ` - (Optional) The number of seconds to wait for a message to arrive in the queue before returning. Must be between 0 and 20. Defaults to 0. - ` + "`" + `visibility_timeout_seconds` + "`" + ` - (Optional) The number of seconds a message is hidden from other consumers. Must be between 0 and 43_200. Defaults to 30. - For more information about the SQS limitations, see [the documentation](https://www.scaleway.com/en/developers/api/messaging-and-queuing/#technical-limitations).`,
				},
				resource.Attribute{
					Name:        "nats",
					Description: `(Optional) The NATS attributes of the queue. Conflicts with ` + "`" + `sqs` + "`" + `. - ` + "`" + `endpoint` + "`" + ` - (Optional) The endpoint of the NATS queue. Can contain a {region} placeholder. Defaults to ` + "`" + `nats://nats.mnq.{region}.scw.cloud:4222` + "`" + `. - ` + "`" + `credentials` + "`" + ` - (Required) Line jump separated key and seed. - ` + "`" + `retention_policy` + "`" + ` - (Optional) The retention policy of the queue. See https://docs.nats.io/nats-concepts/jetstream/streams#retentionpolicy for more information. Defaults to ` + "`" + `workqueue` + "`" + `. ### Attribute Reference In addition to all arguments above, the following attributes are exported:`,
				},
				resource.Attribute{
					Name:        "sqs",
					Description: `The SQS attributes of the queue. ~ ` + "`" + `url` + "`" + ` - The URL of the queue. ### Import Queues can be imported using the ` + "`" + `{region}/{namespace-id}/{queue-name}` + "`" + ` format: ` + "`" + `` + "`" + `` + "`" + `shell $ terraform import scaleway_mnq_queue.my_queue fr-par/11111111111111111111111111111111/my-queue ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "sqs",
					Description: `The SQS attributes of the queue. ~ ` + "`" + `url` + "`" + ` - The URL of the queue. ### Import Queues can be imported using the ` + "`" + `{region}/{namespace-id}/{queue-name}` + "`" + ` format: ` + "`" + `` + "`" + `` + "`" + `shell $ terraform import scaleway_mnq_queue.my_queue fr-par/11111111111111111111111111111111/my-queue ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
			},
			Arguments: []resource.Attribute{},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The path of the object, including bucket name. ~>`,
				},
				resource.Attribute{
					Name:        "region",
					Description: `The Scaleway region this bucket resides in. ## Import Objects can be imported using the ` + "`" + `{region}/{bucketName}/{objectKey}` + "`" + ` identifier, e.g. ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object.some_object fr-par/some-bucket/some-file ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
				"bucket",
			},
			Arguments: []resource.Attribute{},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The unique name of the bucket. ~>`,
				},
				resource.Attribute{
					Name:        "endpoint",
					Description: `The endpoint URL of the bucket`,
				},
				resource.Attribute{
					Name:        "region",
					Description: `The Scaleway region this bucket resides in. ## Import Buckets can be imported using the ` + "`" + `{region}/{bucketName}` + "`" + ` identifier, e.g. ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object_bucket.some_bucket fr-par/some-bucket ` + "`" + `` + "`" + `` + "`" + ` If you are importing a bucket from a specific project (that is not your default project), you can use the following syntax: ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object_bucket.some_bucket fr-par/some-bucket@11111111-1111-1111-1111-111111111111 ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket_acl",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
				"bucket",
				"acl",
			},
			Arguments: []resource.Attribute{},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The ` + "`" + `region` + "`" + `,` + "`" + `bucket` + "`" + ` and ` + "`" + `acl` + "`" + ` separated by (` + "`" + `/` + "`" + `). ## Import Buckets can be imported using the ` + "`" + `{region}/{bucketName}/{acl}` + "`" + ` identifier, e.g. ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object_bucket_acl.some_bucket fr-par/some-bucket /private` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket_object_lock_configuration",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
				"bucket",
				"lock",
				"configuration",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket_policy",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
				"bucket",
				"policy",
			},
			Arguments: []resource.Attribute{},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The ID of the policy, which is the ID of the bucket. ~>`,
				},
				resource.Attribute{
					Name:        "region",
					Description: `The Scaleway region this bucket resides in. ## Import Buckets can be imported using the ` + "`" + `{region}/{bucketName}` + "`" + ` identifier, e.g. ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object_bucket_policy.some_bucket fr-par/some-bucket ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket_website_configuration",
			Category:         "Object Storage",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"object",
				"storage",
				"bucket",
				"website",
				"configuration",
			},
			Arguments: []resource.Attribute{},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "bucket",
					Description: `(Required, Forces new resource) The name of the bucket.`,
				},
				resource.Attribute{
					Name:        "index_document",
					Description: `(Required) The name of the index document for the website [detailed below](#index_document).`,
				},
				resource.Attribute{
					Name:        "error_document",
					Description: `(Optional) The name of the error document for the website [detailed below](#error_document).`,
				},
				resource.Attribute{
					Name:        "project_id",
					Description: `(Defaults to [provider](../index.md#project_id) ` + "`" + `project_id` + "`" + `) The ID of the project the bucket is associated with. ## index_document The ` + "`" + `index_document` + "`" + ` configuration block supports the following arguments:`,
				},
				resource.Attribute{
					Name:        "suffix",
					Description: `(Required) A suffix that is appended to a request that is for a directory on the website endpoint. ~>`,
				},
				resource.Attribute{
					Name:        "id",
					Description: `The region and bucket separated by a slash (/)`,
				},
				resource.Attribute{
					Name:        "website_domain",
					Description: `The domain of the website endpoint. This is used to create DNS alias [records](https://www.scaleway.com/en/docs/network/domains-and-dns/how-to/manage-dns-records/).`,
				},
				resource.Attribute{
					Name:        "website_endpoint",
					Description: `The website endpoint. ~>`,
				},
				resource.Attribute{
					Name:        "key",
					Description: `(Required) The object key name to use when a 4XX class error occurs. ## Import Website configuration Bucket can be imported using the ` + "`" + `{region}/{bucketName}` + "`" + ` identifier, e.g. ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object_bucket_website_configuration.some_bucket fr-par/some-bucket ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_acl",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"acl",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_database",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"database",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_database_backup",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"database",
				"backup",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_instance",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"instance",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_privilege",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"privilege",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_read_replica",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"read",
				"replica",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_user",
			Category:         "Databases",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"databases",
				"rdb",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_redis_cluster",
			Category:         "Redis",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"redis",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_registry_namespace",
			Category:         "Container Registry",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"container",
				"registry",
				"namespace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_secret",
			Category:         "Secrets",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"secrets",
				"secret",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_secret_version",
			Category:         "Secrets",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"secrets",
				"secret",
				"version",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_tem_domain",
			Category:         "Transactional Email",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"transactional",
				"email",
				"tem",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_gateway_network",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"gateway",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_private_network",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"private",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_dhcp",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"dhcp",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_dhcp_reservation",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"dhcp",
				"reservation",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_ip",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_ip_reverse_dns",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"ip",
				"reverse",
				"dns",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_pat_rule",
			Category:         "VPC",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vpc",
				"public",
				"gateway",
				"pat",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"scaleway_account_project":                         0,
		"scaleway_account_ssh_key":                         1,
		"scaleway_apple_silicon":                           2,
		"scaleway_baremetal_server":                        3,
		"scaleway_cockpit":                                 4,
		"scaleway_cockpit_grafana_user":                    5,
		"scaleway_cockpit_token":                           6,
		"scaleway_container":                               7,
		"scaleway_container_cron":                          8,
		"scaleway_container_domain":                        9,
		"scaleway_container_namespace":                     10,
		"scaleway_container_token":                         11,
		"scaleway_domain_record":                           12,
		"scaleway_domain_zone":                             13,
		"scaleway_flexible_ip":                             14,
		"scaleway_function":                                15,
		"scaleway_function_cron":                           16,
		"scaleway_function_domain":                         17,
		"scaleway_function_namespace":                      18,
		"scaleway_function_token":                          19,
		"scaleway_iam_api_key":                             20,
		"scaleway_iam_application":                         21,
		"scaleway_iam_group":                               22,
		"scaleway_iam_policy":                              23,
		"scaleway_iam_ssh_key":                             24,
		"scaleway_instance_image":                          25,
		"scaleway_instance_ip":                             26,
		"scaleway_instance_ip_reverse_dns":                 27,
		"scaleway_instance_placement_group":                28,
		"scaleway_instance_private_nic":                    29,
		"scaleway_instance_security_group":                 30,
		"scaleway_instance_security_group_rules":           31,
		"scaleway_instance_server":                         32,
		"scaleway_instance_snapshot":                       33,
		"scaleway_instance_user_data":                      34,
		"scaleway_instance_volume":                         35,
		"scaleway_iot_device":                              36,
		"scaleway_iot_hub":                                 37,
		"scaleway_iot_network":                             38,
		"scaleway_iot_routes":                              39,
		"scaleway_k8s_cluster":                             40,
		"scaleway_k8s_pool":                                41,
		"scaleway_lb":                                      42,
		"scaleway_lb_backend":                              43,
		"scaleway_lb_certificate":                          44,
		"scaleway_lb_frontend":                             45,
		"scaleway_lb_ip":                                   46,
		"scaleway_lb_route":                                47,
		"scaleway_mnq_credential":                          48,
		"scaleway_mnq_namespace":                           49,
		"scaleway_mnq_queue":                               50,
		"scaleway_object":                                  51,
		"scaleway_object_bucket":                           52,
		"scaleway_object_bucket_acl":                       53,
		"scaleway_object_bucket_object_lock_configuration": 54,
		"scaleway_object_bucket_policy":                    55,
		"scaleway_object_bucket_website_configuration":     56,
		"scaleway_rdb_acl":                                 57,
		"scaleway_rdb_database":                            58,
		"scaleway_rdb_database_backup":                     59,
		"scaleway_rdb_instance":                            60,
		"scaleway_rdb_privilege":                           61,
		"scaleway_rdb_read_replica":                        62,
		"scaleway_rdb_user":                                63,
		"scaleway_redis_cluster":                           64,
		"scaleway_registry_namespace":                      65,
		"scaleway_secret":                                  66,
		"scaleway_secret_version":                          67,
		"scaleway_tem_domain":                              68,
		"scaleway_vpc_gateway_network":                     69,
		"scaleway_vpc_private_network":                     70,
		"scaleway_vpc_public_gateway":                      71,
		"scaleway_vpc_public_gateway_dhcp":                 72,
		"scaleway_vpc_public_gateway_dhcp_reservation":     73,
		"scaleway_vpc_public_gateway_ip":                   74,
		"scaleway_vpc_public_gateway_ip_reverse_dns":       75,
		"scaleway_vpc_public_gateway_pat_rule":             76,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
