package scaleway

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "scaleway_account_ssh_key",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway user SSH keys.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_apple_silicon",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Apple silicon M1 as-a-Service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_baremetal_server",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Baremetal servers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Containers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_container_namespace",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Container Namespaces.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_record",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Domain records.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_domain_zone",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Domain zones.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_function_namespace",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Function Namespaces.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance IPs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_ip_reverse_dns",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance IPs' reverse DNS.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_placement_group",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance Placement Groups.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_private_nic",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance Private NICs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance security groups.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_security_group_rules",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance security group rules.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_server",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance servers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_snapshot",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Instance Snapshots.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_instance_volume",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Compute Instance Volumes.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_device",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Hub device.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_hub",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Hub instances.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_network",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_iot_routes",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway IoT Routes.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_cluster",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Kubernetes clusters.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_k8s_pool",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Kubernetes cluster pools.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_backend",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancer Backends.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_certificate",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancer Certificates.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_frontend",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancer Frontends.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_ip",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancers IPs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_lb_route",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Load-Balancer Route.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_object_bucket",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway object storage buckets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "id",
					Description: `The unique name of the bucket.`,
				},
				resource.Attribute{
					Name:        "endpoint",
					Description: `The endpoint URL of the bucket`,
				},
				resource.Attribute{
					Name:        "region",
					Description: `The Scaleway region this bucket resides in. ## Import Buckets can be imported using the ` + "`" + `{region}/{bucketName}` + "`" + ` identifier, e.g. ` + "`" + `` + "`" + `` + "`" + `bash $ terraform import scaleway_object_bucket.some_bucket fr-par/some-bucket ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_acl",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Database ACL rules.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_database",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway RDB Database.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_instance",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Database Instances.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_privilege",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway RDB Database Privilege.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_rdb_user",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Database Users.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_redis_cluster",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Redis Clusters.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_registry_namespace",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway Container Registries.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_gateway_network",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Gateway Networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_private_network",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Private Networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Public Gateways.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_dhcp",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Public Gateways IP.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_dhcp_reservation",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Public Gateways DHCP Reservations.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_ip",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Public Gateways IP.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "scaleway_vpc_public_gateway_pat_rule",
			Category:         "Resources",
			ShortDescription: `Manages Scaleway VPC Public Gateways PAT rules.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"scaleway_account_ssh_key":                     0,
		"scaleway_apple_silicon":                       1,
		"scaleway_baremetal_server":                    2,
		"scaleway_container":                           3,
		"scaleway_container_namespace":                 4,
		"scaleway_domain_record":                       5,
		"scaleway_domain_zone":                         6,
		"scaleway_function_namespace":                  7,
		"scaleway_instance_ip":                         8,
		"scaleway_instance_ip_reverse_dns":             9,
		"scaleway_instance_placement_group":            10,
		"scaleway_instance_private_nic":                11,
		"scaleway_instance_security_group":             12,
		"scaleway_instance_security_group_rules":       13,
		"scaleway_instance_server":                     14,
		"scaleway_instance_snapshot":                   15,
		"scaleway_instance_volume":                     16,
		"scaleway_iot_device":                          17,
		"scaleway_iot_hub":                             18,
		"scaleway_iot_network":                         19,
		"scaleway_iot_routes":                          20,
		"scaleway_k8s_cluster":                         21,
		"scaleway_k8s_pool":                            22,
		"scaleway_lb":                                  23,
		"scaleway_lb_backend":                          24,
		"scaleway_lb_certificate":                      25,
		"scaleway_lb_frontend":                         26,
		"scaleway_lb_ip":                               27,
		"scaleway_lb_route":                            28,
		"scaleway_object_bucket":                       29,
		"scaleway_rdb_acl":                             30,
		"scaleway_rdb_database":                        31,
		"scaleway_rdb_instance":                        32,
		"scaleway_rdb_privilege":                       33,
		"scaleway_rdb_user":                            34,
		"scaleway_redis_cluster":                       35,
		"scaleway_registry_namespace":                  36,
		"scaleway_vpc_gateway_network":                 37,
		"scaleway_vpc_private_network":                 38,
		"scaleway_vpc_public_gateway":                  39,
		"scaleway_vpc_public_gateway_dhcp":             40,
		"scaleway_vpc_public_gateway_dhcp_reservation": 41,
		"scaleway_vpc_public_gateway_ip":               42,
		"scaleway_vpc_public_gateway_pat_rule":         43,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
