package ionoscloud

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_application_loadbalancer",
			Category:         "Application Load Balancer",
			ShortDescription: `Creates and manages IonosCloud Application Load Balancer.`,
			Description:      ``,
			Keywords: []string{
				"application",
				"load",
				"balancer",
				"loadbalancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_application_loadbalancer_forwardingrule",
			Category:         "Application Load Balancer",
			ShortDescription: `Creates and manages IonosCloud Application Load Balancer Forwarding Rule.`,
			Description:      ``,
			Keywords: []string{
				"application",
				"load",
				"balancer",
				"loadbalancer",
				"forwardingrule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_backup_unit",
			Category:         "Managed Backup",
			ShortDescription: `Creates and manages IonosCloud Backup Units.`,
			Description:      ``,
			Keywords: []string{
				"managed",
				"backup",
				"unit",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_certificate",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages a certificate.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"certificate",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Required)[string] The certificate name`,
				},
				resource.Attribute{
					Name:        "certificate",
					Description: `(Required)[string] The certificate body. Pem encoded. Immutable.`,
				},
				resource.Attribute{
					Name:        "private_key",
					Description: `(Required)[string] The certificate private key. Immutable. Sensitive.`,
				},
				resource.Attribute{
					Name:        "certificate_chain",
					Description: `(Optional)[string] The certificate chain. Pem encoded. Immutable. ## Import Resource certificate can be imported using the ` + "`" + `resource id` + "`" + `, e.g. ` + "`" + `` + "`" + `` + "`" + `shell terraform import ionoscloud_certificate.mycert {certificate uuid} ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_container_registry",
			Category:         "Container Registry",
			ShortDescription: `Creates and manages IonosCloud Container Registry.`,
			Description:      ``,
			Keywords: []string{
				"container",
				"registry",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "garbage_collection_schedule",
					Description: `(Optional)[Map]`,
				},
				resource.Attribute{
					Name:        "time",
					Description: `(Required)[string]`,
				},
				resource.Attribute{
					Name:        "days",
					Description: `(Required)[list] Elements of list must have one of the values: ` + "`" + `Saturday` + "`" + `, ` + "`" + `Sunday` + "`" + `, ` + "`" + `Monday` + "`" + `, ` + "`" + `Tuesday` + "`" + `, ` + "`" + `Wednesday` + "`" + `, ` + "`" + `Thursday` + "`" + `, ` + "`" + `Friday` + "`" + ``,
				},
				resource.Attribute{
					Name:        "location",
					Description: `(Required)[string] Immutable, update forces re-creation of the resource. ## Import Resource Container Registry can be imported using the ` + "`" + `resource id` + "`" + `, e.g. ` + "`" + `` + "`" + `` + "`" + `shell terraform import ionoscloud_container_registry.mycr {container_registry uuid} ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_container_registry_token",
			Category:         "Container Registry Token",
			ShortDescription: `Creates and manages IonosCloud Container Registry Token.`,
			Description:      ``,
			Keywords: []string{
				"container",
				"registry",
				"token",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "save_password_to_file",
					Description: `(Optional)[string] Saves token password to file. Only works on create. Takes as argument a file name, or a file path >`,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_cube_server",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IonosCloud Cube Server objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"cube",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_datacenter",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IonosCloud Virtual Data Center.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"datacenter",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Required)[string] The name of the Virtual Data Center.`,
				},
				resource.Attribute{
					Name:        "location",
					Description: `(Required)[string] The regional location where the Virtual Data Center will be created. This argument is immutable.`,
				},
				resource.Attribute{
					Name:        "description",
					Description: `(Optional)[string] Description for the Virtual Data Center.`,
				},
				resource.Attribute{
					Name:        "sec_auth_protection",
					Description: `(Optional) [bool] Boolean value representing if the data center requires extra protection e.g. two factor protection`,
				},
				resource.Attribute{
					Name:        "version",
					Description: `(Computed) The version of that Data Center. Gets incremented with every change`,
				},
				resource.Attribute{
					Name:        "features",
					Description: `(Computed) List of features supported by the location this data center is part of`,
				},
				resource.Attribute{
					Name:        "cpu_architecture",
					Description: `(Computed) Array of features and CPU families available in a location`,
				},
				resource.Attribute{
					Name:        "cpu_family",
					Description: `A valid CPU family name`,
				},
				resource.Attribute{
					Name:        "max_cores",
					Description: `The maximum number of cores available`,
				},
				resource.Attribute{
					Name:        "max_ram",
					Description: `The maximum number of RAM in MB`,
				},
				resource.Attribute{
					Name:        "vendor",
					Description: `A valid CPU vendor name ## Import Resource Datacenter can be imported using the ` + "`" + `resource id` + "`" + `, e.g. ` + "`" + `` + "`" + `` + "`" + `shell terraform import ionoscloud_datacenter.mydc {datacenter uuid} ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_dataplatform_cluster",
			Category:         "Dataplatform",
			ShortDescription: `Creates and manages Dataplatform Cluster objects.`,
			Description:      ``,
			Keywords: []string{
				"dataplatform",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_dataplatform_node_pool",
			Category:         "Dataplatform",
			ShortDescription: `Creates and manages Dataplatform Node Pool objects.`,
			Description:      ``,
			Keywords: []string{
				"dataplatform",
				"node",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_dbaas_mongo_cluster",
			Category:         "Database as a Service - MongoDB",
			ShortDescription: `Creates and manages DbaaS MongoDB Cluster objects.`,
			Description:      ``,
			Keywords: []string{
				"database",
				"as",
				"a",
				"service",
				"mongodb",
				"dbaas",
				"mongo",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_dbaas_mongo_user",
			Category:         "Database as a Service - MongoDB",
			ShortDescription: `Creates and manages DbaaS MongoDB users.`,
			Description:      ``,
			Keywords: []string{
				"database",
				"as",
				"a",
				"service",
				"mongodb",
				"dbaas",
				"mongo",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_dbaas_pgsql_cluster",
			Category:         "Database as a Service - Postgres",
			ShortDescription: `Creates and manages DbaaS Postgres Cluster objects.`,
			Description:      ``,
			Keywords: []string{
				"database",
				"as",
				"a",
				"service",
				"postgres",
				"dbaas",
				"pgsql",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_firewall",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Firewall Rules.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"firewall",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_group",
			Category:         "User Management",
			ShortDescription: `Creates and manages group objects.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_ipblock",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IP Block objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"ipblock",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_ipfailover",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages ipfailover objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"ipfailover",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_k8s_cluster",
			Category:         "Managed Kubernetes",
			ShortDescription: `Creates and manages IonosCloud Kubernetes Clusters.`,
			Description:      ``,
			Keywords: []string{
				"managed",
				"kubernetes",
				"k8s",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_k8s_node_pool",
			Category:         "Managed Kubernetes",
			ShortDescription: `Creates and manages IonosCloud Kubernetes Node Pools.`,
			Description:      ``,
			Keywords: []string{
				"managed",
				"kubernetes",
				"k8s",
				"node",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_lan",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages LAN objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"lan",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_loadbalancer",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Load Balancers`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"loadbalancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_natgateway",
			Category:         "NAT Gateway",
			ShortDescription: `Creates and manages Nat Gateway objects.`,
			Description:      ``,
			Keywords: []string{
				"nat",
				"gateway",
				"natgateway",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_natgateway_rule",
			Category:         "NAT Gateway",
			ShortDescription: `Creates and manages Nat Gateway Rule objects.`,
			Description:      ``,
			Keywords: []string{
				"nat",
				"gateway",
				"natgateway",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_networkloadbalancer",
			Category:         "Network Load Balancer",
			ShortDescription: `Creates and manages Network Load Balancer objects.`,
			Description:      ``,
			Keywords: []string{
				"network",
				"load",
				"balancer",
				"networkloadbalancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_networkloadbalancer_forwardingrule",
			Category:         "Network Load Balancer",
			ShortDescription: `Creates and manages Network Load Balancer Forwarding Rule objects.`,
			Description:      ``,
			Keywords: []string{
				"network",
				"load",
				"balancer",
				"networkloadbalancer",
				"forwardingrule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_nic",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Network Interface objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"nic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_private_crossconnect",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Private Cross Connections between virtual datacenters.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"private",
				"crossconnect",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_s3_key",
			Category:         "User Management",
			ShortDescription: `Creates and manages IonosCloud S3 keys.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
				"s3",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_server",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IonosCloud Server objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_share",
			Category:         "User Management",
			ShortDescription: `Creates and manages share objects.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
				"share",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_snapshot",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages snapshot objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"snapshot",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_target_group",
			Category:         "Application Load Balancer",
			ShortDescription: `Creates and manages IonosCloud Target Group.`,
			Description:      ``,
			Keywords: []string{
				"application",
				"load",
				"balancer",
				"target",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_user",
			Category:         "User Management",
			ShortDescription: `Creates and manages user objects.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_volume",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IonosCloud Volume objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"volume",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"ionoscloud_application_loadbalancer":                0,
		"ionoscloud_application_loadbalancer_forwardingrule": 1,
		"ionoscloud_backup_unit":                             2,
		"ionoscloud_certificate":                             3,
		"ionoscloud_container_registry":                      4,
		"ionoscloud_container_registry_token":                5,
		"ionoscloud_cube_server":                             6,
		"ionoscloud_datacenter":                              7,
		"ionoscloud_dataplatform_cluster":                    8,
		"ionoscloud_dataplatform_node_pool":                  9,
		"ionoscloud_dbaas_mongo_cluster":                     10,
		"ionoscloud_dbaas_mongo_user":                        11,
		"ionoscloud_dbaas_pgsql_cluster":                     12,
		"ionoscloud_firewall":                                13,
		"ionoscloud_group":                                   14,
		"ionoscloud_ipblock":                                 15,
		"ionoscloud_ipfailover":                              16,
		"ionoscloud_k8s_cluster":                             17,
		"ionoscloud_k8s_node_pool":                           18,
		"ionoscloud_lan":                                     19,
		"ionoscloud_loadbalancer":                            20,
		"ionoscloud_natgateway":                              21,
		"ionoscloud_natgateway_rule":                         22,
		"ionoscloud_networkloadbalancer":                     23,
		"ionoscloud_networkloadbalancer_forwardingrule":      24,
		"ionoscloud_nic":                                     25,
		"ionoscloud_private_crossconnect":                    26,
		"ionoscloud_s3_key":                                  27,
		"ionoscloud_server":                                  28,
		"ionoscloud_share":                                   29,
		"ionoscloud_snapshot":                                30,
		"ionoscloud_target_group":                            31,
		"ionoscloud_user":                                    32,
		"ionoscloud_volume":                                  33,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
