package ionoscloud

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_backup_unit",
			Category:         "Managed Backup",
			ShortDescription: `Creates and manages IonosCloud Backup Units.`,
			Description:      ``,
			Keywords: []string{
				"managed",
				"backup",
				"unit",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_datacenter",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IonosCloud Virtual Data Center.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"datacenter",
			},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "name",
					Description: `(Required)[string] The name of the Virtual Data Center.`,
				},
				resource.Attribute{
					Name:        "location",
					Description: `(Required)[string] The regional location where the Virtual Data Center will be created. This argument is immutable.`,
				},
				resource.Attribute{
					Name:        "description",
					Description: `(Optional)[string] Description for the Virtual Data Center.`,
				},
				resource.Attribute{
					Name:        "sec_auth_protection",
					Description: `(Optional) [bool] Boolean value representing if the data center requires extra protection e.g. two factor protection`,
				},
				resource.Attribute{
					Name:        "version",
					Description: `(Computed) The version of that Data Center. Gets incremented with every change`,
				},
				resource.Attribute{
					Name:        "features",
					Description: `(Computed) List of features supported by the location this data center is part of`,
				},
				resource.Attribute{
					Name:        "cpu_architecture",
					Description: `(Computed) Array of features and CPU families available in a location`,
				},
				resource.Attribute{
					Name:        "cpu_family",
					Description: `A valid CPU family name`,
				},
				resource.Attribute{
					Name:        "max_cores",
					Description: `The maximum number of cores available`,
				},
				resource.Attribute{
					Name:        "max_ram",
					Description: `The maximum number of RAM in MB`,
				},
				resource.Attribute{
					Name:        "vendor",
					Description: `A valid CPU vendor name ## Import Resource Datacenter can be imported using the ` + "`" + `resource id` + "`" + `, e.g. ` + "`" + `` + "`" + `` + "`" + `shell terraform import ionoscloud_datacenter.mydc {datacenter uuid} ` + "`" + `` + "`" + `` + "`" + ``,
				},
			},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_dbaas_pgsql_cluster",
			Category:         "Database as a Service - Postgres",
			ShortDescription: `Creates and manages DbaaS Postgres Cluster objects.`,
			Description:      ``,
			Keywords: []string{
				"database",
				"as",
				"a",
				"service",
				"postgres",
				"dbaas",
				"pgsql",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_firewall",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Firewall Rules.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"firewall",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_group",
			Category:         "User Management",
			ShortDescription: `Creates and manages group objects.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_ipblock",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IP Block objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"ipblock",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_ipfailover",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages ipfailover objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"ipfailover",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_k8s_cluster",
			Category:         "Managed Kubernetes",
			ShortDescription: `Creates and manages IonosCloud Kubernetes Clusters.`,
			Description:      ``,
			Keywords: []string{
				"managed",
				"kubernetes",
				"k8s",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_k8s_node_pool",
			Category:         "Managed Kubernetes",
			ShortDescription: `Creates and manages IonosCloud Kubernetes Node Pools.`,
			Description:      ``,
			Keywords: []string{
				"managed",
				"kubernetes",
				"k8s",
				"node",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_lan",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages LAN objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"lan",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_loadbalancer",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Load Balancers`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"loadbalancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_natgateway",
			Category:         "NAT Gateway",
			ShortDescription: `Creates and manages Nat Gateway objects.`,
			Description:      ``,
			Keywords: []string{
				"nat",
				"gateway",
				"natgateway",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_natgateway_rule",
			Category:         "NAT Gateway",
			ShortDescription: `Creates and manages Nat Gateway Rule objects.`,
			Description:      ``,
			Keywords: []string{
				"nat",
				"gateway",
				"natgateway",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_networkloadbalancer",
			Category:         "Network Load Balancer",
			ShortDescription: `Creates and manages Network Load Balancer objects.`,
			Description:      ``,
			Keywords: []string{
				"network",
				"load",
				"balancer",
				"networkloadbalancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_networkloadbalancer_forwardingrule",
			Category:         "Network Load Balancer",
			ShortDescription: `Creates and manages Network Load Balancer Forwarding Rule objects.`,
			Description:      ``,
			Keywords: []string{
				"network",
				"load",
				"balancer",
				"networkloadbalancer",
				"forwardingrule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_nic",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Network Interface objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"nic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_private_crossconnect",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages Private Cross Connections between virtual datacenters.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"private",
				"crossconnect",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_s3_key",
			Category:         "User Management",
			ShortDescription: `Creates and manages IonosCloud S3 keys.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
				"s3",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_server",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IonosCloud Server objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_share",
			Category:         "User Management",
			ShortDescription: `Creates and manages share objects.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
				"share",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_snapshot",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages snapshot objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"snapshot",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_user",
			Category:         "User Management",
			ShortDescription: `Creates and manages user objects.`,
			Description:      ``,
			Keywords: []string{
				"user",
				"management",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ionoscloud_volume",
			Category:         "Compute Engine",
			ShortDescription: `Creates and manages IonosCloud Volume objects.`,
			Description:      ``,
			Keywords: []string{
				"compute",
				"engine",
				"volume",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"ionoscloud_backup_unit":                        0,
		"ionoscloud_datacenter":                         1,
		"ionoscloud_dbaas_pgsql_cluster":                2,
		"ionoscloud_firewall":                           3,
		"ionoscloud_group":                              4,
		"ionoscloud_ipblock":                            5,
		"ionoscloud_ipfailover":                         6,
		"ionoscloud_k8s_cluster":                        7,
		"ionoscloud_k8s_node_pool":                      8,
		"ionoscloud_lan":                                9,
		"ionoscloud_loadbalancer":                       10,
		"ionoscloud_natgateway":                         11,
		"ionoscloud_natgateway_rule":                    12,
		"ionoscloud_networkloadbalancer":                13,
		"ionoscloud_networkloadbalancer_forwardingrule": 14,
		"ionoscloud_nic":                                15,
		"ionoscloud_private_crossconnect":               16,
		"ionoscloud_s3_key":                             17,
		"ionoscloud_server":                             18,
		"ionoscloud_share":                              19,
		"ionoscloud_snapshot":                           20,
		"ionoscloud_user":                               21,
		"ionoscloud_volume":                             22,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
