package samsungcloudplatform

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_block_storages",
			Category:         "Data Sources",
			ShortDescription: `Provides list of block storages`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_file_storages",
			Category:         "Data Sources",
			ShortDescription: `Provides list of file storages`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_firewalls",
			Category:         "Data Sources",
			ShortDescription: `Provides list of firewalls`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_kubernetes_apps_images",
			Category:         "Data Sources",
			ShortDescription: `Provides list of K8s app images`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_kubernetes_engine_versions",
			Category:         "Data Sources",
			ShortDescription: `Provides list of K8s versions`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_kubernetes_engines",
			Category:         "Data Sources",
			ShortDescription: `Provides list of K8s engines`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_kubernetes_node_pools",
			Category:         "Data Sources",
			ShortDescription: `Provides list of K8s node pools`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_kubernetes_subnet",
			Category:         "Data Sources",
			ShortDescription: `Check whether Subnet is usable for Kubernetes Engine or not (usable : true, not usable : false)`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_lb_server_groups",
			Category:         "Data Sources",
			ShortDescription: `Provides list of Load Balancer server groups`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_lb_service_ips",
			Category:         "Data Sources",
			ShortDescription: `Provides list of Load Balancer service ips`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_lb_services",
			Category:         "Data Sources",
			ShortDescription: `Provides list of Load Balancer services`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_load_balancers",
			Category:         "Data Sources",
			ShortDescription: `Provides list of load balancers`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_product",
			Category:         "Data Sources",
			ShortDescription: `Provides list of products.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_project",
			Category:         "Data Sources",
			ShortDescription: `Provides list of my projects.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_public_ips",
			Category:         "Data Sources",
			ShortDescription: `Provides list of public ips`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_regions",
			Category:         "Data Sources",
			ShortDescription: `Provides list of regions`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_standard_images",
			Category:         "Data Sources",
			ShortDescription: `Provides list of standard images`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_subnet_resources",
			Category:         "Data Sources",
			ShortDescription: `Provides list of subnet resources`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_subnets",
			Category:         "Data Sources",
			ShortDescription: `Provides list of subnets.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "samsungcloudplatform_vpcs",
			Category:         "Data Sources",
			ShortDescription: `Provides list of vpcs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"samsungcloudplatform_block_storages":             0,
		"samsungcloudplatform_file_storages":              1,
		"samsungcloudplatform_firewalls":                  2,
		"samsungcloudplatform_kubernetes_apps_images":     3,
		"samsungcloudplatform_kubernetes_engine_versions": 4,
		"samsungcloudplatform_kubernetes_engines":         5,
		"samsungcloudplatform_kubernetes_node_pools":      6,
		"samsungcloudplatform_kubernetes_subnet":          7,
		"samsungcloudplatform_lb_server_groups":           8,
		"samsungcloudplatform_lb_service_ips":             9,
		"samsungcloudplatform_lb_services":                10,
		"samsungcloudplatform_load_balancers":             11,
		"samsungcloudplatform_product":                    12,
		"samsungcloudplatform_project":                    13,
		"samsungcloudplatform_public_ips":                 14,
		"samsungcloudplatform_regions":                    15,
		"samsungcloudplatform_standard_images":            16,
		"samsungcloudplatform_subnet_resources":           17,
		"samsungcloudplatform_subnets":                    18,
		"samsungcloudplatform_vpcs":                       19,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
