package aiven

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "aiven_account",
			Category:         "Data Sources",
			ShortDescription: `The Account data source provides information about the existing Aiven Account.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_authentication",
			Category:         "Data Sources",
			ShortDescription: `The Account Authentication data source provides information about the existing Aiven Account Authentication.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_team",
			Category:         "Data Sources",
			ShortDescription: `The Account Team data source provides information about the existing Account Team.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_team_member",
			Category:         "Data Sources",
			ShortDescription: `The Account Team Member data source provides information about the existing Aiven Account Team Member.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_team_project",
			Category:         "Data Sources",
			ShortDescription: `The Account Team Project data source provides information about the existing Account Team Project.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_aws_privatelink",
			Category:         "Data Sources",
			ShortDescription: `The AWS Privatelink resource allows the creation and management of Aiven AWS Privatelink for a services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_azure_privatelink",
			Category:         "Data Sources",
			ShortDescription: `The Azure Privatelink resource allows the creation and management of Aiven Azure Privatelink for a services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_billing_group",
			Category:         "Data Sources",
			ShortDescription: `The Billing Group data source provides information about the existing Aiven Account.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_cassandra",
			Category:         "Data Sources",
			ShortDescription: `The Cassandra data source provides information about the existing Aiven Cassandra service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse",
			Category:         "Data Sources",
			ShortDescription: `The Clickhouse data source provides information about the existing Aiven Clickhouse service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse_database",
			Category:         "Data Sources",
			ShortDescription: `The Clickhouse database data source provides information about the existing Aiven Clickhouse Database.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse_user",
			Category:         "Data Sources",
			ShortDescription: `The Clickhouse User data source provides information about the existing Aiven Clickhouse User.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_connection_pool",
			Category:         "Data Sources",
			ShortDescription: `The Connection Pool data source provides information about the existing Aiven Connection Pool.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_database",
			Category:         "Data Sources",
			ShortDescription: `The Database data source provides information about the existing Aiven Database.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch",
			Category:         "Data Sources",
			ShortDescription: `The Elasticsearch data source provides information about the existing Aiven Elasticsearch service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch_acl",
			Category:         "Data Sources",
			ShortDescription: `The Elasticsearch ACL data source provides information about the existing Aiven Elasticsearch ACL for Elasticsearch service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch_acl_config",
			Category:         "Data Sources",
			ShortDescription: `The Elasticsearch ACL Config data source provides information about an existing Aiven Elasticsearch ACL Config.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch_acl_rule",
			Category:         "Data Sources",
			ShortDescription: `The Elasticsearch ACL Rule data source provides information about an existing Aiven Elasticsearch ACL Rule.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_flink",
			Category:         "Data Sources",
			ShortDescription: `The Flink data source provides information about the existing Aiven Flink service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_grafana",
			Category:         "Data Sources",
			ShortDescription: `The Grafana data source provides information about the existing Aiven Grafana service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_influxdb",
			Category:         "Data Sources",
			ShortDescription: `The InfluxDB data source provides information about the existing Aiven InfluxDB service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka",
			Category:         "Data Sources",
			ShortDescription: `The Kafka data source provides information about the existing Aiven Kafka services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_acl",
			Category:         "Data Sources",
			ShortDescription: `The Data Source Kafka ACL data source provides information about the existing Aiven Kafka ACL for a Kafka service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_connect",
			Category:         "Data Sources",
			ShortDescription: `The Kafka Connect data source provides information about the existing Aiven Kafka Connect service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_connector",
			Category:         "Data Sources",
			ShortDescription: `The Kafka connector data source provides information about the existing Aiven Kafka connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_mirrormaker",
			Category:         "Data Sources",
			ShortDescription: `The Kafka MirrorMaker data source provides information about the existing Aiven Kafka MirrorMaker 2 service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_schema",
			Category:         "Data Sources",
			ShortDescription: `The Kafka Schema data source provides information about the existing Aiven Kafka Schema.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_schema_configuration",
			Category:         "Data Sources",
			ShortDescription: `The Kafka Schema Configuration data source provides information about the existing Aiven Kafka Schema Configuration.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_topic",
			Category:         "Data Sources",
			ShortDescription: `The Kafka Topic data source provides information about the existing Aiven Kafka Topic.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_m3aggregator",
			Category:         "Data Sources",
			ShortDescription: `The M3 Aggregator data source provides information about the existing Aiven M3 Aggregator.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_m3db",
			Category:         "Data Sources",
			ShortDescription: `The M3 DB data source provides information about the existing Aiven M3 services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_mirrormaker_replication_flow",
			Category:         "Data Sources",
			ShortDescription: `The MirrorMaker 2 Replication Flow data source provides information about the existing MirrorMaker 2 Replication Flow on Aiven Cloud.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_mysql",
			Category:         "Data Sources",
			ShortDescription: `The MySQL data source provides information about the existing Aiven MySQL service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_opensearch",
			Category:         "Data Sources",
			ShortDescription: `The Opensearch data source provides information about the existing Aiven Opensearch service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_opensearch_acl_config",
			Category:         "Data Sources",
			ShortDescription: `The Opensearch ACL Config data source provides information about an existing Aiven Opensearch ACL Config.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_opensearch_acl_rule",
			Category:         "Data Sources",
			ShortDescription: `The Opensearch ACL Rule data source provides information about an existing Aiven Opensearch ACL Rule.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_pg",
			Category:         "Data Sources",
			ShortDescription: `The PG data source provides information about the existing Aiven PostgreSQL service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_project",
			Category:         "Data Sources",
			ShortDescription: `The Project data source provides information about the existing Aiven Project.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_project_user",
			Category:         "Data Sources",
			ShortDescription: `The Project User data source provides information about the existing Aiven Project User.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_project_vpc",
			Category:         "Data Sources",
			ShortDescription: `The Project VPC data source provides information about the existing Aiven Project VPC.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_redis",
			Category:         "Data Sources",
			ShortDescription: `The Redis data source provides information about the existing Aiven Redis service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service",
			Category:         "Data Sources",
			ShortDescription: `The Service datasource provides information about specific Aiven Services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service_component",
			Category:         "Data Sources",
			ShortDescription: `The Service Component data source provides information about the existing Aiven service Component.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service_integration",
			Category:         "Data Sources",
			ShortDescription: `The Service Integration data source provides information about the existing Aiven Service Integration.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service_integration_endpoint",
			Category:         "Data Sources",
			ShortDescription: `The Service Integration Endpoint data source provides information about the existing Aiven Service Integration Endpoint.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service_user",
			Category:         "Data Sources",
			ShortDescription: `The Service User data source provides information about the existing Aiven Service User.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_transit_gateway_vpc_attachment",
			Category:         "Data Sources",
			ShortDescription: `The Transit Gateway VPC Attachment resource allows the creation and management Transit Gateway VPC Attachment VPC peering connection between Aiven and AWS.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_vpc_peering_connection",
			Category:         "Data Sources",
			ShortDescription: `The VPC Peering Connection data source provides information about the existing Aiven VPC Peering Connection.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"aiven_account":                        0,
		"aiven_account_authentication":         1,
		"aiven_account_team":                   2,
		"aiven_account_team_member":            3,
		"aiven_account_team_project":           4,
		"aiven_aws_privatelink":                5,
		"aiven_azure_privatelink":              6,
		"aiven_billing_group":                  7,
		"aiven_cassandra":                      8,
		"aiven_clickhouse":                     9,
		"aiven_clickhouse_database":            10,
		"aiven_clickhouse_user":                11,
		"aiven_connection_pool":                12,
		"aiven_database":                       13,
		"aiven_elasticsearch":                  14,
		"aiven_elasticsearch_acl":              15,
		"aiven_elasticsearch_acl_config":       16,
		"aiven_elasticsearch_acl_rule":         17,
		"aiven_flink":                          18,
		"aiven_grafana":                        19,
		"aiven_influxdb":                       20,
		"aiven_kafka":                          21,
		"aiven_kafka_acl":                      22,
		"aiven_kafka_connect":                  23,
		"aiven_kafka_connector":                24,
		"aiven_kafka_mirrormaker":              25,
		"aiven_kafka_schema":                   26,
		"aiven_kafka_schema_configuration":     27,
		"aiven_kafka_topic":                    28,
		"aiven_m3aggregator":                   29,
		"aiven_m3db":                           30,
		"aiven_mirrormaker_replication_flow":   31,
		"aiven_mysql":                          32,
		"aiven_opensearch":                     33,
		"aiven_opensearch_acl_config":          34,
		"aiven_opensearch_acl_rule":            35,
		"aiven_pg":                             36,
		"aiven_project":                        37,
		"aiven_project_user":                   38,
		"aiven_project_vpc":                    39,
		"aiven_redis":                          40,
		"aiven_service":                        41,
		"aiven_service_component":              42,
		"aiven_service_integration":            43,
		"aiven_service_integration_endpoint":   44,
		"aiven_service_user":                   45,
		"aiven_transit_gateway_vpc_attachment": 46,
		"aiven_vpc_peering_connection":         47,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
