package aiven

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "aiven_account",
			Category:         "Resources",
			ShortDescription: `The Account resource allows the creation and management of an Aiven Account.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_authentication",
			Category:         "Resources",
			ShortDescription: `The Account Authentication resource allows the creation and management of an Aiven Account Authentications.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_team",
			Category:         "Resources",
			ShortDescription: `The Account Team resource allows the creation and management of an Account Team.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_team_member",
			Category:         "Resources",
			ShortDescription: `The Account Team Member resource allows the creation and management of an Aiven Account Team Member. During the creation of aiven_account_team_memberresource, an email invitation will be sent to a user using user_email address. If the user accepts an invitation, he or she will become a member of the account team. The deletion of aiven_account_team_member will not only delete the invitation if one was sent but not yet accepted by the user, it will also eliminate an account team member if one has accepted an invitation previously.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_account_team_project",
			Category:         "Resources",
			ShortDescription: `The Account Team Project resource allows the creation and management of an Account Team Project. It is intended to link an existing project to the existing account team. It is important to note that the project should have an account_id property set equal to the account team you are trying to link to this project.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_aws_privatelink",
			Category:         "Resources",
			ShortDescription: `The AWS Privatelink resource allows the creation and management of Aiven AWS Privatelink for a services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_azure_privatelink",
			Category:         "Resources",
			ShortDescription: `The Azure Privatelink resource allows the creation and management of Aiven Azure Privatelink for a services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_azure_privatelink_connection_approval",
			Category:         "Resources",
			ShortDescription: `The Azure privatelink approve resource waits for an aiven privatelink connection on a service and approves it with associated endpoint IP`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_billing_group",
			Category:         "Resources",
			ShortDescription: `The Billing Group resource allows the creation and management of Aiven Billing Groups and association with the Projects.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_cassandra",
			Category:         "Resources",
			ShortDescription: `The Cassandra resource allows the creation and management of Aiven Cassandra services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse",
			Category:         "Resources",
			ShortDescription: `The Clickhouse resource allows the creation and management of Aiven Clickhouse services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse_database",
			Category:         "Resources",
			ShortDescription: `The Clickhouse Database resource allows the creation and management of Aiven Clickhouse Databases.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse_grant",
			Category:         "Resources",
			ShortDescription: `The Clickhouse Grant resource allows the creation and management of Grants in Aiven Clickhouse services. Notes: * Due to a ambiguity in the GRANT syntax in clickhouse you should not have users and roles with the same name. It is not clear if a grant refers to the user or the role. * Currently changes will first revoke all grants and then reissue the remaining grants for convergence.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse_role",
			Category:         "Resources",
			ShortDescription: `The Clickhouse Role resource allows the creation and management of Roles in Aiven Clickhouse services`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_clickhouse_user",
			Category:         "Resources",
			ShortDescription: `The Clickhouse User resource allows the creation and management of Aiven Clikhouse Users.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_connection_pool",
			Category:         "Resources",
			ShortDescription: `The Connection Pool resource allows the creation and management of Aiven Connection Pools.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_database",
			Category:         "Resources",
			ShortDescription: `The Database resource allows the creation and management of Aiven Databases.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch",
			Category:         "Resources",
			ShortDescription: `The Elasticsearch resource allows the creation and management of Aiven Elasticsearch services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch_acl",
			Category:         "Resources",
			ShortDescription: `This resource is deprecated, please use aiven_elasticsearch_acl_configand aiven_elasticsearch_acl_rule The Elasticsearch ACL resource allows the creation and management of ACLs for an Aiven Elasticsearch service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch_acl_config",
			Category:         "Resources",
			ShortDescription: `The Elasticsearch ACL Config resource allows the configuration of ACL management on an Aiven Elasticsearch service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_elasticsearch_acl_rule",
			Category:         "Resources",
			ShortDescription: `The Elasticsearch ACL Rule resource models a single ACL Rule for an Aiven Elasticsearch service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_flink",
			Category:         "Resources",
			ShortDescription: `The Flink resource allows the creation and management of Aiven Flink services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_flink_job",
			Category:         "Resources",
			ShortDescription: `The Flink Job resource allows the creation and management of Aiven Jobs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_flink_table",
			Category:         "Resources",
			ShortDescription: `The Flink Table resource allows the creation and management of Aiven Tables.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_grafana",
			Category:         "Resources",
			ShortDescription: `The Grafana resource allows the creation and management of Aiven Grafana services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_influxdb",
			Category:         "Resources",
			ShortDescription: `The InfluxDB resource allows the creation and management of Aiven InfluxDB services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka",
			Category:         "Resources",
			ShortDescription: `The Kafka resource allows the creation and management of Aiven Kafka services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_acl",
			Category:         "Resources",
			ShortDescription: `The Resource Kafka ACL resource allows the creation and management of ACLs for an Aiven Kafka service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_connect",
			Category:         "Resources",
			ShortDescription: `The Kafka Connect resource allows the creation and management of Aiven Kafka Connect services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_connector",
			Category:         "Resources",
			ShortDescription: `The Kafka connectors resource allows the creation and management of Aiven Kafka connectors.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_mirrormaker",
			Category:         "Resources",
			ShortDescription: `The Kafka MirrorMaker resource allows the creation and management of Aiven Kafka MirrorMaker 2 services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_schema",
			Category:         "Resources",
			ShortDescription: `The Kafka Schema resource allows the creation and management of Aiven Kafka Schemas.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_schema_configuration",
			Category:         "Resources",
			ShortDescription: `The Kafka Schema Configuration resource allows the creation and management of Aiven Kafka Schema Configurations.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_kafka_topic",
			Category:         "Resources",
			ShortDescription: `The Kafka Topic resource allows the creation and management of Aiven Kafka Topics.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_m3aggregator",
			Category:         "Resources",
			ShortDescription: `The M3 Aggregator resource allows the creation and management of Aiven M3 Aggregator services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_m3db",
			Category:         "Resources",
			ShortDescription: `The M3 DB resource allows the creation and management of Aiven M3 services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_mirrormaker_replication_flow",
			Category:         "Resources",
			ShortDescription: `The MirrorMaker 2 Replication Flow resource allows the creation and management of MirrorMaker 2 Replication Flows on Aiven Cloud.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_mysql",
			Category:         "Resources",
			ShortDescription: `The MySQL resource allows the creation and management of Aiven MySQL services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_opensearch",
			Category:         "Resources",
			ShortDescription: `The Opensearch resource allows the creation and management of Aiven Opensearch services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_opensearch_acl_config",
			Category:         "Resources",
			ShortDescription: `The Opensearch resource allows the creation and management of Aiven Opensearch services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_opensearch_acl_rule",
			Category:         "Resources",
			ShortDescription: `The Opensearch ACL Rule resource models a single ACL Rule for an Aiven Opensearch service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_pg",
			Category:         "Resources",
			ShortDescription: `The PG resource allows the creation and management of Aiven PostgreSQL services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_project",
			Category:         "Resources",
			ShortDescription: `The Project resource allows the creation and management of Aiven Projects.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_project_user",
			Category:         "Resources",
			ShortDescription: `The Project User resource allows the creation and management of Aiven Project Users.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_project_vpc",
			Category:         "Resources",
			ShortDescription: `The Project VPC resource allows the creation and management of Aiven Project VPCs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_redis",
			Category:         "Resources",
			ShortDescription: `The Redis resource allows the creation and management of Aiven Redis services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service",
			Category:         "Resources",
			ShortDescription: `The Service resource allows the creation and management of Aiven Services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service_integration",
			Category:         "Resources",
			ShortDescription: `The Service Integration resource allows the creation and management of Aiven Service Integrations.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service_integration_endpoint",
			Category:         "Resources",
			ShortDescription: `The Service Integration Endpoint resource allows the creation and management of Aiven Service Integration Endpoints.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_service_user",
			Category:         "Resources",
			ShortDescription: `The Service User resource allows the creation and management of Aiven Service Users.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_static_ip",
			Category:         "Resources",
			ShortDescription: `The aiven static_ip resource allows the creation and deletion of static ips. Please not that once a static ip is in the 'assigned' state it it is bound to the node it is assigned to and cannot be deleted or disassociated until the node is recycled. Plans that would delete static ips that are in the assigned state will be blocked.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_transit_gateway_vpc_attachment",
			Category:         "Resources",
			ShortDescription: `The Transit Gateway VPC Attachment resource allows the creation and management Transit Gateway VPC Attachment VPC peering connection between Aiven and AWS.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "aiven_vpc_peering_connection",
			Category:         "Resources",
			ShortDescription: `The VPC Peering Connection resource allows the creation and management of Aiven VPC Peering Connections.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"aiven_account":                               0,
		"aiven_account_authentication":                1,
		"aiven_account_team":                          2,
		"aiven_account_team_member":                   3,
		"aiven_account_team_project":                  4,
		"aiven_aws_privatelink":                       5,
		"aiven_azure_privatelink":                     6,
		"aiven_azure_privatelink_connection_approval": 7,
		"aiven_billing_group":                         8,
		"aiven_cassandra":                             9,
		"aiven_clickhouse":                            10,
		"aiven_clickhouse_database":                   11,
		"aiven_clickhouse_grant":                      12,
		"aiven_clickhouse_role":                       13,
		"aiven_clickhouse_user":                       14,
		"aiven_connection_pool":                       15,
		"aiven_database":                              16,
		"aiven_elasticsearch":                         17,
		"aiven_elasticsearch_acl":                     18,
		"aiven_elasticsearch_acl_config":              19,
		"aiven_elasticsearch_acl_rule":                20,
		"aiven_flink":                                 21,
		"aiven_flink_job":                             22,
		"aiven_flink_table":                           23,
		"aiven_grafana":                               24,
		"aiven_influxdb":                              25,
		"aiven_kafka":                                 26,
		"aiven_kafka_acl":                             27,
		"aiven_kafka_connect":                         28,
		"aiven_kafka_connector":                       29,
		"aiven_kafka_mirrormaker":                     30,
		"aiven_kafka_schema":                          31,
		"aiven_kafka_schema_configuration":            32,
		"aiven_kafka_topic":                           33,
		"aiven_m3aggregator":                          34,
		"aiven_m3db":                                  35,
		"aiven_mirrormaker_replication_flow":          36,
		"aiven_mysql":                                 37,
		"aiven_opensearch":                            38,
		"aiven_opensearch_acl_config":                 39,
		"aiven_opensearch_acl_rule":                   40,
		"aiven_pg":                                    41,
		"aiven_project":                               42,
		"aiven_project_user":                          43,
		"aiven_project_vpc":                           44,
		"aiven_redis":                                 45,
		"aiven_service":                               46,
		"aiven_service_integration":                   47,
		"aiven_service_integration_endpoint":          48,
		"aiven_service_user":                          49,
		"aiven_static_ip":                             50,
		"aiven_transit_gateway_vpc_attachment":        51,
		"aiven_vpc_peering_connection":                52,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
