package prosimo

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "prosimo_app_onboarding_citrixvdi",
			Category:         "Resources",
			ShortDescription: `Use this resource to onboard Citrix VDI Desktop apps.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_app_onboarding_cloudsvc",
			Category:         "Resources",
			ShortDescription: `Use this resource to onboard Cloud Platform Service apps.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_app_onboarding_fqdn",
			Category:         "Resources",
			ShortDescription: `Use this resource to onboard TCP/UDP apps.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_app_onboarding_ip",
			Category:         "Resources",
			ShortDescription: `Use this resource to onboard IP Endpoint apps.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_app_onboarding_jumpbox",
			Category:         "Resources",
			ShortDescription: `Use this resource to onboard Jumpbox apps.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_app_onboarding_web",
			Category:         "Resources",
			ShortDescription: `Use this resource to onboard web apps.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_cache_rules",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify cache rules.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_certificates",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify certficates.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_cloud_creds",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify cloud credentials.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_connector_placement",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify connector placement.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_dp_profile",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify device posture profiles.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_dp_settings",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify device posture settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_dynamic_risk",
			Category:         "Resources",
			ShortDescription: `Use this resource to modify dynamic risk settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_edge",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify edges.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_edr_integration",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify end point security integrations.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_edr_profile",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify Endpoint Security Profiles.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_geo_location",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify geo Velocity settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_grouping",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify resource group settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_idp",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify identity providers.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_ip_addresses",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify ip ranges.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_ip_reputation",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify ip reputation settngs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_log_exporter",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify log exporter settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_network_onboarding",
			Category:         "Resources",
			ShortDescription: `Use this resource to onboard networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_policy",
			Category:         "Resources",
			ShortDescription: `The policy engine in Prosimo helps control access rules between users, applications, and networking. Use this resource to create/modify policies.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_private_link_mapping",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify Private Link Mappings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_private_link_source",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify Private Link Sources.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_service_insertion",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify service insertion policy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_shared_services",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify shared services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_user_settings",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify user settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "prosimo_waf",
			Category:         "Resources",
			ShortDescription: `Use this resource to create/modify waf settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"prosimo_app_onboarding_citrixvdi": 0,
		"prosimo_app_onboarding_cloudsvc":  1,
		"prosimo_app_onboarding_fqdn":      2,
		"prosimo_app_onboarding_ip":        3,
		"prosimo_app_onboarding_jumpbox":   4,
		"prosimo_app_onboarding_web":       5,
		"prosimo_cache_rules":              6,
		"prosimo_certificates":             7,
		"prosimo_cloud_creds":              8,
		"prosimo_connector_placement":      9,
		"prosimo_dp_profile":               10,
		"prosimo_dp_settings":              11,
		"prosimo_dynamic_risk":             12,
		"prosimo_edge":                     13,
		"prosimo_edr_integration":          14,
		"prosimo_edr_profile":              15,
		"prosimo_geo_location":             16,
		"prosimo_grouping":                 17,
		"prosimo_idp":                      18,
		"prosimo_ip_addresses":             19,
		"prosimo_ip_reputation":            20,
		"prosimo_log_exporter":             21,
		"prosimo_network_onboarding":       22,
		"prosimo_policy":                   23,
		"prosimo_private_link_mapping":     24,
		"prosimo_private_link_source":      25,
		"prosimo_service_insertion":        26,
		"prosimo_shared_services":          27,
		"prosimo_user_settings":            28,
		"prosimo_waf":                      29,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
