package boundary

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "boundary_account",
			Category:         "Resources",
			ShortDescription: `Deprecated: use boundary_account_password instead.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_account_ldap",
			Category:         "Resources",
			ShortDescription: `The account resource allows you to configure a Boundary account.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_account_oidc",
			Category:         "Resources",
			ShortDescription: `The account resource allows you to configure a Boundary account.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_account_password",
			Category:         "Resources",
			ShortDescription: `The account resource allows you to configure a Boundary account.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_auth_method",
			Category:         "Resources",
			ShortDescription: `The auth method resource allows you to configure a Boundary auth_method.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_auth_method_ldap",
			Category:         "Resources",
			ShortDescription: `The LDAP auth method resource allows you to configure a Boundary authmethodldap.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_auth_method_oidc",
			Category:         "Resources",
			ShortDescription: `The OIDC auth method resource allows you to configure a Boundary authmethodoidc.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_auth_method_password",
			Category:         "Resources",
			ShortDescription: `The auth method resource allows you to configure a Boundary authmethodpassword.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_credential_json",
			Category:         "Resources",
			ShortDescription: `The json credential resource allows you to congiure a credential using a json object.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_credential_library_vault",
			Category:         "Resources",
			ShortDescription: `The credential library for Vault resource allows you to configure a Boundary credential library for Vault.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_credential_library_vault_ssh_certificate",
			Category:         "Resources",
			ShortDescription: `The credential library for Vault resource allows you to configure a Boundary credential library for Vault.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_credential_ssh_private_key",
			Category:         "Resources",
			ShortDescription: `The SSH private key credential resource allows you to configure a credential using a username, private key and optional passphrase.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_credential_store_static",
			Category:         "Resources",
			ShortDescription: `The static credential store resource allows you to configure a Boundary static credential store.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_credential_store_vault",
			Category:         "Resources",
			ShortDescription: `The credential store for Vault resource allows you to configure a Boundary credential store for Vault.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_credential_username_password",
			Category:         "Resources",
			ShortDescription: `The username/password credential resource allows you to configure a credential using a username and password pair.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_group",
			Category:         "Resources",
			ShortDescription: `The group resource allows you to configure a Boundary group.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host",
			Category:         "Resources",
			ShortDescription: `Deprecated: use boundary_host_static instead.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host_catalog",
			Category:         "Resources",
			ShortDescription: `Deprecated: use boundary_host_catalog_static instead.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host_catalog_plugin",
			Category:         "Resources",
			ShortDescription: `The host catalog resource allows you to configure a Boundary plugin-type host catalog. Host catalogs are always part of a project, so a project resource should be used inline or you should have the project ID in hand to successfully configure a host catalog.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host_catalog_static",
			Category:         "Resources",
			ShortDescription: `The static host catalog resource allows you to configure a Boundary static-type host catalog. Host catalogs are always part of a project, so a project resource should be used inline or you should have the project ID in hand to successfully configure a host catalog.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host_set",
			Category:         "Resources",
			ShortDescription: `Deprecated: use boundary_host_set_static instead.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host_set_plugin",
			Category:         "Resources",
			ShortDescription: `The hostsetplugin resource allows you to configure a Boundary host set. Host sets are always part of a host catalog, so a host catalog resource should be used inline or you should have the host catalog ID in hand to successfully configure a host set.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host_set_static",
			Category:         "Resources",
			ShortDescription: `The hostsetstatic resource allows you to configure a Boundary host set. Host sets are always part of a host catalog, so a host catalog resource should be used inline or you should have the host catalog ID in hand to successfully configure a host set.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_host_static",
			Category:         "Resources",
			ShortDescription: `The static host resource allows you to configure a Boundary static host. Hosts are always part of a project, so a project resource should be used inline or you should have the project ID in hand to successfully configure a host.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_managed_group",
			Category:         "Resources",
			ShortDescription: `The managed group resource allows you to configure a Boundary group.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_managed_group_ldap",
			Category:         "Resources",
			ShortDescription: `The managed group resource allows you to configure a Boundary group.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_role",
			Category:         "Resources",
			ShortDescription: `The role resource allows you to configure a Boundary role.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_scope",
			Category:         "Resources",
			ShortDescription: `The scope resource allows you to configure a Boundary scope.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_target",
			Category:         "Resources",
			ShortDescription: `The target resource allows you to configure a Boundary target.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_user",
			Category:         "Resources",
			ShortDescription: `The user resource allows you to configure a Boundary user.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "boundary_worker",
			Category:         "Resources",
			ShortDescription: `The resource allows you to create a self-managed worker object.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"boundary_account":                                  0,
		"boundary_account_ldap":                             1,
		"boundary_account_oidc":                             2,
		"boundary_account_password":                         3,
		"boundary_auth_method":                              4,
		"boundary_auth_method_ldap":                         5,
		"boundary_auth_method_oidc":                         6,
		"boundary_auth_method_password":                     7,
		"boundary_credential_json":                          8,
		"boundary_credential_library_vault":                 9,
		"boundary_credential_library_vault_ssh_certificate": 10,
		"boundary_credential_ssh_private_key":               11,
		"boundary_credential_store_static":                  12,
		"boundary_credential_store_vault":                   13,
		"boundary_credential_username_password":             14,
		"boundary_group":                                    15,
		"boundary_host":                                     16,
		"boundary_host_catalog":                             17,
		"boundary_host_catalog_plugin":                      18,
		"boundary_host_catalog_static":                      19,
		"boundary_host_set":                                 20,
		"boundary_host_set_plugin":                          21,
		"boundary_host_set_static":                          22,
		"boundary_host_static":                              23,
		"boundary_managed_group":                            24,
		"boundary_managed_group_ldap":                       25,
		"boundary_role":                                     26,
		"boundary_scope":                                    27,
		"boundary_target":                                   28,
		"boundary_user":                                     29,
		"boundary_worker":                                   30,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
