package hpegl

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_cluster",
			Category:         "caas",
			ShortDescription: `Cluster data source allows reading cluster data based on name and space ID. Required inputs are name and space_id`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_cluster_blueprint",
			Category:         "caas",
			ShortDescription: `Cluster Blueprint data source allows reading cluster blueprint data based on blueprint name and space ID. Required inputs are name and space_id`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"cluster",
				"blueprint",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_cluster_provider",
			Category:         "caas",
			ShortDescription: `ClusterProvider data source allows reading Cluster Provider data based on name and site ID. Required inputs are name and site ID`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"cluster",
				"provider",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_machine_blueprint",
			Category:         "caas",
			ShortDescription: `Machine Blueprint data source allows reading machine blueprint data based on blueprint name and appliance ID. Required inputs are name and site_id`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"machine",
				"blueprint",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_site",
			Category:         "caas",
			ShortDescription: `Appliance data source allows reading appliance data based on name and space ID. Required inputs are name and space_id`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"site",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_available_images",
			Category:         "metal",
			ShortDescription: `Provides a list of available Image Services for a project.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"available",
				"images",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_available_resources",
			Category:         "metal",
			ShortDescription: `Provides a list of available resources in a project for creating Hosts and Volumes.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"available",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_usage",
			Category:         "metal",
			ShortDescription: `Get a usage report`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"usage",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_cloud",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaascloud data source can be used to discover the ID of a hpegl vmaas Cloud. This can then be used with resources or data sources that require a hpegl vmaas cloud, such as the hpeglvmaasdatastore data source, hpeglvmaasinstance resource, etc.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"cloud",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_cloud_folder",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaascloudfolder data source can be used to discover the ID for a folder. hpeglvmaascloudfolder can be used along with hpeglvmaasinstance, If it is used, all instances/VMs spawned will be stored in the specified folder.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"cloud",
				"folder",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_datastore",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasdatastore data source can be used to discover the ID of a hpegl vmaas datastore. This can then be used with resources or data sources that require a hpeglvmaasdatastore, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"datastore",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_dhcp_server",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasdhcpserver data source can be used to discover the ID of a hpegl vmaas DHCP server. This can then be used with resources or data sources that require a hpeglvmaasdhcpserver, such as the hpeglvmaasdhcp_server resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"dhcp",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_edge_cluster",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasedgecluster data source can be used to discover the Provider ID of a hpegl vmaas Edge cluster. This can then be used with resources or data sources that require a hpeglvmaasedgecluster`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"edge",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_environment",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasenvironment data source can be used to discover the ID/Code of a hpegl vmaas environment. This can then be used with resources or data sources that require a hpeglvmaasenvironment, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"environment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_group",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasgroup data source can be used to discover the ID of a hpegl vmaas group. This can then be used with resources or data sources that require a hpeglvmaasgroup, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_layout",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaaslayout data source can be used to discover the ID of a hpegl vmaas layout. This can then be used with resources or data sources that require a hpeglvmaaslayout, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"layout",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_lb_pool_member_group",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaaslbpoolmember_group data source can be used to discover the ID of a hpegl vmaas network load balancer. This can then be used for the data sources`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"lb",
				"pool",
				"member",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasloadbalancer data source can be used to discover the ID of a hpegl vmaas network load balancer. This can then be used with resources or data sources that require a hpeglvmaasloadbalancer, such as the hpeglvmaasload_balancer resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_monitor",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasloadbalancermonitor data source can be used to discover the ID of a hpegl vmaas network load balancer. This can then be used with resources or data sources that require a hpeglvmaasloadbalancermonitor, such as the hpeglvmaasloadbalancermonitor resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"monitor",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_pool",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasloadbalancerpool data source can be used to discover the ID of a hpegl vmaas network load balancer. This can then be used with resources or data sources that require a hpeglvmaasloadbalancerpool, such as the hpeglvmaasloadbalancerpool resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_profile",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasloadbalancerprofile data source can be used to discover the ID of a hpegl vmaas network load balancer. This can then be used with resources or data sources`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"profile",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_virtual_server_ssl_cert",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasloadbalancervirtualserverssl_cert data source can be used to discover the ID of a hpegl vmaas network load balancer. This can then be used with resources or data sources`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"virtual",
				"server",
				"ssl",
				"cert",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasnetwork data source can be used to discover the ID of a hpegl vmaas network. This can then be used with resources or data sources that require a hpeglvmaasnetwork, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_domain",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasnetworkdomain data source can be used to discover the ID of an hpeglvmaasnetworkdomain. This can then be used with resources or data sources that require an hpeglvmaasnetworkdomain such as the hpeglvmaas_network`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"network",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_interface",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasnetworkinterface data source can be used to discover the ID of a hpegl vmaas NetworkInterface. This can then be used with resources or data sources that require a hpeglvmaasnetworkinterface, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"network",
				"interface",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_pool",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasnetworkpool data source can be used to discover the ID of a hpegl vmaas network pool. This can then be used with resources or data sources that require a hpeglvmaasnetworkpool, such as the hpeglvmaasnetwork resource (for creating non NSX-T segments).`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"network",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_proxy",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasnetworkproxy data source can be used to discover the ID of an hpeglvmaasnetworkproxy. This can then be used with resources or data sources that require an hpeglvmaasnetworkproxy, such as the hpeglvmaas_network resource (for creating non NSX-T segments).`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"network",
				"proxy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_type",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasnetworktype data source can be used to discover the ID of an hpegl vmaas network types. This can then be used with resources or data sources that require an hpeglvmaasnetworktype, such as the hpeglvmaasnetwork resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"network",
				"type",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_plan",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasplan data source can be used to discover the ID of a hpegl vmaas plan. This can then be used with resources or data sources that require a hpeglvmaasplan, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"plan",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_power_schedule",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaaspowerschedule data source can be used to discover the ID of a hpegl vmaas powerSchedule. This can then be used with resources or data sources that require a hpeglvmaaspowerschedule, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"power",
				"schedule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_resource_pool",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasresourcepool data source can be used to discover the ID of an hpegl vmaas resource pool. This can then be used with resources or data sources that require an hpeglvmaasresourcepool, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"resource",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_router",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaasrouter data source can be used to discover the ID of a hpegl vmaas router. This can then be used with resources or data sources that require a hpeglvmaasrouter, such as the hpeglvmaasrouter resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"router",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_template",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaastemplate data source can be used to discover the ID of a hpegl vmaas template. This can then be used with resources or data sources that require a hpeglvmaastemplate, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"template",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_transport_zone",
			Category:         "vmaas",
			ShortDescription: `The hpeglvmaastransportzone data source can be used to discover the ID of a hpegl vmaas transport zone. This can then be used with resources or data sources that require an hpeglvmaastransportzone`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"transport",
				"zone",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"hpegl_caas_cluster":                                0,
		"hpegl_caas_cluster_blueprint":                      1,
		"hpegl_caas_cluster_provider":                       2,
		"hpegl_caas_machine_blueprint":                      3,
		"hpegl_caas_site":                                   4,
		"hpegl_metal_available_images":                      5,
		"hpegl_metal_available_resources":                   6,
		"hpegl_metal_usage":                                 7,
		"hpegl_vmaas_cloud":                                 8,
		"hpegl_vmaas_cloud_folder":                          9,
		"hpegl_vmaas_datastore":                             10,
		"hpegl_vmaas_dhcp_server":                           11,
		"hpegl_vmaas_edge_cluster":                          12,
		"hpegl_vmaas_environment":                           13,
		"hpegl_vmaas_group":                                 14,
		"hpegl_vmaas_layout":                                15,
		"hpegl_vmaas_lb_pool_member_group":                  16,
		"hpegl_vmaas_load_balancer":                         17,
		"hpegl_vmaas_load_balancer_monitor":                 18,
		"hpegl_vmaas_load_balancer_pool":                    19,
		"hpegl_vmaas_load_balancer_profile":                 20,
		"hpegl_vmaas_load_balancer_virtual_server_ssl_cert": 21,
		"hpegl_vmaas_network":                               22,
		"hpegl_vmaas_network_domain":                        23,
		"hpegl_vmaas_network_interface":                     24,
		"hpegl_vmaas_network_pool":                          25,
		"hpegl_vmaas_network_proxy":                         26,
		"hpegl_vmaas_network_type":                          27,
		"hpegl_vmaas_plan":                                  28,
		"hpegl_vmaas_power_schedule":                        29,
		"hpegl_vmaas_resource_pool":                         30,
		"hpegl_vmaas_router":                                31,
		"hpegl_vmaas_template":                              32,
		"hpegl_vmaas_transport_zone":                        33,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
