package hpegl

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_cloud",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaascloud data source can be used to discover the ID of a hpegl vmaas Cloud. This can then be used with resources or data sources that require a hpegl vmaas cloud, such as the hpeglvmaasdatastore data source, hpeglvmaasinstance resource, etc.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_cloud_folder",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaascloudfolder data source can be used to discover the ID for a folder. hpeglvmaascloudfolder can be used along with hpeglvmaasinstance, if so all instances/VMs spawned will store on the specified folder.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_datastore",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasdatastore data source can be used to discover the ID of a hpegl vmaas datastore. This can then be used with resources or data sources that require a hpeglvmaasdatastore, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_edge_cluster",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasedgecluster data source can be used to discover the Provider ID of a hpegl vmaas Edge cluster. This can then be used with resources or data sources that require a hpeglvmaasedgecluster`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_environment",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasenvironment data source can be used to discover the ID/Code of a hpegl vmaas environment. This can then be used with resources or data sources that require a hpeglvmaasenvironment, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_group",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasgroup data source can be used to discover the ID of a hpegl vmaas group. This can then be used with resources or data sources that require a hpeglvmaasgroup, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_layout",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaaslayout data source can be used to discover the ID of a hpegl vmaas layout. This can then be used with resources or data sources that require a hpeglvmaaslayout, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasnetwork data source can be used to discover the ID of a hpegl vmaas network. This can then be used with resources or data sources that require a hpeglvmaasnetwork, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_domain",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasnetworkdomain data source can be used to discover the ID of a hpeglvmaasnetworkdomain. This can then be used with resources or data sources that require a hpeglvmaasnetworkdomain such as the hpeglvmaas_network`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_interface",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasnetworkinterface data source can be used to discover the ID of a hpegl vmaas NetworkInterface. This can then be used with resources or data sources that require a hpeglvmaasnetworkinterface, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_pool",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasnetworkpool data source can be used to discover the ID of a hpegl vmaas network pool. This can then be used with resources or data sources that require a hpeglvmaasnetworkpool, such as the hpeglvmaasnetwork resource (for creating non NSX-T segments).`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_proxy",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasnetworkproxy data source can be used to discover the ID of a hpeglvmaasnetworkproxy. This can then be used with resources or data sources that require a hpeglvmaasnetworkproxy, such as the hpeglvmaas_network resource (for creating non NSX-T segments).`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network_type",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasnetworktype data source can be used to discover the ID of a hpegl vmaas network types. This can then be used with resources or data sources that require a hpeglvmaasnetworktype, such as the hpeglvmaasnetwork resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_plan",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasplan data source can be used to discover the ID of a hpegl vmaas plan. This can then be used with resources or data sources that require a hpeglvmaasplan, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_power_schedule",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaaspowerschedule data source can be used to discover the ID of a hpegl vmaas powerSchedule. This can then be used with resources or data sources that require a hpeglvmaaspowerschedule, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_resource_pool",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasresourcepool data source can be used to discover the ID of a hpegl vmaas resource pool. This can then be used with resources or data sources that require a hpeglvmaasresourcepool, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_router",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaasrouter data source can be used to discover the ID of a hpegl vmaas router. This can then be used with resources or data sources that require a hpeglvmaasrouter, such as the hpeglvmaasrouter resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_template",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaastemplate data source can be used to discover the ID of a hpegl vmaas template. This can then be used with resources or data sources that require a hpeglvmaastemplate, such as the hpeglvmaasinstance resource.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_transport_zone",
			Category:         "Data Sources",
			ShortDescription: `The hpeglvmaastransportzone data source can be used to discover the ID of a hpegl vmaas transport zone. This can then be used with resources or data sources that require a hpeglvmaastransportzone`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"hpegl_vmaas_cloud":             0,
		"hpegl_vmaas_cloud_folder":      1,
		"hpegl_vmaas_datastore":         2,
		"hpegl_vmaas_edge_cluster":      3,
		"hpegl_vmaas_environment":       4,
		"hpegl_vmaas_group":             5,
		"hpegl_vmaas_layout":            6,
		"hpegl_vmaas_network":           7,
		"hpegl_vmaas_network_domain":    8,
		"hpegl_vmaas_network_interface": 9,
		"hpegl_vmaas_network_pool":      10,
		"hpegl_vmaas_network_proxy":     11,
		"hpegl_vmaas_network_type":      12,
		"hpegl_vmaas_plan":              13,
		"hpegl_vmaas_power_schedule":    14,
		"hpegl_vmaas_resource_pool":     15,
		"hpegl_vmaas_router":            16,
		"hpegl_vmaas_template":          17,
		"hpegl_vmaas_transport_zone":    18,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
