package hpegl

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_cluster",
			Category:         "caas",
			ShortDescription: `The cluster resource facilitates the creation, updation and deletion of a CaaS cluster. There are four required inputs when creating a cluster - name, blueprintid, siteid and spaceid. workernodes is an optional input to scale nodes on cluster. OS Image update & Kubernetes version upgrade are also supported while updating the cluster.`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_cluster_blueprint",
			Category:         "caas",
			ShortDescription: `The cluster blueprint resource facilitates the creation and deletion of a CaaS cluster blueprint. Update is currently not supported. The required inputs when creating a cluster blueprint are name, kubernetesversion, site-id, clusterprovider, controlplane, workernodes and defaultstorageclass`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"cluster",
				"blueprint",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_caas_machine_blueprint",
			Category:         "caas",
			ShortDescription: `The machine blueprint resource facilitates the creation and deletion of a CaaS machine blueprint. Update is currently not supported. The required inputs when creating a cluster blueprint are name, site-id, machineprovider, machineroles, osimage, osversion, computetype, size and storagetype`,
			Description:      ``,
			Keywords: []string{
				"caas",
				"machine",
				"blueprint",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_host",
			Category:         "metal",
			ShortDescription: `Provides Host resource. This allows Metal Host creation, deletion and update.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"host",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_image",
			Category:         "metal",
			ShortDescription: `Provides service image resource. This allows creation, deletion and update of Metal OS service images.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"image",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_ip",
			Category:         "metal",
			ShortDescription: `Provides an IP resource. This allows allocation, deallocation of IP addresses from IP Pool.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"ip",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_network",
			Category:         "metal",
			ShortDescription: `Provides Network resource. This allows creation, deletion and update of Metal networks.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_project",
			Category:         "metal",
			ShortDescription: `Provides Project resource. This allows creation, deletion and update of Metal projects.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"project",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_ssh_key",
			Category:         "metal",
			ShortDescription: `Provides SSH resource. This allows creation, deletion and update of Metal SSHKeys`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"ssh",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_metal_volume",
			Category:         "metal",
			ShortDescription: `Provides Volume resource. This allows creation, deletion and update of Metal volumes.`,
			Description:      ``,
			Keywords: []string{
				"metal",
				"volume",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_dhcp_server",
			Category:         "vmaas",
			ShortDescription: `Server resource facilitates creating, updating and deleting Dhcp Server.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"dhcp",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_instance",
			Category:         "vmaas",
			ShortDescription: `This Instance resource facilitates creating, updating and deleting virtual machines. HPE recommends that you use the VMware as type for provisioning.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"instance",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_instance_clone",
			Category:         "vmaas",
			ShortDescription: `Instance clone resource facilitates creating, updating and deleting cloned virtual machines. For creating an instance clone, provide a unique name and all the Mandatory(Required) parameters. All optional parameters will be inherited from parent resource if not provided.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"instance",
				"clone",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer",
			Category:         "vmaas",
			ShortDescription: `loadbalancer resource facilitates creating, updating and deleting NSX-T Network Load Balancers.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_monitor",
			Category:         "vmaas",
			ShortDescription: `Loadbalancer Monitor resource facilitates creating, updating and deleting NSX-T Network Load Balancer Monitors.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"monitor",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_pool",
			Category:         "vmaas",
			ShortDescription: `loadbalancer Pool resource facilitates creating, updating and deleting NSX-T Network Load Balancer Pools.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"pool",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_profile",
			Category:         "vmaas",
			ShortDescription: `loadbalancer Profile resource facilitates creating, updating and deleting NSX-T Network Load Balancer Profiles.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"profile",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_load_balancer_virtual_server",
			Category:         "vmaas",
			ShortDescription: `loadbalancer Virtual Server resource facilitates creating, updating and deleting NSX-T Network Load Balancer Virtual Servers.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"load",
				"balancer",
				"virtual",
				"server",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_network",
			Category:         "vmaas",
			ShortDescription: `Network resource facilitates creating, updating and deleting NSX-T Networks.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_router",
			Category:         "vmaas",
			ShortDescription: `Router resource facilitates creating, updating and deleting NSX-T Tier0/Tier1 Network Routers.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"router",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_router_bgp_neighbor",
			Category:         "vmaas",
			ShortDescription: `Router Bgp Neighbor resource facilitates creating, updating and deleting NSX-T Network Router BGP Neighbors.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"router",
				"bgp",
				"neighbor",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_router_firewall_rule_group",
			Category:         "vmaas",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"router",
				"firewall",
				"rule",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_router_nat_rule",
			Category:         "vmaas",
			ShortDescription: `Router NAT rule resource facilitates creating, updating and deleting NSX-T Network Router NAT rules.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"router",
				"nat",
				"rule",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "hpegl_vmaas_router_route",
			Category:         "vmaas",
			ShortDescription: `Router route resource facilitates creating, updating and deleting NSX-T Network Router routes.`,
			Description:      ``,
			Keywords: []string{
				"vmaas",
				"router",
				"route",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"hpegl_caas_cluster":                       0,
		"hpegl_caas_cluster_blueprint":             1,
		"hpegl_caas_machine_blueprint":             2,
		"hpegl_metal_host":                         3,
		"hpegl_metal_image":                        4,
		"hpegl_metal_ip":                           5,
		"hpegl_metal_network":                      6,
		"hpegl_metal_project":                      7,
		"hpegl_metal_ssh_key":                      8,
		"hpegl_metal_volume":                       9,
		"hpegl_vmaas_dhcp_server":                  10,
		"hpegl_vmaas_instance":                     11,
		"hpegl_vmaas_instance_clone":               12,
		"hpegl_vmaas_load_balancer":                13,
		"hpegl_vmaas_load_balancer_monitor":        14,
		"hpegl_vmaas_load_balancer_pool":           15,
		"hpegl_vmaas_load_balancer_profile":        16,
		"hpegl_vmaas_load_balancer_virtual_server": 17,
		"hpegl_vmaas_network":                      18,
		"hpegl_vmaas_router":                       19,
		"hpegl_vmaas_router_bgp_neighbor":          20,
		"hpegl_vmaas_router_firewall_rule_group":   21,
		"hpegl_vmaas_router_nat_rule":              22,
		"hpegl_vmaas_router_route":                 23,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
