package ns

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "ns_autogen_subdomain",
			Category:         "Resources",
			ShortDescription: `Resource to configure an autogen subdomain in nullstone.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments: []resource.Attribute{
				resource.Attribute{
					Name:        "dns_name",
					Description: `The random portion of the autogen_subdomain. This is the first part of the fully-qualified domain name (FQDN) that comes before the domain name.`,
				},
				resource.Attribute{
					Name:        "domain_name",
					Description: `The name of the domain that Nullstone administers for this auto-generated subdomain.`,
				},
				resource.Attribute{
					Name:        "fqdn",
					Description: `The fully-qualified domain name (FQDN) for this auto-generated subdomain. It is composed as ` + "`" + `{dns_name}.{domain_name}.` + "`" + `.`,
				},
			},
			Attributes: []resource.Attribute{
				resource.Attribute{
					Name:        "dns_name",
					Description: `The random portion of the autogen_subdomain. This is the first part of the fully-qualified domain name (FQDN) that comes before the domain name.`,
				},
				resource.Attribute{
					Name:        "domain_name",
					Description: `The name of the domain that Nullstone administers for this auto-generated subdomain.`,
				},
				resource.Attribute{
					Name:        "fqdn",
					Description: `The fully-qualified domain name (FQDN) for this auto-generated subdomain. It is composed as ` + "`" + `{dns_name}.{domain_name}.` + "`" + `.`,
				},
			},
		},
		&resource.Resource{
			Name:             "",
			Type:             "ns_autogen_subdomain_delegation",
			Category:         "Resources",
			ShortDescription: `Resource to configure a delegation set for a nullstone autogenerated subdomain.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"ns_autogen_subdomain":            0,
		"ns_autogen_subdomain_delegation": 1,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
