package exoscale

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "exoscale_affinity",
			Category:         "Deprecated",
			ShortDescription: `Fetch Exoscale Anti-Affinity Groups data.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"affinity",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_anti_affinity_group",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Anti-Affinity Groups https://community.exoscale.com/documentation/compute/anti-affinity-groups/ data. Corresponding resource: exoscaleantiaffinity_group ../resources/anti_affinity_group.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_compute",
			Category:         "Deprecated",
			ShortDescription: `Fetch Exoscale Compute Instances data.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"compute",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_compute_instance",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Compute Instances https://community.exoscale.com/documentation/compute/ data. Corresponding resource: exoscalecomputeinstance ../resources/compute_instance.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_compute_instance_list",
			Category:         "Data Sources",
			ShortDescription: `List Exoscale Compute Instances https://community.exoscale.com/documentation/compute/. Corresponding resource: exoscalecomputeinstance ../resources/compute_instance.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_compute_ipaddress",
			Category:         "Deprecated",
			ShortDescription: `Fetch Exoscale Elastic IPs (EIP) data.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"compute",
				"ipaddress",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_compute_template",
			Category:         "Deprecated",
			ShortDescription: `Fetch Exoscale Compute Instance Templates data.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"compute",
				"template",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_domain",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale DNS https://community.exoscale.com/documentation/dns/ Domains data. Corresponding resource: exoscale_domain ../resources/domain.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_domain_record",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale DNS https://community.exoscale.com/documentation/dns/ Domain Records data. Corresponding resource: exoscaledomainrecord ../resources/domain_record.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_elastic_ip",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Elastic IPs (EIP) https://community.exoscale.com/documentation/compute/eip/ data. Corresponding resource: exoscaleelasticip ../resources/elastic_ip.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_instance_pool",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Instance Pools https://community.exoscale.com/documentation/compute/instance-pools/ data. Corresponding resource: exoscaleinstancepool ../resources/instance_pool.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_instance_pool_list",
			Category:         "Data Sources",
			ShortDescription: `List Exoscale Instance Pools https://community.exoscale.com/documentation/compute/instance-pools/. Corresponding resource: exoscaleinstancepool ../resources/instance_pool.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_network",
			Category:         "Deprecated",
			ShortDescription: `Fetch Exoscale Private Networks data.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_nlb",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Network Load Balancers (NLB) https://community.exoscale.com/documentation/compute/network-load-balancer/ data. Corresponding resource: exoscale_nlb ../resources/nlb.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_private_network",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Private Networks https://community.exoscale.com/documentation/compute/private-networks/ data. Corresponding resource: exoscaleprivatenetwork ../resources/private_network.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_security_group",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Security Groups https://community.exoscale.com/documentation/compute/security-groups/ data. Corresponding resource: exoscalesecuritygroup ../resources/security_group.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_sks_cluster",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_sks_cluster_list",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_sks_nodepool",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_sks_nodepool_list",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_template",
			Category:         "Data Sources",
			ShortDescription: `Fetch Exoscale Compute Instance Templates https://community.exoscale.com/documentation/compute/custom-templates/ data.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"exoscale_affinity":              0,
		"exoscale_anti_affinity_group":   1,
		"exoscale_compute":               2,
		"exoscale_compute_instance":      3,
		"exoscale_compute_instance_list": 4,
		"exoscale_compute_ipaddress":     5,
		"exoscale_compute_template":      6,
		"exoscale_domain":                7,
		"exoscale_domain_record":         8,
		"exoscale_elastic_ip":            9,
		"exoscale_instance_pool":         10,
		"exoscale_instance_pool_list":    11,
		"exoscale_network":               12,
		"exoscale_nlb":                   13,
		"exoscale_private_network":       14,
		"exoscale_security_group":        15,
		"exoscale_sks_cluster":           16,
		"exoscale_sks_cluster_list":      17,
		"exoscale_sks_nodepool":          18,
		"exoscale_sks_nodepool_list":     19,
		"exoscale_template":              20,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
