package exoscale

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "exoscale_affinity",
			Category:         "Deprecated",
			ShortDescription: `Manage Exoscale Anti-Affinity Groups.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"affinity",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_anti_affinity_group",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Anti-Affinity Groups https://community.exoscale.com/documentation/compute/anti-affinity-groups/. Corresponding data source: exoscaleantiaffinity_group ../data-sources/anti_affinity_group.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_compute",
			Category:         "Deprecated",
			ShortDescription: `Manage Exoscale Compute Instances.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"compute",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_compute_instance",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Compute Instances https://community.exoscale.com/documentation/compute/. Corresponding data sources: exoscalecomputeinstance ../data-sources/compute_instance.md, exoscalecomputeinstance_list ../data-sources/compute_instance_list.md. After the creation, you can retrieve the password of an instance with Exoscale CLI https://github.com/exoscale/cli: exo compute instance reveal-password NAME.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_database",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Database Services (DBaaS) https://community.exoscale.com/documentation/dbaas/.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_domain",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale DNS Domains.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_domain_record",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale DNS https://community.exoscale.com/documentation/dns/ Domain Records. Corresponding data source: exoscaledomainrecord ../data-sources/domain_record.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_elastic_ip",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Elastic IPs (EIP).`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_iam_access_key",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale IAM Access Keys`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_instance_pool",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Instance Pools https://community.exoscale.com/documentation/compute/instance-pools/. Corresponding data sources: exoscaleinstancepool ../data-sources/instance_pool.md, exoscaleinstancepool_list ../data-sources/instance_pool_list.md.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_ipaddress",
			Category:         "Deprecated",
			ShortDescription: `Manage Exoscale Elastic IPs (EIP).`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"ipaddress",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_network",
			Category:         "Deprecated",
			ShortDescription: `Manage Exoscale Private Networks.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"network",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_nic",
			Category:         "Deprecated",
			ShortDescription: `Manage Exoscale Compute Instance Private Network Interfaces (NIC).`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"nic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_nlb",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Network Load Balancers (NLB).`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_nlb_service",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Network Load Balancer (NLB) https://community.exoscale.com/documentation/compute/network-load-balancer/ Services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_private_network",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Private Networks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_secondary_ipaddress",
			Category:         "Deprecated",
			ShortDescription: `Associate Exoscale Elastic IPs (EIP) to Compute Instances.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"secondary",
				"ipaddress",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_security_group",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Security Groups.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_security_group_rule",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Security Group https://community.exoscale.com/documentation/compute/security-groups/ Rules.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_security_group_rules",
			Category:         "Deprecated",
			ShortDescription: `Manage Exoscale Security Group Rules.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"security",
				"group",
				"rules",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_sks_cluster",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Scalable Kubernetes Service (SKS) https://community.exoscale.com/documentation/sks/ Clusters.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_sks_kubeconfig",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Scalable Kubernetes Service (SKS) Credentials (Kubeconfig).`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_sks_nodepool",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale Scalable Kubernetes Service (SKS) Node Pools.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_ssh_key",
			Category:         "Resources",
			ShortDescription: `Manage Exoscale SSH Keys.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "exoscale_ssh_keypair",
			Category:         "Deprecated",
			ShortDescription: `Manage Exoscale SSH Keypairs.`,
			Description:      ``,
			Keywords: []string{
				"deprecated",
				"ssh",
				"keypair",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"exoscale_affinity":             0,
		"exoscale_anti_affinity_group":  1,
		"exoscale_compute":              2,
		"exoscale_compute_instance":     3,
		"exoscale_database":             4,
		"exoscale_domain":               5,
		"exoscale_domain_record":        6,
		"exoscale_elastic_ip":           7,
		"exoscale_iam_access_key":       8,
		"exoscale_instance_pool":        9,
		"exoscale_ipaddress":            10,
		"exoscale_network":              11,
		"exoscale_nic":                  12,
		"exoscale_nlb":                  13,
		"exoscale_nlb_service":          14,
		"exoscale_private_network":      15,
		"exoscale_secondary_ipaddress":  16,
		"exoscale_security_group":       17,
		"exoscale_security_group_rule":  18,
		"exoscale_security_group_rules": 19,
		"exoscale_sks_cluster":          20,
		"exoscale_sks_kubeconfig":       21,
		"exoscale_sks_nodepool":         22,
		"exoscale_ssh_key":              23,
		"exoscale_ssh_keypair":          24,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
