package alkira

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "alkira_billing_tag",
			Category:         "Resources",
			ShortDescription: `Manage Billing Tag.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_byoip_prefix",
			Category:         "Resources",
			ShortDescription: `Manage BYOIP Prefix.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_cloudvisor_account",
			Category:         "Resources",
			ShortDescription: `Manage CloudVisor Accounts`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_akamai_prolexic",
			Category:         "Resources",
			ShortDescription: `Manage Connector for Akamai Prolexic. (BETA) This resource is still under active development. It may have further changes in the near future. Today, to use this connector, you will need to have onboarded a BYOIP with Do Not Advertise set to true. Also, the segment with public IPs needs to be reported to Akamai Representative.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_aruba_edge",
			Category:         "Resources",
			ShortDescription: `Manage Aruba Edge Connector`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_aws_vpc",
			Category:         "Resources",
			ShortDescription: `Manage AWS Cloud Connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_azure_vnet",
			Category:         "Resources",
			ShortDescription: `Manage Azure Cloud Connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_cisco_sdwan",
			Category:         "Resources",
			ShortDescription: `Manage Cisco SD-WAN Connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_gcp_vpc",
			Category:         "Resources",
			ShortDescription: `Manage GCP Cloud Connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_internet_exit",
			Category:         "Resources",
			ShortDescription: `Manage Internet Exit. An internet exit is an exit from the CXP to theinternet and allows the traffic fromthe various Users & Sites or Cloud Connectors toflow towards the Internet.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_ipsec",
			Category:         "Resources",
			ShortDescription: `Manage IPSec Connector. VPN Mode vpn_mode could be either ROUTE_BASED or POLICY_BASED. When it's defined as ROUTE_BASED, routing_options block is required. When it's defined as POLICY_BASED, policy_options block is required.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_connector_oci_vcn",
			Category:         "Resources",
			ShortDescription: `Manage Oracle Cloud (OCI) Virtual Computing Network (VCN) Cloud Connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_aws_vpc",
			Category:         "Resources",
			ShortDescription: `Manage AWS credential for authentication. The following methods are supported: Static credentialsEnvironment variables Static Credentials: Static credentials can be provided by adding an aws_access_keyand aws_secret_key in-line in the AWS provider block. Environment Variables: You can provide your credentials via enviromental variables: AKAWSACCESSKEYIDAKAWSSECRETACCESSKEYAKAWSROLE_ARNAKAWSROLEEXTERNALID`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_azure_vnet",
			Category:         "Resources",
			ShortDescription: `Credential for interacting with Azure. You could also provide your credentials via the following environmental variables: AKAZUREAPPLICATION_IDAKAZURESUBSCRIPTION_IDAKAZURESECRET_KEYAKAZURETENANT_ID`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_checkpoint",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_cisco_sdwan",
			Category:         "Resources",
			ShortDescription: `Manage Cisco SD-WAN credential for authentication. The following methods are supported: Static credentialsEnvironment variables Static Credentials: Static credentials can be provided by adding an usernameand password in-line in the CISCO SD-WAN block. Environment Variables: You can provide your credentials via the AK_CISCO_SDWAN_USERNAME andAK_CISCO_SDWAN_PASSWORD, environment variables, representing yourCisco SD-WAN username and password, respectively.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_fortinet",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_fortinet_instance",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_gcp_vpc",
			Category:         "Resources",
			ShortDescription: `Manage Credential for GCP.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_oci_vcn",
			Category:         "Resources",
			ShortDescription: `Credential for accessing Oracle Cloud. You can provide your credentials via the following enviromental variables: AKOCIUSER_OCIDAKOCIFINGERPRINTAKOCIKEYAKOCITENANT_OCID`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_pan",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_credential_pan_instance",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_group",
			Category:         "Resources",
			ShortDescription: `Manage groups Groups can contain one or many connectors across different segments. This grouping of connectors can be for policy enforcement purposes or for monitoring purposes within the network. It allows for easier policy assignment by assigning policies to the entire group at the same time instead of having to assign them individually.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_group_connector",
			Category:         "Resources",
			ShortDescription: `Manage connector groups Connector Groups can contain one or many connectors across different segments. This grouping of connectors can be for policy enforcement purposes or for monitoring purposes within the network. It allows for easier policy assignment by assigning policies to the entire group at the same time instead of having to assign them individually.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_group_user",
			Category:         "Resources",
			ShortDescription: `Manage user groups`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_internet_application",
			Category:         "Resources",
			ShortDescription: `Manage Internet Application. The internet facing applications could be used with bothUsers & Sites or Cloud Connectors.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_list_as_path",
			Category:         "Resources",
			ShortDescription: `This list could be used in a policy rule, a route will match successfully if any one value from the list is included within the AS-PATH of the route.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_list_community",
			Category:         "Resources",
			ShortDescription: `This list could be used to matches a route when all values in the list are present on the route. A route matches a list when any of the values match.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_list_extended_community",
			Category:         "Resources",
			ShortDescription: `An extended community list matches a route when all values in the list are present on the route. A route matches an extended community list when any of the values match.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_list_global_cidr",
			Category:         "Resources",
			ShortDescription: `A list of CIDRs to be used for services.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_policy",
			Category:         "Resources",
			ShortDescription: `Manage policy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_policy_nat",
			Category:         "Resources",
			ShortDescription: `Manage NAT policy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_policy_nat_rule",
			Category:         "Resources",
			ShortDescription: `Manage policy NAT rule. This resource is usually used along with policy resources:policy_nat_policy.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_policy_prefix_list",
			Category:         "Resources",
			ShortDescription: `Manage policy prefix list.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_policy_rule",
			Category:         "Resources",
			ShortDescription: `Manage policy rule. This resource is usually used along with policy resources:policy_prefix_list, policy_rule_list and policycontrol the network traffic.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_policy_rule_list",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_segment",
			Category:         "Resources",
			ShortDescription: `This resource manages segments. A Segment is a section of a network isolated from one anotherto make it possible to more effectively control who has accessto what. Segmentation also allows for segregation of resourcesbetween segments for security and isolation purposes.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_segment_resource",
			Category:         "Resources",
			ShortDescription: `Manage segment resource To use this resource, you will need to use or create alkira_group, alkira_segment and alkira_policy_prefix_list. There could be multiple group_prefix section defined as needed. The group_prefix should be defined like this: ANY -> ANY: where group_id must be -1 and prefixlistid must be -1. When an ANY -> ANY mapping is present then it should be the only mapping in the group_prefixEXPLICIT Group -> ANY: where group_id must be the ID of group of type EXPLICIT and prefixlistid MUST be -1.IMPLICIT Group -> ANY: where group_id must be the ID of group of type IMPLICIT, this is also known as a Connector Group and prefix_list_id must be -1. If an IMPLICIT group is mapped to ANY prefix_list_id, then an IMPLICIT Group -> prefix_list_id must NOT be present in group_prefixIMPLICIT Group -> PrefixList ID: where group_id must be the ID of group of type IMPLICIT and prefix_list_id MUST be the ID of an existing prefix_list_idSERVICE Group -> ANY: where group_id must be the ID of group of type SERVICE and prefix_list_id MUST be -1.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_segment_resource_share",
			Category:         "Resources",
			ShortDescription: `Manages segment resource share. Select resources to share between Resource End-A in a segment and Resource End-B in another segment.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_service_checkpoint",
			Category:         "Resources",
			ShortDescription: `Manage checkpoint services`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_service_fortinet",
			Category:         "Resources",
			ShortDescription: `Manage Fortinet firewall.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_service_pan",
			Category:         "Resources",
			ShortDescription: `Manage PAN firewall.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_service_zscaler",
			Category:         "Resources",
			ShortDescription: `Manage Zscaler firewall.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "alkira_tenant_network",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"alkira_billing_tag":                  0,
		"alkira_byoip_prefix":                 1,
		"alkira_cloudvisor_account":           2,
		"alkira_connector_akamai_prolexic":    3,
		"alkira_connector_aruba_edge":         4,
		"alkira_connector_aws_vpc":            5,
		"alkira_connector_azure_vnet":         6,
		"alkira_connector_cisco_sdwan":        7,
		"alkira_connector_gcp_vpc":            8,
		"alkira_connector_internet_exit":      9,
		"alkira_connector_ipsec":              10,
		"alkira_connector_oci_vcn":            11,
		"alkira_credential_aws_vpc":           12,
		"alkira_credential_azure_vnet":        13,
		"alkira_credential_checkpoint":        14,
		"alkira_credential_cisco_sdwan":       15,
		"alkira_credential_fortinet":          16,
		"alkira_credential_fortinet_instance": 17,
		"alkira_credential_gcp_vpc":           18,
		"alkira_credential_oci_vcn":           19,
		"alkira_credential_pan":               20,
		"alkira_credential_pan_instance":      21,
		"alkira_group":                        22,
		"alkira_group_connector":              23,
		"alkira_group_user":                   24,
		"alkira_internet_application":         25,
		"alkira_list_as_path":                 26,
		"alkira_list_community":               27,
		"alkira_list_extended_community":      28,
		"alkira_list_global_cidr":             29,
		"alkira_policy":                       30,
		"alkira_policy_nat":                   31,
		"alkira_policy_nat_rule":              32,
		"alkira_policy_prefix_list":           33,
		"alkira_policy_rule":                  34,
		"alkira_policy_rule_list":             35,
		"alkira_segment":                      36,
		"alkira_segment_resource":             37,
		"alkira_segment_resource_share":       38,
		"alkira_service_checkpoint":           39,
		"alkira_service_fortinet":             40,
		"alkira_service_pan":                  41,
		"alkira_service_zscaler":              42,
		"alkira_tenant_network":               43,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
