package genesyscloud

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_datatable",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Architect Datatables. Select an architect datatable by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_emergencygroup",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Emergency Groups. Select an emergency group by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_ivr",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud IVRs. Select an IVR by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_schedulegroups",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Schedule Groups. Select a schedule group by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_schedules",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Schedule. Select a schedule by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_user_prompt",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud User Prompts. Select a user prompt by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_division",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Divisions. Select a division by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_division_home",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Divisions. Get the Home division`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_role",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Roles. Select a role by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_employeeperformance_externalmetrics_definitions",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Employeeperformance Externalmetrics Definition. Select a Employeeperformance Externalmetrics Definition by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_externalcontacts_contact",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud external contacts. Select a contact by any string search.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_flow",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Flows. Select a flow by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_flow_milestone",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Flow Milestone. Select a milestone by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_flow_outcome",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Flow Outcome. Select an outcome by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_group",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Groups. Select a group by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud integration. Select an integration by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_action",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud integration action. Select an integration action by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_credential",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud integration credential. Select an integration credential by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_action_map",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Action Map. Select a journey action map by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_action_template",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Action Template. Select a journey action template by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_outcome",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Journey Outcome. Select a journey outcome by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_segment",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Journey Segment. Select a journey segment by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_category",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Knowledge Base Category. Select a category by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_knowledgebase",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Knowledge Base. Select a knowledge base by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_label",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Knowledge Base Label. Select a label by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_location",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Location. Select a location by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_oauth_client",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud OAuth Clients. Select an OAuth Client by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_organizations_me",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud current organization`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_attempt_limit",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Attempt Limits. Select an attempt limit by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_callabletimeset",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Clound Outbound Callable Timesets. Select a callable timeset by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_callanalysisresponseset",
			Category:         "Data Sources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_campaign",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Campaign. Select a Outbound Campaign by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_campaignrule",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Campaign Rules. Select a campaign rule by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_contact_list",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Contact Lists. Select a contact list by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_contactlistfilter",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Contact List Filters. Select a contact list filter by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_dnclist",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound DNC Lists. Select a DNC list by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_messagingcampaign",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Messaging Campaign. Select a Outbound Messaging Campaign by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_ruleset",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Ruleset. Select an Outbound Ruleset by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_sequence",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Outbound Sequence. Select a Outbound Sequence by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_processautomation_trigger",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud process automation trigger. Select a trigger by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_quality_forms_evaluation",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Evaluation Forms. Select an evaluations form by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_quality_forms_survey",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud survey form. Select a form by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_recording_media_retention_policy",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud media retention policy. Select a policy by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_responsemanagement_library",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Responsemanagement Library. Select a Responsemanagement Library by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_responsemanagement_response",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Responsemanagement Response. Select a Responsemanagement Response by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_responsemanagement_responseasset",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Response Management Response Assets. Select a response asset by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_email_domain",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Email Domains. Select an email domain by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_language",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Languages. Select a language by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_queue",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Queues. Select a queue by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_settings",
			Category:         "Data Sources",
			ShortDescription: `An organization's routing settings`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_skill",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Skills. Select a skill by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_skill_group",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Skills Groups. Select a skill group by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_sms_address",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Sms Address. Select a Routing Sms Address by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_wrapupcode",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Wrap-up Code. Select a wrap-up code by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_script",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Scripts. Select a script by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_station",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Stations. Select a station by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_did",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud DID. The identifier is the E-164 phone number.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_did_pool",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud DID pool. Select a DID pool by starting phone number and ending phone number`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_edge_group",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Edge Group. Select an edge group by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_extension_pool",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Extension pool. Select an Extension pool by starting number and ending number`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_linebasesettings",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Line Base Settings. Select a line base settings by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_phone",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Phone. Select a phone by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_phonebasesettings",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Phone Base Settings. Select a phone base settings by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_site",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Sites. Select a site by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_trunk",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Trunk. Select a trunk by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_trunkbasesettings",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Trunk Base Settings. Select a trunk base settings by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_user",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Users. Select a user by email or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_webdeployments_configuration",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Web Deployments Configurations. Select a configuration by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_webdeployments_deployment",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Web Deployments. Select a deployment by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_widget_deployment",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Widget Deployment. Select a widget deployment.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"genesyscloud_architect_datatable":                             0,
		"genesyscloud_architect_emergencygroup":                        1,
		"genesyscloud_architect_ivr":                                   2,
		"genesyscloud_architect_schedulegroups":                        3,
		"genesyscloud_architect_schedules":                             4,
		"genesyscloud_architect_user_prompt":                           5,
		"genesyscloud_auth_division":                                   6,
		"genesyscloud_auth_division_home":                              7,
		"genesyscloud_auth_role":                                       8,
		"genesyscloud_employeeperformance_externalmetrics_definitions": 9,
		"genesyscloud_externalcontacts_contact":                        10,
		"genesyscloud_flow":                                            11,
		"genesyscloud_flow_milestone":                                  12,
		"genesyscloud_flow_outcome":                                    13,
		"genesyscloud_group":                                           14,
		"genesyscloud_integration":                                     15,
		"genesyscloud_integration_action":                              16,
		"genesyscloud_integration_credential":                          17,
		"genesyscloud_journey_action_map":                              18,
		"genesyscloud_journey_action_template":                         19,
		"genesyscloud_journey_outcome":                                 20,
		"genesyscloud_journey_segment":                                 21,
		"genesyscloud_knowledge_category":                              22,
		"genesyscloud_knowledge_knowledgebase":                         23,
		"genesyscloud_knowledge_label":                                 24,
		"genesyscloud_location":                                        25,
		"genesyscloud_oauth_client":                                    26,
		"genesyscloud_organizations_me":                                27,
		"genesyscloud_outbound_attempt_limit":                          28,
		"genesyscloud_outbound_callabletimeset":                        29,
		"genesyscloud_outbound_callanalysisresponseset":                30,
		"genesyscloud_outbound_campaign":                               31,
		"genesyscloud_outbound_campaignrule":                           32,
		"genesyscloud_outbound_contact_list":                           33,
		"genesyscloud_outbound_contactlistfilter":                      34,
		"genesyscloud_outbound_dnclist":                                35,
		"genesyscloud_outbound_messagingcampaign":                      36,
		"genesyscloud_outbound_ruleset":                                37,
		"genesyscloud_outbound_sequence":                               38,
		"genesyscloud_processautomation_trigger":                       39,
		"genesyscloud_quality_forms_evaluation":                        40,
		"genesyscloud_quality_forms_survey":                            41,
		"genesyscloud_recording_media_retention_policy":                42,
		"genesyscloud_responsemanagement_library":                      43,
		"genesyscloud_responsemanagement_response":                     44,
		"genesyscloud_responsemanagement_responseasset":                45,
		"genesyscloud_routing_email_domain":                            46,
		"genesyscloud_routing_language":                                47,
		"genesyscloud_routing_queue":                                   48,
		"genesyscloud_routing_settings":                                49,
		"genesyscloud_routing_skill":                                   50,
		"genesyscloud_routing_skill_group":                             51,
		"genesyscloud_routing_sms_address":                             52,
		"genesyscloud_routing_wrapupcode":                              53,
		"genesyscloud_script":                                          54,
		"genesyscloud_station":                                         55,
		"genesyscloud_telephony_providers_edges_did":                   56,
		"genesyscloud_telephony_providers_edges_did_pool":              57,
		"genesyscloud_telephony_providers_edges_edge_group":            58,
		"genesyscloud_telephony_providers_edges_extension_pool":        59,
		"genesyscloud_telephony_providers_edges_linebasesettings":      60,
		"genesyscloud_telephony_providers_edges_phone":                 61,
		"genesyscloud_telephony_providers_edges_phonebasesettings":     62,
		"genesyscloud_telephony_providers_edges_site":                  63,
		"genesyscloud_telephony_providers_edges_trunk":                 64,
		"genesyscloud_telephony_providers_edges_trunkbasesettings":     65,
		"genesyscloud_user":                                            66,
		"genesyscloud_webdeployments_configuration":                    67,
		"genesyscloud_webdeployments_deployment":                       68,
		"genesyscloud_widget_deployment":                               69,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
