package genesyscloud

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_datatable",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Architect Datatables. Select an architect datatable by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_emergencygroup",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Emergency Groups. Select an emergency group by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_ivr",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud IVRs. Select an IVR by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_schedulegroups",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Schedule Groups. Select a schedule group by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_schedules",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Schedule. Select a schedule by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_user_prompt",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud User Prompts. Select a user prompt by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_division",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Divisions. Select a division by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_division_home",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Divisions. Get the Home division`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_role",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Roles. Select a role by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_flow",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Flows. Select a flow by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_group",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Groups. Select a group by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud integration. Select an integration by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_action",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud integration action. Select an integration action by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_credential",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud integration credential. Select an integration credential by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_location",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Location. Select a location by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_oauth_client",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud OAuth Clients. Select an OAuth Client by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_organizations_me",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud current organization`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_processautomation_trigger",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud process automation trigger. Select a trigger by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_quality_forms_evaluation",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Evaluation Forms. Select an evaluations form by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_email_domain",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Email Domains. Select an email domain by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_language",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Languages. Select a language by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_queue",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Queues. Select a queue by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_skill",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Routing Skills. Select a skill by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_wrapupcode",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Wrap-up Code. Select a wrap-up code by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_script",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Scripts. Select a script by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_station",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Stations. Select a station by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_did",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud DID. The identifier is the E-164 phone number.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_did_pool",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud DID pool. Select a DID pool by starting phone number and ending phone number`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_edge_group",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Edge Group. Select an edge group by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_extension_pool",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Extension pool. Select an Extension pool by starting number and ending number`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_linebasesettings",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Line Base Settings. Select a line base settings by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_phone",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Phone. Select a phone by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_phonebasesettings",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Phone Base Settings. Select a phone base settings by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_site",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Sites. Select a site by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_trunk",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Trunk. Select a trunk by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_trunkbasesettings",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Trunk Base Settings. Select a trunk base settings by name`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_user",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Users. Select a user by email or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_webdeployments_configuration",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Web Deployments Configurations. Select a configuration by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_webdeployments_deployment",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Web Deployments. Select a deployment by name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_widget_deployment",
			Category:         "Data Sources",
			ShortDescription: `Data source for Genesys Cloud Widget Deployment. Select a widget deployment.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"genesyscloud_architect_datatable":                         0,
		"genesyscloud_architect_emergencygroup":                    1,
		"genesyscloud_architect_ivr":                               2,
		"genesyscloud_architect_schedulegroups":                    3,
		"genesyscloud_architect_schedules":                         4,
		"genesyscloud_architect_user_prompt":                       5,
		"genesyscloud_auth_division":                               6,
		"genesyscloud_auth_division_home":                          7,
		"genesyscloud_auth_role":                                   8,
		"genesyscloud_flow":                                        9,
		"genesyscloud_group":                                       10,
		"genesyscloud_integration":                                 11,
		"genesyscloud_integration_action":                          12,
		"genesyscloud_integration_credential":                      13,
		"genesyscloud_location":                                    14,
		"genesyscloud_oauth_client":                                15,
		"genesyscloud_organizations_me":                            16,
		"genesyscloud_processautomation_trigger":                   17,
		"genesyscloud_quality_forms_evaluation":                    18,
		"genesyscloud_routing_email_domain":                        19,
		"genesyscloud_routing_language":                            20,
		"genesyscloud_routing_queue":                               21,
		"genesyscloud_routing_skill":                               22,
		"genesyscloud_routing_wrapupcode":                          23,
		"genesyscloud_script":                                      24,
		"genesyscloud_station":                                     25,
		"genesyscloud_telephony_providers_edges_did":               26,
		"genesyscloud_telephony_providers_edges_did_pool":          27,
		"genesyscloud_telephony_providers_edges_edge_group":        28,
		"genesyscloud_telephony_providers_edges_extension_pool":    29,
		"genesyscloud_telephony_providers_edges_linebasesettings":  30,
		"genesyscloud_telephony_providers_edges_phone":             31,
		"genesyscloud_telephony_providers_edges_phonebasesettings": 32,
		"genesyscloud_telephony_providers_edges_site":              33,
		"genesyscloud_telephony_providers_edges_trunk":             34,
		"genesyscloud_telephony_providers_edges_trunkbasesettings": 35,
		"genesyscloud_user":                                        36,
		"genesyscloud_webdeployments_configuration":                37,
		"genesyscloud_webdeployments_deployment":                   38,
		"genesyscloud_widget_deployment":                           39,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
