package genesyscloud

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_datatable",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Architect Datatables`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_datatable_row",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Architect Datatable Row`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_division",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Authorization Division`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_role",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Authorization Role`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_group",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Directory Group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_group_roles",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Group Roles maintains group role assignments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_adfs",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on ADFS Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-microsoft-adfs-single-sign-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_generic",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Generic Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-a-generic-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_gsuite",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on GSuite Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-google-g-suite-single-sign-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_okta",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Okta Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-okta-as-a-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_onelogin",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on OneLogin Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-onelogin-as-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_ping",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Ping Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-ping-identity-single-sign-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_salesforce",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Salesforce Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-salesforce-as-a-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Integration`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_action",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Integration Actions. See this page for detailed information on configuring Actions: https://help.mypurecloud.com/articles/add-configuration-custom-actions-integrations/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_credential",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Credential`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_location",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Location`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_oauth_client",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud OAuth Clients. See this page for detailed configuration information: https://help.mypurecloud.com/articles/create-an-oauth-client/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_email_domain",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Email Domain`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_email_route",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Email Domain Route`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_language",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Language`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_queue",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Queue`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_skill",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Skill`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_utilization",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Org-wide Routing Utilization Settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_wrapupcode",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Wrapup Code`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_did_pool",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud DID Pool`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_phone",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Phone`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_trunkbasesettings",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Trunk Base Settings`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_tf_export",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Resource to export Terraform config and (optionally) tfstate files to a local directory. The config file is named 'genesyscloud.tf.json', and the state file is named 'terraform.tfstate'.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_user",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud User`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_user_roles",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud User Roles maintains user role assignments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"genesyscloud_architect_datatable":                         0,
		"genesyscloud_architect_datatable_row":                     1,
		"genesyscloud_auth_division":                               2,
		"genesyscloud_auth_role":                                   3,
		"genesyscloud_group":                                       4,
		"genesyscloud_group_roles":                                 5,
		"genesyscloud_idp_adfs":                                    6,
		"genesyscloud_idp_generic":                                 7,
		"genesyscloud_idp_gsuite":                                  8,
		"genesyscloud_idp_okta":                                    9,
		"genesyscloud_idp_onelogin":                                10,
		"genesyscloud_idp_ping":                                    11,
		"genesyscloud_idp_salesforce":                              12,
		"genesyscloud_integration":                                 13,
		"genesyscloud_integration_action":                          14,
		"genesyscloud_integration_credential":                      15,
		"genesyscloud_location":                                    16,
		"genesyscloud_oauth_client":                                17,
		"genesyscloud_routing_email_domain":                        18,
		"genesyscloud_routing_email_route":                         19,
		"genesyscloud_routing_language":                            20,
		"genesyscloud_routing_queue":                               21,
		"genesyscloud_routing_skill":                               22,
		"genesyscloud_routing_utilization":                         23,
		"genesyscloud_routing_wrapupcode":                          24,
		"genesyscloud_telephony_did_pool":                          25,
		"genesyscloud_telephony_providers_edges_phone":             26,
		"genesyscloud_telephony_providers_edges_trunkbasesettings": 27,
		"genesyscloud_tf_export":                                   28,
		"genesyscloud_user":                                        29,
		"genesyscloud_user_roles":                                  30,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
