package genesyscloud

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_datatable",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Architect Datatables`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_datatable_row",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Architect Datatable Row`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_emergencygroup",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Architect Emergency Group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_ivr",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud IVR config`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_schedulegroups",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Architect Schedule Groups`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_schedules",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Architect Schedules`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_architect_user_prompt",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud User Audio Prompt`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_division",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Authorization Division`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_auth_role",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Authorization Role`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_employeeperformance_externalmetrics_definitions",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud employeeperformance externalmetrics definition`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_externalcontacts_contact",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud External Contact`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_flow",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Flow`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_flow_milestone",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud flow milestone`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_flow_outcome",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud flow outcome`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_group",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Directory Group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_group_roles",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Group Roles maintains group role assignments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_adfs",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on ADFS Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-microsoft-adfs-single-sign-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_generic",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Generic Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-a-generic-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_gsuite",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on GSuite Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-google-g-suite-single-sign-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_okta",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Okta Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-okta-as-a-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_onelogin",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on OneLogin Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-onelogin-as-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_ping",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Ping Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-ping-identity-single-sign-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_idp_salesforce",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Single Sign-on Salesforce Identity Provider. See this page for detailed configuration instructions: https://help.mypurecloud.com/articles/add-salesforce-as-a-single-sign-on-provider/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Integration`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_action",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Integration Actions. See this page for detailed information on configuring Actions: https://help.mypurecloud.com/articles/add-configuration-custom-actions-integrations/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_integration_credential",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Credential`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_action_map",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Journey Action Map`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_action_template",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Journey Action Template`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_outcome",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Journey Outcome`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_journey_segment",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Journey Segment`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_category",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Knowledge Category`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_document",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Knowledge document`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_document_variation",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Knowledge Document Variation`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_knowledgebase",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Knowledge Base`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_label",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Knowledge Label`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_v1_category",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Knowledge v1 Category`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_knowledge_v1_document",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Knowledge document`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_location",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Location`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_oauth_client",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud OAuth Clients. See this page for detailed configuration information: https://help.mypurecloud.com/articles/create-an-oauth-client/`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_orgauthorization_pairing",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud orgauthorization pairing`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_attempt_limit",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Outbound Attempt Limit`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_callabletimeset",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud outbound callabletimeset`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_callanalysisresponseset",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud outbound Call Analysis Response Set`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_campaign",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud outbound campaign`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_campaignrule",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud outbound campaign rule`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_contact_list",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Outbound Contact List`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_contactlistfilter",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Outbound Contact List Filter`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_dnclist",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Outbound DNC List`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_messagingcampaign",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Outbound Messaging Campaign`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_ruleset",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud outbound ruleset`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_sequence",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud outbound sequence`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_settings",
			Category:         "Resources",
			ShortDescription: `An organization's outbound settings`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_outbound_wrapupcodemappings",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Outbound Wrap-up Code Mappings`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_processautomation_trigger",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Process Automation Trigger NOTE: This component is currently in beta. If you wish to use this provider make sure your client has the correct permissions`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_quality_forms_evaluation",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Evaluation Forms`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_quality_forms_survey",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Survey Forms`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_recording_media_retention_policy",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Media Retention Policies`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_responsemanagement_library",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud responsemanagement library`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_responsemanagement_response",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud responsemanagement response`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_responsemanagement_responseasset",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud responsemanagement response asset`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_email_domain",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Email Domain`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_email_route",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Email Domain Route`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_language",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Language`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_queue",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Queue`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_settings",
			Category:         "Resources",
			ShortDescription: `An organization's routing settings`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_skill",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Skill`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_skill_group",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Skill Group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_sms_address",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud routing sms address`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_utilization",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Org-wide Routing Utilization Settings.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_routing_wrapupcode",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Routing Wrapup Code`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_script",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Script`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_did_pool",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud DID Pool`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_edge_group",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Edge Group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_extension_pool",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Extension Pool`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_phone",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Phone`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_phonebasesettings",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Phone Base Settings`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_site",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Site`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_trunk",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Trunk. Created by assigning a trunk base settings to an edge or edge group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_telephony_providers_edges_trunkbasesettings",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Trunk Base Settings`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_tf_export",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Resource to export Terraform config and (optionally) tfstate files to a local directory. The config file is named 'genesyscloud.tf.json' or 'genesyscloud.tf', and the state file is named 'terraform.tfstate'.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_user",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud User`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_user_roles",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud User Roles maintains user role assignments. Terraform expects to manage the resources that are defined in its stack. You can use this resource to assign roles to existing users that are not managed by Terraform. However, one thing you have to remember is that when you use this resource to assign roles to existing users, you must define all roles assigned to those users in this resource. Otherwise, you will inadvertently drop all of the existing roles assigned to the user and replace them with the one defined in this resource. Keep this in mind, as the author of this note inadvertently stripped his Genesys admin account of administrator privileges while using this resource to assign a role to his account. The best lessons in life are often free and self-inflicted.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_webdeployments_configuration",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Web Deployment Configuration`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_webdeployments_deployment",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Web Deployment`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "genesyscloud_widget_deployment",
			Category:         "Resources",
			ShortDescription: `Genesys Cloud Widget Deployment`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"genesyscloud_architect_datatable":                             0,
		"genesyscloud_architect_datatable_row":                         1,
		"genesyscloud_architect_emergencygroup":                        2,
		"genesyscloud_architect_ivr":                                   3,
		"genesyscloud_architect_schedulegroups":                        4,
		"genesyscloud_architect_schedules":                             5,
		"genesyscloud_architect_user_prompt":                           6,
		"genesyscloud_auth_division":                                   7,
		"genesyscloud_auth_role":                                       8,
		"genesyscloud_employeeperformance_externalmetrics_definitions": 9,
		"genesyscloud_externalcontacts_contact":                        10,
		"genesyscloud_flow":                                            11,
		"genesyscloud_flow_milestone":                                  12,
		"genesyscloud_flow_outcome":                                    13,
		"genesyscloud_group":                                           14,
		"genesyscloud_group_roles":                                     15,
		"genesyscloud_idp_adfs":                                        16,
		"genesyscloud_idp_generic":                                     17,
		"genesyscloud_idp_gsuite":                                      18,
		"genesyscloud_idp_okta":                                        19,
		"genesyscloud_idp_onelogin":                                    20,
		"genesyscloud_idp_ping":                                        21,
		"genesyscloud_idp_salesforce":                                  22,
		"genesyscloud_integration":                                     23,
		"genesyscloud_integration_action":                              24,
		"genesyscloud_integration_credential":                          25,
		"genesyscloud_journey_action_map":                              26,
		"genesyscloud_journey_action_template":                         27,
		"genesyscloud_journey_outcome":                                 28,
		"genesyscloud_journey_segment":                                 29,
		"genesyscloud_knowledge_category":                              30,
		"genesyscloud_knowledge_document":                              31,
		"genesyscloud_knowledge_document_variation":                    32,
		"genesyscloud_knowledge_knowledgebase":                         33,
		"genesyscloud_knowledge_label":                                 34,
		"genesyscloud_knowledge_v1_category":                           35,
		"genesyscloud_knowledge_v1_document":                           36,
		"genesyscloud_location":                                        37,
		"genesyscloud_oauth_client":                                    38,
		"genesyscloud_orgauthorization_pairing":                        39,
		"genesyscloud_outbound_attempt_limit":                          40,
		"genesyscloud_outbound_callabletimeset":                        41,
		"genesyscloud_outbound_callanalysisresponseset":                42,
		"genesyscloud_outbound_campaign":                               43,
		"genesyscloud_outbound_campaignrule":                           44,
		"genesyscloud_outbound_contact_list":                           45,
		"genesyscloud_outbound_contactlistfilter":                      46,
		"genesyscloud_outbound_dnclist":                                47,
		"genesyscloud_outbound_messagingcampaign":                      48,
		"genesyscloud_outbound_ruleset":                                49,
		"genesyscloud_outbound_sequence":                               50,
		"genesyscloud_outbound_settings":                               51,
		"genesyscloud_outbound_wrapupcodemappings":                     52,
		"genesyscloud_processautomation_trigger":                       53,
		"genesyscloud_quality_forms_evaluation":                        54,
		"genesyscloud_quality_forms_survey":                            55,
		"genesyscloud_recording_media_retention_policy":                56,
		"genesyscloud_responsemanagement_library":                      57,
		"genesyscloud_responsemanagement_response":                     58,
		"genesyscloud_responsemanagement_responseasset":                59,
		"genesyscloud_routing_email_domain":                            60,
		"genesyscloud_routing_email_route":                             61,
		"genesyscloud_routing_language":                                62,
		"genesyscloud_routing_queue":                                   63,
		"genesyscloud_routing_settings":                                64,
		"genesyscloud_routing_skill":                                   65,
		"genesyscloud_routing_skill_group":                             66,
		"genesyscloud_routing_sms_address":                             67,
		"genesyscloud_routing_utilization":                             68,
		"genesyscloud_routing_wrapupcode":                              69,
		"genesyscloud_script":                                          70,
		"genesyscloud_telephony_providers_edges_did_pool":              71,
		"genesyscloud_telephony_providers_edges_edge_group":            72,
		"genesyscloud_telephony_providers_edges_extension_pool":        73,
		"genesyscloud_telephony_providers_edges_phone":                 74,
		"genesyscloud_telephony_providers_edges_phonebasesettings":     75,
		"genesyscloud_telephony_providers_edges_site":                  76,
		"genesyscloud_telephony_providers_edges_trunk":                 77,
		"genesyscloud_telephony_providers_edges_trunkbasesettings":     78,
		"genesyscloud_tf_export":                                       79,
		"genesyscloud_user":                                            80,
		"genesyscloud_user_roles":                                      81,
		"genesyscloud_webdeployments_configuration":                    82,
		"genesyscloud_webdeployments_deployment":                       83,
		"genesyscloud_widget_deployment":                               84,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
