package packetfabric

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_backbone_virtual_circuit",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_backbone_virtual_circuit_marketplace",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_backbone_virtual_circuit_speed_burst",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_provider_credential_aws",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_provider_credential_google",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_bgp_session",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_connection_aws",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_connection_azure",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_connection_google",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_connection_ibm",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_connection_ipsec",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_connection_oracle",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_connection_port",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cloud_router_quick_connect",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_aws_dedicated_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_aws_hosted_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_aws_hosted_marketplace_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_azure_dedicated_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_azure_hosted_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_azure_hosted_marketplace_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_google_dedicated_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_google_hosted_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_google_hosted_marketplace_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_ibm_hosted_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_oracle_hosted_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_cs_oracle_hosted_marketplace_connection",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_document",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_flex_bandwidth",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_ix_virtual_circuit_marketplace",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_link_aggregation_group",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_marketplace_service",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_marketplace_service_port_accept_request",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_marketplace_service_port_reject_request",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_outbound_cross_connect",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_point_to_point",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_port",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_port_loa",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_quick_connect_accept_request",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_quick_connect_reject_request",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_streaming_events",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "packetfabric_packetfabric_user",
			Category:         "Resources",
			ShortDescription: ``,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"packetfabric_packetfabric_backbone_virtual_circuit":                0,
		"packetfabric_packetfabric_backbone_virtual_circuit_marketplace":    1,
		"packetfabric_packetfabric_backbone_virtual_circuit_speed_burst":    2,
		"packetfabric_packetfabric_cloud_provider_credential_aws":           3,
		"packetfabric_packetfabric_cloud_provider_credential_google":        4,
		"packetfabric_packetfabric_cloud_router":                            5,
		"packetfabric_packetfabric_cloud_router_bgp_session":                6,
		"packetfabric_packetfabric_cloud_router_connection_aws":             7,
		"packetfabric_packetfabric_cloud_router_connection_azure":           8,
		"packetfabric_packetfabric_cloud_router_connection_google":          9,
		"packetfabric_packetfabric_cloud_router_connection_ibm":             10,
		"packetfabric_packetfabric_cloud_router_connection_ipsec":           11,
		"packetfabric_packetfabric_cloud_router_connection_oracle":          12,
		"packetfabric_packetfabric_cloud_router_connection_port":            13,
		"packetfabric_packetfabric_cloud_router_quick_connect":              14,
		"packetfabric_packetfabric_cs_aws_dedicated_connection":             15,
		"packetfabric_packetfabric_cs_aws_hosted_connection":                16,
		"packetfabric_packetfabric_cs_aws_hosted_marketplace_connection":    17,
		"packetfabric_packetfabric_cs_azure_dedicated_connection":           18,
		"packetfabric_packetfabric_cs_azure_hosted_connection":              19,
		"packetfabric_packetfabric_cs_azure_hosted_marketplace_connection":  20,
		"packetfabric_packetfabric_cs_google_dedicated_connection":          21,
		"packetfabric_packetfabric_cs_google_hosted_connection":             22,
		"packetfabric_packetfabric_cs_google_hosted_marketplace_connection": 23,
		"packetfabric_packetfabric_cs_ibm_hosted_connection":                24,
		"packetfabric_packetfabric_cs_oracle_hosted_connection":             25,
		"packetfabric_packetfabric_cs_oracle_hosted_marketplace_connection": 26,
		"packetfabric_packetfabric_document":                                27,
		"packetfabric_packetfabric_flex_bandwidth":                          28,
		"packetfabric_packetfabric_ix_virtual_circuit_marketplace":          29,
		"packetfabric_packetfabric_link_aggregation_group":                  30,
		"packetfabric_packetfabric_marketplace_service":                     31,
		"packetfabric_packetfabric_marketplace_service_port_accept_request": 32,
		"packetfabric_packetfabric_marketplace_service_port_reject_request": 33,
		"packetfabric_packetfabric_outbound_cross_connect":                  34,
		"packetfabric_packetfabric_point_to_point":                          35,
		"packetfabric_packetfabric_port":                                    36,
		"packetfabric_packetfabric_port_loa":                                37,
		"packetfabric_packetfabric_quick_connect_accept_request":            38,
		"packetfabric_packetfabric_quick_connect_reject_request":            39,
		"packetfabric_packetfabric_streaming_events":                        40,
		"packetfabric_packetfabric_user":                                    41,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
