package netris

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "netris_acl",
			Category:         "Resources",
			ShortDescription: `Creates and manages ACLs`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_acltwozero",
			Category:         "Resources",
			ShortDescription: `Creates and manages ACLs 2.0`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_allocation",
			Category:         "Resources",
			ShortDescription: `Creates and manages Allocations`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_bgp",
			Category:         "Resources",
			ShortDescription: `Creates and manages BGPs`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_bgp_object",
			Category:         "Resources",
			ShortDescription: `Creates and manages BGP Objects`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_controller",
			Category:         "Resources",
			ShortDescription: `Creates and manages controllers`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_inventory_profile",
			Category:         "Resources",
			ShortDescription: `Creates and manages inventory profiles`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_l4lb",
			Category:         "Resources",
			ShortDescription: `Creates and manages L4LBs`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_link",
			Category:         "Resources",
			ShortDescription: `Creates and manages Links`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_nat",
			Category:         "Resources",
			ShortDescription: `Creates and manages NATs`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_permission_group",
			Category:         "Resources",
			ShortDescription: `Creates and manages Permission Groups`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_port",
			Category:         "Resources",
			ShortDescription: `Manages Switch Ports`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_portgroup",
			Category:         "Resources",
			ShortDescription: `Creates and manages ACL Port Groups`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_roh",
			Category:         "Resources",
			ShortDescription: `Creates and manages Instances (ROH)`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_route",
			Category:         "Resources",
			ShortDescription: `Creates and manages static routes`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_routemap",
			Category:         "Resources",
			ShortDescription: `Creates and manages BGP Route-maps`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_site",
			Category:         "Resources",
			ShortDescription: `Creates and manages Sites`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_softgate",
			Category:         "Resources",
			ShortDescription: `Creates and manages Softgates`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_subnet",
			Category:         "Resources",
			ShortDescription: `Creates and manages Subnet`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_switch",
			Category:         "Resources",
			ShortDescription: `Creates and manages Switches`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_tenant",
			Category:         "Resources",
			ShortDescription: `Creates and manages Tenants`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_user",
			Category:         "Resources",
			ShortDescription: `Creates and manages Users`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_user_role",
			Category:         "Resources",
			ShortDescription: `Creates and manages User Roles`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "netris_vnet",
			Category:         "Resources",
			ShortDescription: `Creates and manages Vnets`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"netris_acl":               0,
		"netris_acltwozero":        1,
		"netris_allocation":        2,
		"netris_bgp":               3,
		"netris_bgp_object":        4,
		"netris_controller":        5,
		"netris_inventory_profile": 6,
		"netris_l4lb":              7,
		"netris_link":              8,
		"netris_nat":               9,
		"netris_permission_group":  10,
		"netris_port":              11,
		"netris_portgroup":         12,
		"netris_roh":               13,
		"netris_route":             14,
		"netris_routemap":          15,
		"netris_site":              16,
		"netris_softgate":          17,
		"netris_subnet":            18,
		"netris_switch":            19,
		"netris_tenant":            20,
		"netris_user":              21,
		"netris_user_role":         22,
		"netris_vnet":              23,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
