package harness

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "harness_application",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness application`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"application",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_current_account",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving information about the current Harness account`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"current",
				"account",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_delegate",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness delegate. If more than one delegate matches the query the first one will be returned.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"delegate",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_delegate_ids",
			Category:         "First Gen",
			ShortDescription: `Use this data source to get a list of delegate ID's matching the specified search criteria.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"delegate",
				"ids",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_encrypted_text",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness application`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"encrypted",
				"text",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_environment",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness service`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"environment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_git_connector",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness application`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"git",
				"connector",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_ccm_filters",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness CCM Filter.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"ccm",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_appdynamics",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an App Dynamics connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"appdynamics",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_artifactory",
			Category:         "Next Gen",
			ShortDescription: `Resource for looking up an App Dynamics connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"artifactory",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_aws",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an AWS connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"aws",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_aws_secret_manager",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an AWS Secret Manager connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"aws",
				"secret",
				"manager",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_awscc",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an AWS Cloud Cost connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"awscc",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_awskms",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an AWS KMS connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"awskms",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_azure_cloud_cost",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an Azure Cloud Cost Connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"azure",
				"cloud",
				"cost",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_azure_cloud_provider",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an Azure Cloud Provider Connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"azure",
				"cloud",
				"provider",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_azure_key_vault",
			Category:         "Next Gen",
			ShortDescription: `Data source for looking up an Azure key vault connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"azure",
				"key",
				"vault",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_bitbucket",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Bitbucket connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"bitbucket",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_datadog",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Datadog connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"datadog",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_docker",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Datadog connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"docker",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_dynatrace",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Dynatrace connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"dynatrace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gcp",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Gcp connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gcp",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gcp_cloud_cost",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a GCP Cloud Cost Connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gcp",
				"cloud",
				"cost",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gcp_secret_manager",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up GCP Secret Manager connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gcp",
				"secret",
				"manager",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_git",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Git connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"git",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_github",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Github connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"github",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gitlab",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Gitlab connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gitlab",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_helm",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a HTTP Helm connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"helm",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_jenkins",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Jenkins connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"jenkins",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_jira",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Jira connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"jira",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_kubernetes",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Kubernetes connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"kubernetes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_kubernetes_cloud_cost",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Kubernetes Cloud Cost connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"kubernetes",
				"cloud",
				"cost",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_nexus",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Nexus connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"nexus",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_oci_helm",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a OCI Helm connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"oci",
				"helm",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_pagerduty",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a PagerDuty connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"pagerduty",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_prometheus",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Prometheus connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"prometheus",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_service_now",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Service Now connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"service",
				"now",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_splunk",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Splunk connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"splunk",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_spot",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an Spot connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"spot",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_sumologic",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up a Sumologic connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"sumologic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_tas",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up an Tas Connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"tas",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_terraform_cloud",
			Category:         "Next Gen",
			ShortDescription: `Resource for looking up a Terraform Cloud connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"terraform",
				"cloud",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_vault",
			Category:         "Next Gen",
			ShortDescription: `DataSource for looking up a Vault connector in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"vault",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_current_user",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving the current user based on the API key.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"current",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness environment.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment_clusters_mapping",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness Cluster.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
				"clusters",
				"mapping",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment_group",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness environment group.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment_service_overrides",
			Category:         "Next Gen",
			ShortDescription: `Data source for Harness environment service overrides.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
				"service",
				"overrides",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_filters",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness Filter. This data source allow to fetch filters of types {Connector, DelegateProfile, Delegate, EnvironmentGroup, FileStore, Environment}`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_agent",
			Category:         "Next Gen",
			ShortDescription: `Datasource for fetching a Harness Gitops Agents.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"agent",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_agent_deploy_yaml",
			Category:         "Next Gen",
			ShortDescription: `Datasource for fetching a Harness Gitops Agents.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"agent",
				"deploy",
				"yaml",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_applications",
			Category:         "Next Gen",
			ShortDescription: `Datasource for fetching a Harness GitOps Application.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"applications",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_cluster",
			Category:         "Next Gen",
			ShortDescription: `Data source for fetching a Harness GitOps Cluster.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_gnupg",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a GPG public key in the server's configuration.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"gnupg",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_repo_cert",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a GitOps RepoCert.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"repo",
				"cert",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_repo_cred",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a GitOps RepoCred.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"repo",
				"cred",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_repository",
			Category:         "Next Gen",
			ShortDescription: `Data Source for fetching a Harness GitOps Repository.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"repository",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_infrastructure",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness Infrastructure.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"infrastructure",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_input_set",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness input set.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"input",
				"set",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_manual_freeze",
			Category:         "Next Gen",
			ShortDescription: `DataSource for deployment freeze in harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"manual",
				"freeze",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_monitored_service",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a monitored service.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"monitored",
				"service",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_organization",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness organization`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"organization",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_permissions",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving permissions.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"permissions",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_pipeline",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness pipeline.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"pipeline",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_pipeline_filters",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness Pipeline Filter.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"pipeline",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_policy",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness policy.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_policyset",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness policyset.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"policyset",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_project",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness project.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"project",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_resource_group",
			Category:         "Next Gen",
			ShortDescription: `DataSource for looking up resource group in harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"resource",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_role_assignments",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving role assignment.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"role",
				"assignments",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_roles",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving roles`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"roles",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_secret_file",
			Category:         "Next Gen",
			ShortDescription: `Datasource for looking up secert file type secret.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"secret",
				"file",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_secret_sshkey",
			Category:         "Next Gen",
			ShortDescription: `Resource for looking up an SSH Key type secret.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"secret",
				"sshkey",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_secret_text",
			Category:         "Next Gen",
			ShortDescription: `DataSource for looking up secret of type secret text.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"secret",
				"text",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_service",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness service.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"service",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_service_account",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving service account.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"service",
				"account",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_slo",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving an SLO.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"slo",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_template",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness pipeline.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"template",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_template_filters",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness Template Filter.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"template",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_triggers",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness trigger.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"triggers",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_user",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving the user based on the API key.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_usergroup",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness User Group.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"usergroup",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_variables",
			Category:         "Next Gen",
			ShortDescription: `Data source for retrieving a Harness Variable.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"variables",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_secret_manager",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness secret manager`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"secret",
				"manager",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness service`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_ssh_credential",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving an SSH credential.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"ssh",
				"credential",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_sso_provider",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving an SSO providers`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"sso",
				"provider",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_trigger",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness trigger.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"trigger",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_user",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness user`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_user_group",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a Harness user group`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"user",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_yaml_config",
			Category:         "First Gen",
			ShortDescription: `Data source for retrieving a yaml config.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"yaml",
				"config",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"harness_application":                              0,
		"harness_current_account":                          1,
		"harness_delegate":                                 2,
		"harness_delegate_ids":                             3,
		"harness_encrypted_text":                           4,
		"harness_environment":                              5,
		"harness_git_connector":                            6,
		"harness_platform_ccm_filters":                     7,
		"harness_platform_connector_appdynamics":           8,
		"harness_platform_connector_artifactory":           9,
		"harness_platform_connector_aws":                   10,
		"harness_platform_connector_aws_secret_manager":    11,
		"harness_platform_connector_awscc":                 12,
		"harness_platform_connector_awskms":                13,
		"harness_platform_connector_azure_cloud_cost":      14,
		"harness_platform_connector_azure_cloud_provider":  15,
		"harness_platform_connector_azure_key_vault":       16,
		"harness_platform_connector_bitbucket":             17,
		"harness_platform_connector_datadog":               18,
		"harness_platform_connector_docker":                19,
		"harness_platform_connector_dynatrace":             20,
		"harness_platform_connector_gcp":                   21,
		"harness_platform_connector_gcp_cloud_cost":        22,
		"harness_platform_connector_gcp_secret_manager":    23,
		"harness_platform_connector_git":                   24,
		"harness_platform_connector_github":                25,
		"harness_platform_connector_gitlab":                26,
		"harness_platform_connector_helm":                  27,
		"harness_platform_connector_jenkins":               28,
		"harness_platform_connector_jira":                  29,
		"harness_platform_connector_kubernetes":            30,
		"harness_platform_connector_kubernetes_cloud_cost": 31,
		"harness_platform_connector_nexus":                 32,
		"harness_platform_connector_oci_helm":              33,
		"harness_platform_connector_pagerduty":             34,
		"harness_platform_connector_prometheus":            35,
		"harness_platform_connector_service_now":           36,
		"harness_platform_connector_splunk":                37,
		"harness_platform_connector_spot":                  38,
		"harness_platform_connector_sumologic":             39,
		"harness_platform_connector_tas":                   40,
		"harness_platform_connector_terraform_cloud":       41,
		"harness_platform_connector_vault":                 42,
		"harness_platform_current_user":                    43,
		"harness_platform_environment":                     44,
		"harness_platform_environment_clusters_mapping":    45,
		"harness_platform_environment_group":               46,
		"harness_platform_environment_service_overrides":   47,
		"harness_platform_filters":                         48,
		"harness_platform_gitops_agent":                    49,
		"harness_platform_gitops_agent_deploy_yaml":        50,
		"harness_platform_gitops_applications":             51,
		"harness_platform_gitops_cluster":                  52,
		"harness_platform_gitops_gnupg":                    53,
		"harness_platform_gitops_repo_cert":                54,
		"harness_platform_gitops_repo_cred":                55,
		"harness_platform_gitops_repository":               56,
		"harness_platform_infrastructure":                  57,
		"harness_platform_input_set":                       58,
		"harness_platform_manual_freeze":                   59,
		"harness_platform_monitored_service":               60,
		"harness_platform_organization":                    61,
		"harness_platform_permissions":                     62,
		"harness_platform_pipeline":                        63,
		"harness_platform_pipeline_filters":                64,
		"harness_platform_policy":                          65,
		"harness_platform_policyset":                       66,
		"harness_platform_project":                         67,
		"harness_platform_resource_group":                  68,
		"harness_platform_role_assignments":                69,
		"harness_platform_roles":                           70,
		"harness_platform_secret_file":                     71,
		"harness_platform_secret_sshkey":                   72,
		"harness_platform_secret_text":                     73,
		"harness_platform_service":                         74,
		"harness_platform_service_account":                 75,
		"harness_platform_slo":                             76,
		"harness_platform_template":                        77,
		"harness_platform_template_filters":                78,
		"harness_platform_triggers":                        79,
		"harness_platform_user":                            80,
		"harness_platform_usergroup":                       81,
		"harness_platform_variables":                       82,
		"harness_secret_manager":                           83,
		"harness_service":                                  84,
		"harness_ssh_credential":                           85,
		"harness_sso_provider":                             86,
		"harness_trigger":                                  87,
		"harness_user":                                     88,
		"harness_user_group":                               89,
		"harness_yaml_config":                              90,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
