package harness

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "harness_application",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness application`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_current_account",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving information about the current Harness account`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_delegate",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness delegate. If more than one delegate matches the query the first one will be returned.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_delegate_ids",
			Category:         "Data Sources",
			ShortDescription: `Use this data source to get a list of delegate ID's matching the specified search criteria.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_encrypted_text",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness application`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_environment",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness service`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_git_connector",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness application`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_appdynamics",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up an App Dynamics connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_artifactory",
			Category:         "Data Sources",
			ShortDescription: `Resource for looking up an App Dynamics connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_aws",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up an AWS connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_aws_secret_manager",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up an AWS Secret Manager connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_awscc",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up an AWS Cloud Cost connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_awskms",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up an AWS KMS connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_bitbucket",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Bitbucket connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_datadog",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Datadog connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_docker",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Datadog connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_dynatrace",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Dynatrace connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gcp",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Gcp connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_git",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Git connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_github",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Github connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gitlab",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Gitlab connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_helm",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Helm connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_jira",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Jira connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_kubernetes",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Kubernetes connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_nexus",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Nexus connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_pagerduty",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a PagerDuty connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_prometheus",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Prometheus connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_splunk",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Splunk connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_sumologic",
			Category:         "Data Sources",
			ShortDescription: `Datasource for looking up a Sumologic connector.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_current_user",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving the current user based on the API key.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness environment.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_organization",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness organization`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_pipeline",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness pipeline.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_project",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness project.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_service",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness service.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_secret_manager",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness secret manager`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness service`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_ssh_credential",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving an SSH credential.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_sso_provider",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving an SSO providers`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_user",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness user`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_user_group",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a Harness user group`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_yaml_config",
			Category:         "Data Sources",
			ShortDescription: `Data source for retrieving a yaml config.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"harness_application":                           0,
		"harness_current_account":                       1,
		"harness_delegate":                              2,
		"harness_delegate_ids":                          3,
		"harness_encrypted_text":                        4,
		"harness_environment":                           5,
		"harness_git_connector":                         6,
		"harness_platform_connector_appdynamics":        7,
		"harness_platform_connector_artifactory":        8,
		"harness_platform_connector_aws":                9,
		"harness_platform_connector_aws_secret_manager": 10,
		"harness_platform_connector_awscc":              11,
		"harness_platform_connector_awskms":             12,
		"harness_platform_connector_bitbucket":          13,
		"harness_platform_connector_datadog":            14,
		"harness_platform_connector_docker":             15,
		"harness_platform_connector_dynatrace":          16,
		"harness_platform_connector_gcp":                17,
		"harness_platform_connector_git":                18,
		"harness_platform_connector_github":             19,
		"harness_platform_connector_gitlab":             20,
		"harness_platform_connector_helm":               21,
		"harness_platform_connector_jira":               22,
		"harness_platform_connector_kubernetes":         23,
		"harness_platform_connector_nexus":              24,
		"harness_platform_connector_pagerduty":          25,
		"harness_platform_connector_prometheus":         26,
		"harness_platform_connector_splunk":             27,
		"harness_platform_connector_sumologic":          28,
		"harness_platform_current_user":                 29,
		"harness_platform_environment":                  30,
		"harness_platform_organization":                 31,
		"harness_platform_pipeline":                     32,
		"harness_platform_project":                      33,
		"harness_platform_service":                      34,
		"harness_secret_manager":                        35,
		"harness_service":                               36,
		"harness_ssh_credential":                        37,
		"harness_sso_provider":                          38,
		"harness_user":                                  39,
		"harness_user_group":                            40,
		"harness_yaml_config":                           41,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
