package harness

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "harness_add_user_to_group",
			Category:         "First Gen",
			ShortDescription: `Resource for adding a user to a group.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"add",
				"user",
				"to",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_application",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Harness application`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"application",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_application_gitsync",
			Category:         "First Gen",
			ShortDescription: `Resource for configuring application git sync.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"application",
				"gitsync",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_cloudprovider_aws",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an AWS cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"cloudprovider",
				"aws",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_cloudprovider_azure",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an Azure cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"cloudprovider",
				"azure",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_cloudprovider_datacenter",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a physical data center cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"cloudprovider",
				"datacenter",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_cloudprovider_gcp",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a GCP cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"cloudprovider",
				"gcp",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_cloudprovider_kubernetes",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Kubernetes cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"cloudprovider",
				"kubernetes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_cloudprovider_spot",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Spot cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"cloudprovider",
				"spot",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_cloudprovider_tanzu",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Tanzu cloud provider. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"cloudprovider",
				"tanzu",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_delegate_approval",
			Category:         "First Gen",
			ShortDescription: `Resource for approving or rejecting delegates.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"delegate",
				"approval",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_encrypted_text",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an encrypted text secret`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"encrypted",
				"text",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_environment",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an environment`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"environment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_git_connector",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a git connector`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"git",
				"connector",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_infrastructure_definition",
			Category:         "First Gen",
			ShortDescription: `Resource for creating am infrastructure definition. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"infrastructure",
				"definition",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_ccm_filters",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness CCM Filters.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"ccm",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_appdynamics",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an App Dynamics connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"appdynamics",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_artifactory",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an Artifactory connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"artifactory",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_aws",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an AWS connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"aws",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_aws_secret_manager",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an AWS Secret Manager connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"aws",
				"secret",
				"manager",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_awscc",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an AWS Cloud Cost connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"awscc",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_awskms",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an AWS KMS connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"awskms",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_azure_cloud_cost",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an Azure Cloud Cost connector in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"azure",
				"cloud",
				"cost",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_azure_cloud_provider",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an Azure Cloud Provider in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"azure",
				"cloud",
				"provider",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_azure_key_vault",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an Azure key vault in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"azure",
				"key",
				"vault",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_bitbucket",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Bitbucket connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"bitbucket",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_datadog",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Datadog connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"datadog",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_docker",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Docker connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"docker",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_dynatrace",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Dynatrace connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"dynatrace",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gcp",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Gcp connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gcp",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gcp_cloud_cost",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a GCP Cloud Cost connector in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gcp",
				"cloud",
				"cost",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gcp_secret_manager",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a GCP Secret Manager connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gcp",
				"secret",
				"manager",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_git",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Git connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"git",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_github",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Github connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"github",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_gitlab",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Gitlab connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"gitlab",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_helm",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a HTTP Helm connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"helm",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_jenkins",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Jenkins connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"jenkins",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_jira",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Jira connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"jira",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_kubernetes",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a K8s connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"kubernetes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_kubernetes_cloud_cost",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Kubernetes Cloud Cost connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"kubernetes",
				"cloud",
				"cost",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_newrelic",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a New Relic connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"newrelic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_nexus",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Nexus connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"nexus",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_oci_helm",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a OCI Helm connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"oci",
				"helm",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_pagerduty",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a PagerDuty connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"pagerduty",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_prometheus",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Prometheus connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"prometheus",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_service_now",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Service Now connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"service",
				"now",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_splunk",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Splunk connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"splunk",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_spot",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Spot connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"spot",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_sumologic",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Sumologic connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"sumologic",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_tas",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an Tas in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"tas",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_terraform_cloud",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Terraform Cloud connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"terraform",
				"cloud",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_connector_vault",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a HashiCorp Vault Secret Manager connector.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"connector",
				"vault",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness environment.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment_clusters_mapping",
			Category:         "Next Gen",
			ShortDescription: `Resource for mapping environment with Harness Clusters.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
				"clusters",
				"mapping",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment_group",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness environment group.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_environment_service_overrides",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness environment service overrides.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"environment",
				"service",
				"overrides",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_feature_flag",
			Category:         "Next Gen",
			ShortDescription: `Resource for managing Feature Flags.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"feature",
				"flag",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_ff_api_key",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an environment SDK key for Feature Flags.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"ff",
				"api",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_filters",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Filter. This resource support filters of types {Connector, DelegateProfile, Delegate, EnvironmentGroup, FileStore, Environment}`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_agent",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Gitops Agents.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"agent",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_applications",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Gitops Application.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"applications",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_cluster",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Gitops Cluster.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"cluster",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_gnupg",
			Category:         "Next Gen",
			ShortDescription: `GPG public key in the server's configuration.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"gnupg",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_repo_cert",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Gitops Repositories Certificates.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"repo",
				"cert",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_repo_cred",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Gitops Repositories Credentials.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"repo",
				"cred",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_gitops_repository",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating Harness Gitops Repositories.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"gitops",
				"repository",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_infrastructure",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Infrastructure.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"infrastructure",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_input_set",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness InputSet.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"input",
				"set",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_manual_freeze",
			Category:         "Next Gen",
			ShortDescription: `Resource for Manual Deployment Freeze Window.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"manual",
				"freeze",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_monitored_service",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a monitored service.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"monitored",
				"service",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_organization",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness organization.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"organization",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_pipeline",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness pipeline.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"pipeline",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_pipeline_filters",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating Harness Pipeline Filters.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"pipeline",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_policy",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Policy.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_policyset",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Policyset.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"policyset",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_project",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness project.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"project",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_resource_group",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Resource Group`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"resource",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_role_assignments",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating role assignments in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"role",
				"assignments",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_roles",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating roles.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"roles",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_secret_file",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a secret of type secret file in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"secret",
				"file",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_secret_sshkey",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an ssh key type secret.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"secret",
				"sshkey",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_secret_text",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating secret of type secret text`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"secret",
				"text",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_service",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness project.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"service",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_service_account",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating service account.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"service",
				"account",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_slo",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating an SLO.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"slo",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_template",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Template.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"template",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_template_filters",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Template Filters.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"template",
				"filters",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_triggers",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating triggers in Harness.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"triggers",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_user",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness User. This requires your authentication mechanism to be set to SAML, LDAP, or OAuth, and the feature flag AUTOACCEPTSAMLACCOUNTINVITES to be enabled.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_usergroup",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness User Group. Linking SSO providers with User Groups: The following fields need to be populated for LDAP SSO Providers: - linked_sso_id - linked_sso_display_name - sso_group_id - sso_group_name - linked_sso_type - sso_linked The following fields need to be populated for SAML SSO Providers: - linked_sso_id - linked_sso_display_name - sso_group_name - sso_group_id // same as sso_group_name - linked_sso_type - sso_linked`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"usergroup",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_platform_variables",
			Category:         "Next Gen",
			ShortDescription: `Resource for creating a Harness Variables.`,
			Description:      ``,
			Keywords: []string{
				"next",
				"gen",
				"platform",
				"variables",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_ami",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an AMI service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"ami",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_aws_codedeploy",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an AWS CodeDeploy service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"aws",
				"codedeploy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_aws_lambda",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an AWS Lambda service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"aws",
				"lambda",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_ecs",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an AWS ECS service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"ecs",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_helm",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Kubernetes Helm service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"helm",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_kubernetes",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Kubernetes service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"kubernetes",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_ssh",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an SSH service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"ssh",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_tanzu",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Tanzu (PCF) service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"tanzu",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_service_winrm",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an WinRM service. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"service",
				"winrm",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_ssh_credential",
			Category:         "First Gen",
			ShortDescription: `Resource for creating an encrypted text secret`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"ssh",
				"credential",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_user",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Harness user`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_user_group",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a Harness user group`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"user",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_user_group_permissions",
			Category:         "First Gen",
			ShortDescription: `Resource for adding permissions to an existing Harness user group.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"user",
				"group",
				"permissions",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "harness_yaml_config",
			Category:         "First Gen",
			ShortDescription: `Resource for creating a raw YAML configuration in Harness. Note: This works for all objects EXCEPT application objects. This resource uses the config-as-code API's. When updating the name or path of this resource you should typically also set the create_before_destroy = true lifecycle setting.`,
			Description:      ``,
			Keywords: []string{
				"first",
				"gen",
				"yaml",
				"config",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"harness_add_user_to_group":                        0,
		"harness_application":                              1,
		"harness_application_gitsync":                      2,
		"harness_cloudprovider_aws":                        3,
		"harness_cloudprovider_azure":                      4,
		"harness_cloudprovider_datacenter":                 5,
		"harness_cloudprovider_gcp":                        6,
		"harness_cloudprovider_kubernetes":                 7,
		"harness_cloudprovider_spot":                       8,
		"harness_cloudprovider_tanzu":                      9,
		"harness_delegate_approval":                        10,
		"harness_encrypted_text":                           11,
		"harness_environment":                              12,
		"harness_git_connector":                            13,
		"harness_infrastructure_definition":                14,
		"harness_platform_ccm_filters":                     15,
		"harness_platform_connector_appdynamics":           16,
		"harness_platform_connector_artifactory":           17,
		"harness_platform_connector_aws":                   18,
		"harness_platform_connector_aws_secret_manager":    19,
		"harness_platform_connector_awscc":                 20,
		"harness_platform_connector_awskms":                21,
		"harness_platform_connector_azure_cloud_cost":      22,
		"harness_platform_connector_azure_cloud_provider":  23,
		"harness_platform_connector_azure_key_vault":       24,
		"harness_platform_connector_bitbucket":             25,
		"harness_platform_connector_datadog":               26,
		"harness_platform_connector_docker":                27,
		"harness_platform_connector_dynatrace":             28,
		"harness_platform_connector_gcp":                   29,
		"harness_platform_connector_gcp_cloud_cost":        30,
		"harness_platform_connector_gcp_secret_manager":    31,
		"harness_platform_connector_git":                   32,
		"harness_platform_connector_github":                33,
		"harness_platform_connector_gitlab":                34,
		"harness_platform_connector_helm":                  35,
		"harness_platform_connector_jenkins":               36,
		"harness_platform_connector_jira":                  37,
		"harness_platform_connector_kubernetes":            38,
		"harness_platform_connector_kubernetes_cloud_cost": 39,
		"harness_platform_connector_newrelic":              40,
		"harness_platform_connector_nexus":                 41,
		"harness_platform_connector_oci_helm":              42,
		"harness_platform_connector_pagerduty":             43,
		"harness_platform_connector_prometheus":            44,
		"harness_platform_connector_service_now":           45,
		"harness_platform_connector_splunk":                46,
		"harness_platform_connector_spot":                  47,
		"harness_platform_connector_sumologic":             48,
		"harness_platform_connector_tas":                   49,
		"harness_platform_connector_terraform_cloud":       50,
		"harness_platform_connector_vault":                 51,
		"harness_platform_environment":                     52,
		"harness_platform_environment_clusters_mapping":    53,
		"harness_platform_environment_group":               54,
		"harness_platform_environment_service_overrides":   55,
		"harness_platform_feature_flag":                    56,
		"harness_platform_ff_api_key":                      57,
		"harness_platform_filters":                         58,
		"harness_platform_gitops_agent":                    59,
		"harness_platform_gitops_applications":             60,
		"harness_platform_gitops_cluster":                  61,
		"harness_platform_gitops_gnupg":                    62,
		"harness_platform_gitops_repo_cert":                63,
		"harness_platform_gitops_repo_cred":                64,
		"harness_platform_gitops_repository":               65,
		"harness_platform_infrastructure":                  66,
		"harness_platform_input_set":                       67,
		"harness_platform_manual_freeze":                   68,
		"harness_platform_monitored_service":               69,
		"harness_platform_organization":                    70,
		"harness_platform_pipeline":                        71,
		"harness_platform_pipeline_filters":                72,
		"harness_platform_policy":                          73,
		"harness_platform_policyset":                       74,
		"harness_platform_project":                         75,
		"harness_platform_resource_group":                  76,
		"harness_platform_role_assignments":                77,
		"harness_platform_roles":                           78,
		"harness_platform_secret_file":                     79,
		"harness_platform_secret_sshkey":                   80,
		"harness_platform_secret_text":                     81,
		"harness_platform_service":                         82,
		"harness_platform_service_account":                 83,
		"harness_platform_slo":                             84,
		"harness_platform_template":                        85,
		"harness_platform_template_filters":                86,
		"harness_platform_triggers":                        87,
		"harness_platform_user":                            88,
		"harness_platform_usergroup":                       89,
		"harness_platform_variables":                       90,
		"harness_service_ami":                              91,
		"harness_service_aws_codedeploy":                   92,
		"harness_service_aws_lambda":                       93,
		"harness_service_ecs":                              94,
		"harness_service_helm":                             95,
		"harness_service_kubernetes":                       96,
		"harness_service_ssh":                              97,
		"harness_service_tanzu":                            98,
		"harness_service_winrm":                            99,
		"harness_ssh_credential":                           100,
		"harness_user":                                     101,
		"harness_user_group":                               102,
		"harness_user_group_permissions":                   103,
		"harness_yaml_config":                              104,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
