package buddy

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_group",
			Category:         "Data Sources",
			ShortDescription: `Get group by name or group ID Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_group_members",
			Category:         "Data Sources",
			ShortDescription: `List members of a group and optionally filter them by name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_groups",
			Category:         "Data Sources",
			ShortDescription: `List groups and optionally filter them by name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_integration",
			Category:         "Data Sources",
			ShortDescription: `Get integration by name or integration ID Token scope required: INTEGRATION_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_integrations",
			Category:         "Data Sources",
			ShortDescription: `List integrations and optionally filter them by name or type Token scope required: INTEGRATION_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_member",
			Category:         "Data Sources",
			ShortDescription: `Get member by name, email or member ID Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_members",
			Category:         "Data Sources",
			ShortDescription: `List members and optionally filter them by name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_permission",
			Category:         "Data Sources",
			ShortDescription: `Get permission (role) by name or permission ID Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_permissions",
			Category:         "Data Sources",
			ShortDescription: `List permissions (roles) and optionally filter them by name or type Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_pipeline",
			Category:         "Data Sources",
			ShortDescription: `Get pipeline by name or pipeline ID Token scopes required: WORKSPACE, EXECUTION_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_pipelines",
			Category:         "Data Sources",
			ShortDescription: `List pipelines and optionally filter them by name Token scopes required: WORKSPACE, EXECUTION_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_profile",
			Category:         "Data Sources",
			ShortDescription: `Get details of a Buddy's user profile Token scope required: USER_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_project",
			Category:         "Data Sources",
			ShortDescription: `Get project by name or display_name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_project_group",
			Category:         "Data Sources",
			ShortDescription: `Get project group Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_project_groups",
			Category:         "Data Sources",
			ShortDescription: `List project groups and optionally filter them by name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_project_member",
			Category:         "Data Sources",
			ShortDescription: `Get project member Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_project_members",
			Category:         "Data Sources",
			ShortDescription: `List project members and optionally filter them by name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_projects",
			Category:         "Data Sources",
			ShortDescription: `List projects and optionally filter them by membership, status, name or display name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_variable",
			Category:         "Data Sources",
			ShortDescription: `Get variable by key or variable ID Token scope required: WORKSPACE, VARIABLE_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_variable_ssh_key",
			Category:         "Data Sources",
			ShortDescription: `Get variables of SSH key type by key or variable ID Token scope required: WORKSPACE, VARIABLE_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_variables",
			Category:         "Data Sources",
			ShortDescription: `List variables and optionally filter them by key, project, pipeline or action Token scope required: WORKSPACE, VARIABLE_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_variables_ssh_keys",
			Category:         "Data Sources",
			ShortDescription: `List variables of SSH key type and optionally filter them by key, project name, pipeline or action Token scope required: WORKSPACE, VARIABLE_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_webhook",
			Category:         "Data Sources",
			ShortDescription: `Get webhook by target URL or webhook ID Token scope required: WORKSPACE, WEBHOOK_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_webhooks",
			Category:         "Data Sources",
			ShortDescription: `List webhooks and optionally filter them by target URL Token scope required: WORKSPACE, WEBHOOK_INFO`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_workspace",
			Category:         "Data Sources",
			ShortDescription: `Get workspace by URL handle or name Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "buddy_buddy_workspaces",
			Category:         "Data Sources",
			ShortDescription: `List workspaces and optionally filter them by name or URL handle Token scope required: WORKSPACE`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"buddy_buddy_group":              0,
		"buddy_buddy_group_members":      1,
		"buddy_buddy_groups":             2,
		"buddy_buddy_integration":        3,
		"buddy_buddy_integrations":       4,
		"buddy_buddy_member":             5,
		"buddy_buddy_members":            6,
		"buddy_buddy_permission":         7,
		"buddy_buddy_permissions":        8,
		"buddy_buddy_pipeline":           9,
		"buddy_buddy_pipelines":          10,
		"buddy_buddy_profile":            11,
		"buddy_buddy_project":            12,
		"buddy_buddy_project_group":      13,
		"buddy_buddy_project_groups":     14,
		"buddy_buddy_project_member":     15,
		"buddy_buddy_project_members":    16,
		"buddy_buddy_projects":           17,
		"buddy_buddy_variable":           18,
		"buddy_buddy_variable_ssh_key":   19,
		"buddy_buddy_variables":          20,
		"buddy_buddy_variables_ssh_keys": 21,
		"buddy_buddy_webhook":            22,
		"buddy_buddy_webhooks":           23,
		"buddy_buddy_workspace":          24,
		"buddy_buddy_workspaces":         25,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
