package pingone

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "pingone_agreement",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage agreements in a PingOne environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"agreement",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_agreement_enable",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage the enabled status of an agreement in a PingOne environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"agreement",
				"enable",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_agreement_localization",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage agreement localizations in a PingOne environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"agreement",
				"localization",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_agreement_localization_enable",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage the enabled status of an agreement localization in a PingOne environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"agreement",
				"localization",
				"enable",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_agreement_localization_revision",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage agreement localization revisions in a PingOne environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"agreement",
				"localization",
				"revision",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_application",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne applications`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"application",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_application_attribute_mapping",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage custom attribute mappings for applications configured in PingOne.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"application",
				"attribute",
				"mapping",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_application_flow_policy_assignment",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage a DaVinci flow policy assignment for an application configured in PingOne.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"application",
				"flow",
				"policy",
				"assignment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_application_resource_grant",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage a resource grant for an application configured in PingOne.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"application",
				"resource",
				"grant",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_application_role_assignment",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne admin role assignments to applications.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"application",
				"role",
				"assignment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_application_sign_on_policy_assignment",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage a sign-on policy assignment for applications configured in PingOne.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"application",
				"sign",
				"on",
				"policy",
				"assignment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_authorize_decision_endpoint",
			Category:         "Authorize",
			ShortDescription: `Resource to create and manage PingOne Authorize decision endpoints.`,
			Description:      ``,
			Keywords: []string{
				"authorize",
				"decision",
				"endpoint",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_branding_settings",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage the PingOne branding settings for an environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"branding",
				"settings",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_branding_theme",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne branding themes for an environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"branding",
				"theme",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_certificate",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne certificates.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"certificate",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_certificate_signing_response",
			Category:         "Platform",
			ShortDescription: `Resource to import a CA issued response to a downloaded certificate signing request (CSR).`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"certificate",
				"signing",
				"response",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_custom_domain",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne Custom Domains.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"custom",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_custom_domain_ssl",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne Custom Domain SSL settings.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"custom",
				"domain",
				"ssl",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_custom_domain_verify",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne Custom Domain verification.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"custom",
				"domain",
				"verify",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_environment",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne environments.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"environment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_gateway",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne gateways.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"gateway",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_gateway_credential",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne gateway credentials.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"gateway",
				"credential",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_gateway_role_assignment",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne admin role assignments to gateways.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"gateway",
				"role",
				"assignment",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_group",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne groups`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"group",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_group_nesting",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne group nesting.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"group",
				"nesting",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_identity_provider",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne Identity Providers.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"identity",
				"provider",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_identity_provider_attribute",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage an attribute mapping for identity providers configured in PingOne. For a full list of social providers and their configurable attribute mappings, see the Social Provider and External Identity Provider Attribute Reference below.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"identity",
				"provider",
				"attribute",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_image",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne images.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"image",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_key",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne keys`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"key",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_language",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne languages. To fully enable a created language, the pingone_language_update resource must be used to complete the configuration.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"language",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_language_update",
			Category:         "Platform",
			ShortDescription: `Resource to complete the configuration of customer-defined and system-defined languages in PingOne.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"language",
				"update",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_mfa_application_push_credential",
			Category:         "MFA",
			ShortDescription: `Resource to create and manage push credentials for a mobile MFA application configured in PingOne.`,
			Description:      ``,
			Keywords: []string{
				"mfa",
				"application",
				"push",
				"credential",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_mfa_fido_policy",
			Category:         "MFA",
			ShortDescription: `Resource to create and manage MFA FIDO Policies in a PingOne Environment.`,
			Description:      ``,
			Keywords: []string{
				"mfa",
				"fido",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_mfa_policy",
			Category:         "MFA",
			ShortDescription: `Resource to create and manage MFA Policies in a PingOne Environment.`,
			Description:      ``,
			Keywords: []string{
				"mfa",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_mfa_settings",
			Category:         "MFA",
			ShortDescription: `Resource to create and manage a PingOne Environment's MFA Settings`,
			Description:      ``,
			Keywords: []string{
				"mfa",
				"settings",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_notification_policy",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage notification policies in a PingOne environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"notification",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_notification_settings_email",
			Category:         "Platform",
			ShortDescription: `Resource to manage the email sender settings in a PingOne environment.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"notification",
				"settings",
				"email",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_notification_template_content",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne notification template contents for push, SMS, email and voice notifications.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"notification",
				"template",
				"content",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_password_policy",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne password policies`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"password",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_population",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne populations`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"population",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_resource",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne OAuth 2.0 resources`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"resource",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_resource_attribute",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage resource attributes in PingOne.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"resource",
				"attribute",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_resource_scope",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne OAuth 2.0 resource scopes for custom resources. This resource cannot manage PingOne API or OpenID Connect scopes.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"resource",
				"scope",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_resource_scope_openid",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage resource scopes for the OpenID Connect resource. Predefined scopes can be overridden, and new scopes can be defined.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"resource",
				"scope",
				"openid",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_resource_scope_pingone_api",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage resource scopes for the PingOne API resource. Predefined scopes of p1:read:user and p1:update:user can be overridden, and new scopes can be defined as subscopes in the format p1:read:user:{suffix} or p1:update:user:{suffix}. E.g. p1:read:user:newscope or p1:update:user:newscope.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"resource",
				"scope",
				"api",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_role_assignment_user",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne admin role assignments to users.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"role",
				"assignment",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_schema_attribute",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne schema attributes`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"schema",
				"attribute",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_sign_on_policy",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne sign on policies`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"sign",
				"on",
				"policy",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_sign_on_policy_action",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne sign on policy actions.`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"sign",
				"on",
				"policy",
				"action",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_trusted_email_address",
			Category:         "Platform",
			ShortDescription: ``,
			Description:      ``,
			Keywords: []string{
				"platform",
				"trusted",
				"email",
				"address",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_trusted_email_domain",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne Trusted Email Domains.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"trusted",
				"email",
				"domain",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_user",
			Category:         "SSO",
			ShortDescription: `Resource to create and manage PingOne users`,
			Description:      ``,
			Keywords: []string{
				"sso",
				"user",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "pingone_webhook",
			Category:         "Platform",
			ShortDescription: `Resource to create and manage PingOne Webhooks / Data Subscriptions.`,
			Description:      ``,
			Keywords: []string{
				"platform",
				"webhook",
			},
			Arguments:  []resource.Attribute{},
			Attributes: []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"pingone_agreement":                             0,
		"pingone_agreement_enable":                      1,
		"pingone_agreement_localization":                2,
		"pingone_agreement_localization_enable":         3,
		"pingone_agreement_localization_revision":       4,
		"pingone_application":                           5,
		"pingone_application_attribute_mapping":         6,
		"pingone_application_flow_policy_assignment":    7,
		"pingone_application_resource_grant":            8,
		"pingone_application_role_assignment":           9,
		"pingone_application_sign_on_policy_assignment": 10,
		"pingone_authorize_decision_endpoint":           11,
		"pingone_branding_settings":                     12,
		"pingone_branding_theme":                        13,
		"pingone_certificate":                           14,
		"pingone_certificate_signing_response":          15,
		"pingone_custom_domain":                         16,
		"pingone_custom_domain_ssl":                     17,
		"pingone_custom_domain_verify":                  18,
		"pingone_environment":                           19,
		"pingone_gateway":                               20,
		"pingone_gateway_credential":                    21,
		"pingone_gateway_role_assignment":               22,
		"pingone_group":                                 23,
		"pingone_group_nesting":                         24,
		"pingone_identity_provider":                     25,
		"pingone_identity_provider_attribute":           26,
		"pingone_image":                                 27,
		"pingone_key":                                   28,
		"pingone_language":                              29,
		"pingone_language_update":                       30,
		"pingone_mfa_application_push_credential":       31,
		"pingone_mfa_fido_policy":                       32,
		"pingone_mfa_policy":                            33,
		"pingone_mfa_settings":                          34,
		"pingone_notification_policy":                   35,
		"pingone_notification_settings_email":           36,
		"pingone_notification_template_content":         37,
		"pingone_password_policy":                       38,
		"pingone_population":                            39,
		"pingone_resource":                              40,
		"pingone_resource_attribute":                    41,
		"pingone_resource_scope":                        42,
		"pingone_resource_scope_openid":                 43,
		"pingone_resource_scope_pingone_api":            44,
		"pingone_role_assignment_user":                  45,
		"pingone_schema_attribute":                      46,
		"pingone_sign_on_policy":                        47,
		"pingone_sign_on_policy_action":                 48,
		"pingone_trusted_email_address":                 49,
		"pingone_trusted_email_domain":                  50,
		"pingone_user":                                  51,
		"pingone_webhook":                               52,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
