package zentral

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	DataSources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "zentral_jmespath_check",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_jmespath_check allows details of a JMESPath compliance check to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_meta_business_unit",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_meta_business_unit allows details of a meta business unit to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_catalog",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_monolith_catalog allows details of a Monolith catalog to be retrieved by its ID or its name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_condition",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_monolith_condition allows details of a Monolith condition to be retrieved by its ID or its name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_enrollment",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_monolith_enrollment allows details of a Monolith enrollment to be retrieved by its ID.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_manifest",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_monolith_manifest allows details of a Monolith manifest to be retrieved by its ID or its name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_sub_manifest",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_monolith_sub_manifest allows details of a Monolith sub manifest to be retrieved by its ID or its name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_munki_configuration",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_munki_configuration allows details of a Munki configuration to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_munki_enrollment",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_munki_enrollment allows details of a Munki enrollment to be retrieved by its ID.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_atc",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_osquery_atc allows details of a Osquery automatic table construction to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_configuration",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_osquery_configuration allows details of a Osquery configuration to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_enrollment",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_osquery_enrollment allows details of a Osquery enrollment to be retrieved by its ID.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_file_category",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_osquery_file_category allows details of a Osquery file category to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_pack",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_osquery_pack allows details of a Osquery pack to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_query",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_osquery_query allows details of a Osquery query to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_santa_configuration",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_santa_configuration allows details of a Santa configuration to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_santa_enrollment",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_santa_enrollment allows details of a Santa enrollment to be retrieved by its ID.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_santa_rule",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_santa_rule allows details of a Santa rule to be retrieved by its ID.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_tag",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_tag allows details of a tag to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_taxonomy",
			Category:         "Data Sources",
			ShortDescription: `The data source zentral_taxonomy allows details of a taxonomy to be retrieved by its ID or name.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	dataSourcesMap = map[string]int{

		"zentral_jmespath_check":        0,
		"zentral_meta_business_unit":    1,
		"zentral_monolith_catalog":      2,
		"zentral_monolith_condition":    3,
		"zentral_monolith_enrollment":   4,
		"zentral_monolith_manifest":     5,
		"zentral_monolith_sub_manifest": 6,
		"zentral_munki_configuration":   7,
		"zentral_munki_enrollment":      8,
		"zentral_osquery_atc":           9,
		"zentral_osquery_configuration": 10,
		"zentral_osquery_enrollment":    11,
		"zentral_osquery_file_category": 12,
		"zentral_osquery_pack":          13,
		"zentral_osquery_query":         14,
		"zentral_santa_configuration":   15,
		"zentral_santa_enrollment":      16,
		"zentral_santa_rule":            17,
		"zentral_tag":                   18,
		"zentral_taxonomy":              19,
	}
)

func GetDataSource(r string) (*resource.Resource, error) {
	rs, ok := dataSourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("datasource %q not found", r)
	}
	return DataSources[rs], nil
}
