package zentral

import (
	"fmt"

	"github.com/cycloidio/tfdocs/resource"
)

var (
	Resources = []*resource.Resource{

		&resource.Resource{
			Name:             "",
			Type:             "zentral_jmespath_check",
			Category:         "Resources",
			ShortDescription: `The resource zentral_jmespath_check manages JMESPath compliance checks.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_meta_business_unit",
			Category:         "Resources",
			ShortDescription: `The resource zentral_meta_business_unit manages meta business units.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_catalog",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_catalog manages Monolith catalogs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_condition",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_condition manages Monolith conditions.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_enrollment",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_enrollment manages Monolith enrollments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_manifest",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_manifest manages Monolith manifests.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_manifest_catalog",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_manifest_catalog manages Monolith manifest catalogs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_manifest_sub_manifest",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_manifest_sub_manifest manages Monolith manifest sub manifests.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_sub_manifest",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_sub_manifest manages Monolith sub manifests.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_monolith_sub_manifest_pkg_info",
			Category:         "Resources",
			ShortDescription: `The resource zentral_monolith_sub_manifest_pkg_info manages Monolith sub manifest pkg infos.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_munki_configuration",
			Category:         "Resources",
			ShortDescription: `The resource zentral_munki_configuration manages Munki configurations.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_munki_enrollment",
			Category:         "Resources",
			ShortDescription: `The resource zentral_munki_enrollment manages Munki enrollments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_atc",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_atc manages Osquery automatic table constructions.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_configuration",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_configuration manages Osquery configurations.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_configuration_pack",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_configuration_pack manages Osquery configuration packs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_enrollment",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_enrollment manages Osquery enrollments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_file_category",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_file_category manages Osquery file categories.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_pack",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_pack manages Osquery packs.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_pack_query",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_pack_query manages Osquery pack queries.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_osquery_query",
			Category:         "Resources",
			ShortDescription: `The resource zentral_osquery_query manages Osquery queries.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_santa_configuration",
			Category:         "Resources",
			ShortDescription: `The resource zentral_santa_configuration manages Santa configurations.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_santa_enrollment",
			Category:         "Resources",
			ShortDescription: `The resource zentral_santa_enrollment manages Santa enrollments.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_santa_rule",
			Category:         "Resources",
			ShortDescription: `The resource zentral_santa_rule manages Santa rules.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_tag",
			Category:         "Resources",
			ShortDescription: `The resource zentral_tag manages tags.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
		&resource.Resource{
			Name:             "",
			Type:             "zentral_taxonomy",
			Category:         "Resources",
			ShortDescription: `The resource zentral_taxonomy manages taxonomies.`,
			Description:      ``,
			Keywords:         []string{},
			Arguments:        []resource.Attribute{},
			Attributes:       []resource.Attribute{},
		},
	}

	resourcesMap = map[string]int{

		"zentral_jmespath_check":                 0,
		"zentral_meta_business_unit":             1,
		"zentral_monolith_catalog":               2,
		"zentral_monolith_condition":             3,
		"zentral_monolith_enrollment":            4,
		"zentral_monolith_manifest":              5,
		"zentral_monolith_manifest_catalog":      6,
		"zentral_monolith_manifest_sub_manifest": 7,
		"zentral_monolith_sub_manifest":          8,
		"zentral_monolith_sub_manifest_pkg_info": 9,
		"zentral_munki_configuration":            10,
		"zentral_munki_enrollment":               11,
		"zentral_osquery_atc":                    12,
		"zentral_osquery_configuration":          13,
		"zentral_osquery_configuration_pack":     14,
		"zentral_osquery_enrollment":             15,
		"zentral_osquery_file_category":          16,
		"zentral_osquery_pack":                   17,
		"zentral_osquery_pack_query":             18,
		"zentral_osquery_query":                  19,
		"zentral_santa_configuration":            20,
		"zentral_santa_enrollment":               21,
		"zentral_santa_rule":                     22,
		"zentral_tag":                            23,
		"zentral_taxonomy":                       24,
	}
)

func GetResource(r string) (*resource.Resource, error) {
	rs, ok := resourcesMap[r]
	if !ok {
		return nil, fmt.Errorf("resource %q not found", r)
	}
	return Resources[rs], nil
}
